### ISSUE TITLE
[Feature Request] Dashed or Dotted Border Line Styling

### ISSUE THREAD

**Issue by isalew** [archimatetool/archi#1044] opened 2024-04-19 18:05 UTC
I don't recall any Archimate language semantics forbidding the use of dotted or dashed borders on elements (See [3.9 Use of Colors and Notational Cues](https://pubs.opengroup.org/architecture/archimate3-doc/ch-Language-Structure.html)). [Grouping notation](https://pubs.opengroup.org/architecture/archimate3-doc/ch-Generic-Metamodel.html#sec-Grouping) could be the closest possible conflict, but I don't believe this is a mandatory constraint of the language.

Adding border styles could help to express considerations more intuitively to various stakeholder groups, like how the [Salesforce Diagram Framework](https://architect.salesforce.com/diagrams/framework/data-model-notation) uses to differentiate between conceptual vs. concrete elements.

(NOTE: The SF Diagramming Framework uses rounded edges on everything, even structural elements. I'm NOT interested in changing that, just noting the use of color and border styles to help create visual distinction).

![](https://architect.salesforce.com/1/asset/immutable/s/17125931930000000/assets/images/data-models/sample-legend-entities.png)

**Comment by Phillipus** [comment] 2024-04-19 18:39
Duplicate of https://github.com/archimatetool/archi/issues/702

**Closed by Phillipus** 2024-04-19 18:39 UTC
