### ISSUE TITLE
Relationships (Association) on relationships doesn't appear in Navigator or Visualiser

### ISSUE THREAD

**Issue by LionelLD** [archimatetool/archi#562] opened 2019-11-24 17:44 UTC
### Version of Archi, Operating System

4.6, Windows 10
### Expected Behaviour

Depending on the direction of the relation to a relationship (Achimate 3), it should appear in the navigator tree or the Visualiser window

### Actual Behaviour

Below a relation in the navigator, there only are elements connected to the relation, no relations connected to (or from)
<img width="418" alt="Capture" src="https://user-images.githubusercontent.com/58145380/69498632-360a4400-0eea-11ea-82a8-be8504538a54.PNG">

### Steps to Reproduce the Behaviour
1.Create AC1 and AC2, two applications components
2.Create a Flow relationship between AP1---FlowR-->AP2
3.Create a dataobjet DO1
4.Create an Association relation from DO1 to FlowR
5.Select the FlowR and observe Navigator or Visualiser : no way to found connected DO1

**Comment by Phillipus** [comment] 2019-11-24 18:06
Duplicate of #420

Sorry, can't fix.

**Closed by Phillipus** 2019-11-24 18:06 UTC

**Comment by LionelLD** [comment] 2019-11-24 18:28
Understood...
Would have been great...

Congrats for all the work already done in Architool, I've discovered 3 months ago !
Keep on !

**Comment by LionelDL** [comment] 2020-07-25 14:47
Thank you very much. I get it with 4.7 version.
THX !
