### ISSUE TITLE
[Bug] File not closed when error during import of exchange file

### ISSUE THREAD

**Issue by FransFaase** [archimatetool/archi#274] opened 2017-09-20 09:17 UTC
### Version of Archi, Operating System

Version 4.0.3 Build 201709061211

### Actual Behaviour

When an error occurs during an import of an ArchiMate Exchange file, it seems as if the file remains open (and locked) until Archi is closed.

### Steps to Reproduce the Behaviour
1. Open Archi
2. Import file not confirming to the XSD's
3. Saving named file in text editor does not work. File seems to be locked.

**Comment by Phillipus** [comment] 2017-09-20 09:24
Thanks, Frans. Do you have a simple import file that causes this?

**Comment by Phillipus** [comment] 2017-09-20 09:31
Actually I can reproduce it. The file is locked for as long as the error dialog is shown. Closing the error dialog releases the locked file.

**Comment by Phillipus** [comment] 2017-09-20 09:49
See https://stackoverflow.com/questions/6900939/moving-files-after-failed-validation-java

**Comment by Phillipus** [comment] 2017-09-20 09:55
Fixed. Will be in next Archi release. Thanks for reporting.

(Re-open if the issue is still present in next build)

**Closed by Phillipus** 2017-09-20 09:55 UTC
