### ISSUE TITLE
Images set as "fill" are cropped

### ISSUE THREAD

**Issue by devnewton** [archimatetool/archi#868] opened 2022-09-12 08:25 UTC
### Version of Archi
4.9.3

### Archi Plug-ins
None.

### Operating System
Windows 11.

### Expected Behaviour

A custom image with position set as "fill" should fill the component.

### Actual Behaviour

![image](https://user-images.githubusercontent.com/103828758/189607000-d565ffbd-db26-4b0b-8536-9a5d6aeebceb.png)

### Steps to Reproduce the Behaviour
1. Add a component ;
2. Set a custom image
3. Set position as "Fill"

**Comment by Phillipus** [comment] 2022-09-12 08:29
This uses the "Cover Fill" algorithm. See https://www.w3schools.com/css/css3_object-fit.asp

"cover - The image keeps its aspect ratio and fills the given dimension. The image will be clipped to fit"

**Comment by Phillipus** [comment] 2022-09-12 12:44
I'll close this as this is intended behaviour. We discussed this in [this very long thread](https://github.com/archimatetool/archi/issues/705).

**Closed by Phillipus** 2022-09-12 12:44 UTC
