### ISSUE TITLE
Properties tab in view does not show the properties of the selected object

### ISSUE THREAD

**Issue by jbouwh** [archimatetool/archi#214] opened 2017-04-01 12:21 UTC
For entering/viewing  additional properties or details of an object in an Archimate view the properies windows/tab can be shown using ALT+ENTER or ALT+2 or using the context menu. After showing the properties of an object the properties window is not changing context to the new selected object. ALT+ENTER or the properties context menu does not work. Work-a-round is closing the properties window and reopeing again. Selecting the object in the Model Tree does not work either. Select in Model Tree says: 'Properties are not availible in the Properties window.
Used software version: 4.0.0. Build 201702211434. Beta 7.
Platform: Windows 10 professional.

**Comment by Phillipus** [comment] 2017-04-01 12:24
Which version of Archi is this? Mac, Windows, Linux? Steps to reproduce?

**Comment by jbouwh** [comment] 2017-04-01 12:25
I updated the the call with the version information.

It happens always.

**Comment by Phillipus** [comment] 2017-04-01 12:26
Did you try beta 8?

**Comment by jbouwh** [comment] 2017-04-01 12:28
I'll give it a try!

**Comment by jbouwh** [comment] 2017-04-01 12:30
Beta 8 has the same problem

**Comment by Phillipus** [comment] 2017-04-01 12:31
I can't reproduce the problem here. You need to give more details on how to reproduce this.

**Comment by jbouwh** [comment] 2017-04-01 12:36
I don't see the problem in a new generated model. It must be some problem with the model itself.

**Comment by jbouwh** [comment] 2017-04-01 12:40
For now I do not see the problem any more. Some how the problem presited even after closing down the application (beta 7). Now the bug seem te be gone.

**Comment by Phillipus** [comment] 2017-04-01 12:42
Closing. Re-open if it happens again .;-)

**Comment by Madhur744** [comment] 2017-06-02 18:56
I had encountered similar issue multiple times earlier with beta versions of Archi 4.
It was difficult to create the simulatable sequence to reproduce this issue.
Now I have found the steps to simulate this repeatedly.

Environment:
Archi Version 4.0.1
Build: 201705261613
macOS Sierra Version 10.12.5

Create a new ArchiMate model with few elements in a view.
**Close ALL views** and save the model. **Close properties window** and then close the model.
Open the newly created model.
Select any element in models window, press properties, properties of the selected element are shown in the properties window.
Select any other element in models window, press properties, properties of the previously selected element will continue to be shown.
Close / Quit Archi without closing the model.
Reopen Archi.
CLUE1:  **_“Properties are not available”_** message is seen in the Properties window
Select any element in Models window, press properties, the same message persists
Close Properties window.
Select any element in models window, press properties, properties of the selected element are shown in the properties window.
Select any other element in models window, press properties, properties of the previously selected element will continue to be shown.
Close the model. Properties of the previously selected element will continue to be shown in the properties window. 
CLUE2: **_It should actually go out of context_** but continues to be there. 
These two clues might provide the insights to resolve the properties window issue

**Comment by Phillipus** [comment] 2017-06-02 19:06
> CLUE1: “Properties are not available” message is seen in the Properties window

That's because when re-opening Archi nothing is selected in the tree

I still can't reproduce this. It may depend on your arrangement of tabs and views in Archi. Do you have any editors or views maximised?

**Comment by Madhur744** [comment] 2017-06-02 19:26
All windows and views are closed.
First the model window was opened (It opened on the left side of the main window - its default position).
Then the file was opened. NO views are opened.
Element is selected and properties menu item is selected ==> Properties window opens (it opened in the right side bottom  of the main window - its default position).
There are no Open views, no resizing, no change of properties. 
All these steps were done on a fresh installation on Archi and a freshly created Archimate File.

I included CLUE1 for three reasons to indicate there could be interelations in the behavior,
1.  when **NO element was selected** to view the property, property window should not have tried to fetch the property. 
2. when another element is selected, property window is not detecting the change in element in modals window
3. when model itself is closed, it should have let go the details of the last selected element.
This behavior indicates something missing in event handing on changes in modals window or the context in which the property window fetches the properties.

**Comment by Phillipus** [comment] 2017-06-02 19:30
How are you opening Properties window? Right-click menu? Main Menu? Keyboard shortcut?

**Comment by Madhur744** [comment] 2017-06-02 19:39
Tried opening the properties window by
1. Double clicking on the element
2. Right click on the element and selecting the properties
3. Keyboard shortcut (command + I)
Behavior is the same in all these cases.

If the property window is not open, It opens the property window properly.
If the property window is already open or for subsequent selections, there is no change in the property window, until you close the property window.

**Comment by Phillipus** [comment] 2017-06-02 20:33
I must be missing some key thing because I still can't reproduce this. Anyone else like to try it?

**Comment by Madhur744** [comment] 2017-06-02 20:36
Third method of simulating this issue is:

Open any view which has elements.
Maximize the view.
In the view, select the element and view properties,
Properties window opens in top right corner.
Restore the size of property window, property window moves to the bottom.
Click on any other element, property window changes the property of the view (instead of the element).
Select another element in the view and view properties, Instead of the element’s property, You will see the properties of the view.
This behavior continues until you close the property window and select another element to view the properties.

**Comment by Phillipus** [comment] 2017-06-02 20:41
OK, I can reproduce the last case.

I think this problem occurs under some circumstances that may involve a maximised view. I think it may be related to this Eclipse bug which is supposed to be fixed:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=509405

If it is an Eclipse bug then I can't fix it.

**Comment by Madhur744** [comment] 2017-06-02 22:56
Another interesting/funny/related/not-related (based on how you look at it) observation on the properties window.
Couple of weeks/months back I had upgraded Archi Beta (may be from 7 to 9). When I opened an existing Archimate File, In the views, the drawings were looking messed up as that version read my preferences (for default figures) differently or the logic was changed in that version.I reselected the default figures in preferences and corrected the views. It is fine from that point onwards.
Issue of properties window was there earlier and even seen in the GA release.

I have used Archi 3.3.2 and almost all beta version of 4 on this Mac system.
I presume, preferences are stored in different location on Mac (outside the installation directory).
Previous experience (stated above) on the preferences, made me curious today to look into any thing else in preferences that might require a reset.
In Preferences ==> General ==> Appearance
    1. Changed the theme from Mac to Classic and ran the test of Properties window.
        Result was same, then reverted back to Mac.
    2. **_Unchecked "Show Status Bar" (unset)_** . As it requires restart of Archi, Saved the preferences and closed Archi.
        Reopened Archi and ran the test of Properties window. **Except for third method (of maximized window), properties window started behaving properly.**
        Context switching was happening. Repeated the test couple of more times, result was looking fine.
        Even opened large Archimate Files (>3MB) with more than 750 elements, seems to be working now.
   3. Once again _**Checked "Show Status Bar" (set)**_. As it requires restart of Archi, Saved the preferences and closed Archi.
        Reopened Archi and ran the test of Properties window. Except for third method (of maximized window), properties window behaved properly.

> STRANGE !!

**What is that changed the behavior of properties window**?
a) Changing the setting/flag for "Show Status Bar" in Preferences?
b) Change in the preferences (version 3 to 4) data/setting/defaults initiated by the change in Preferences?
c) Differences in customized preferences in version 3 and version 4?
d) If NONE of the above, then what restored the behavior?
    
Regarding the eclipse bug mentioned in your response with respect to maximized view window, after encountering no changes in property window, without closing property window, if the model window is restored and the navigation of elements in done either from view window or model window,  property window changes with respect to the context selected and sometimes it does not. It works in most cases, when the status bar is off, but does not respond (relatively) more frequently when the status bar is on. No response status is there with / without the status bar on, only the frequency of occurrence differs. 

What is impact of settings for status bar or the custom preferences on the tool, If any?

While navigating elements of the large Archimate File from the models windows and viewing its properties in property window (with no other views / windows open)
Navigation was instant and seamless when Status Bar was disabled (unset in preferences).
Navigation was lagging/delayed and sometime appears not to be changed (changes after a while) when Status Bar was enabled (set in preferences).
There was no perceptible difference in navigating the smaller Archimate files immaterial of the status bar setting.
If Status Bar has any role in impacting the performance of navigation and/or on properties window, Can the last paragraph be treated under this (the current) issue(#214), or it should be recorded as a separate issue

**Comment by Phillipus** [comment] 2017-06-03 08:20
I'm not sure status bar has anything to do with it. I think it is an Eclipse bug related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=509405 and having a maximised view. I never see this issue now I think because I don't maximise any views or editors.

**Comment by theunsfvo** [comment] 2017-09-20 12:43
I'm getting it also, using and old model from previous versions of Archi...

What is interesting though, is if you dock the properties window to the left hand side, it updates properly when you switch between elements...

**Closed** 2019-11-14 16:35 UTC
Labels: help wanted
