### ISSUE TITLE
[Linux] Tree text cell editor not working when starting with no tree nodes

### ISSUE THREAD

**Issue by gtc-bigyin** [archimatetool/archi#617] opened 2020-05-05 15:14 UTC
### Version of Archi

4.7 Build 202004301130
see installation log attached
### Archi Plug-ins

See installation log attached

### Operating System

Linux Unbuntu
### Expected Behaviour

When selecting a view or folder in the model the cursor should highlight the text indicating that it is being changed and the text when entered show
### Actual Behaviour

When selecting a view or folder in the model the cursor does not show and you do not see the text being entered, however hit return and the text is auctioned
### Steps to Reproduce the Behaviour
1.  Consistently there
2.
3.
[Archi Installation Log.txt](https://github.com/archimatetool/archi/files/4581684/Archi.Installation.Log.txt)

**Comment by Phillipus** [comment] 2020-05-05 15:19
Which cursor do you mean? Please also - steps to reproduce.

**Comment by gtc-bigyin** [comment] 2020-05-05 15:21
The cursor where you rename the folders or elements in the model.

Happy to show you using zoom, etc


M

**Comment by Phillipus** [comment] 2020-05-05 15:23
Which version of Ubuntu?
Do you have Wayland on?
Do you mean the text I beam cursor?

**Comment by gtc-bigyin** [comment] 2020-05-05 15:25
Linux matt-VirtualBox-GTCprod 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

No idea re Wayland

Yes I think I mean that cursor.. when you want to change a name F2 then type etc

M

**Comment by Phillipus** [comment] 2020-05-05 15:29
> Linux matt-VirtualBox-GTCprod 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I can't tell from that what version of Ubuntu it is.

**Comment by gtc-bigyin** [comment] 2020-05-05 15:32
Sorry was doing three things at once - Ubuntu 18.04.4 LTS

**Comment by Phillipus** [comment] 2020-05-05 15:33
Perhaps a screen shot might help...

**Comment by gtc-bigyin** [comment] 2020-05-05 15:34
The screen shot won’t show anything (that’s the bug …)  .. that’s why I suggest a zoom desktop share to show you ..

**Comment by Phillipus** [comment] 2020-05-05 17:25
I can reproduce this on Ubuntu 18.04 with Archi 4.6 and 4.7

The issue is that under some circumstances the text editor control does not appear in the Models Tree on Rename action.

1. Launch Archi with an empty Models Tree (this stage is important)
1. New Model
1. Try to rename the Default View or add an element and try to rename it
1. The text edit control does not appear

To get it to work launch Archi with a model already open in the Models Tree or close the Models Tree and re-open it (ensure that it contains a model).

Some observations:

1. This does not happen on Archi 4.5.1 (that uses Eclipse 4.11)
1. This does not happen on Ubuntu 19.10
1. The same thing happens in the jArchi Scripts Manager
1. It is only happening if the Models Tree (or Scripts Manager) is initially empty. If there are tree nodes when these are opened the text editor works.

**Comment by Phillipus** [comment] 2020-05-05 17:36
And I can reproduce this on Linux Mint (based on Ubuntu 18.04).

The key to reproducing this bug is to ensure that the Models Tree is initially empty. Add a new model and the tree nodes do not show a text editor control. Close and re-open the Models Tree (with at least one model in it) and it works.

Right now I have no idea if this is an Eclipse or a GTK issue. I'll need to test with Eclipse 4.15.

**Comment by gtc-bigyin** [comment] 2020-05-05 17:57
Ok , let me know if I can test a release etc when your ready ..


M

**Comment by Phillipus** [comment] 2020-05-05 18:09
> Ok , let me know if I can test a release etc when your ready ..

I don't think there's anything I can fix if it is an Eclipse bug.

**Comment by Phillipus** [comment] 2020-05-05 18:41
I've tested this against Eclipse 4.15 (Archi 4.6 and 4.7 EA are built against Eclipse 4.13) and it seems to be fixed.

I know that the Eclipse people "fixed" some GTK issues in later versions of Eclipse for Linux. But with any Eclipse "fixes", something else is broken (a.k.a "Fix one, break one).

I don't like this bug because a brand new Archi installation on Linux, followed by a "New Model" leads to the user not being able to rename things in the Models Tree.

@jbsarrodie I'm going to build Archi 4.7 on top of Eclipse 4.15 - I know there are other fixes in that version that we could benefit from apart from this one.

**Comment by jbsarrodie** [comment] 2020-05-05 18:44
I can reproduce this bug. FWIW, when it happens, toggling the model tree off and on solve the issue, but that's really annoying.



> @jbsarrodie I'm going to build Archi 4.7 on top of Eclipse 4.15 - I know there are other fixes in that version that we could benefit from apart from this one.

Ok, let's see what gets broken ;-)

**Comment by Phillipus** [comment] 2020-05-05 18:48
> Ok, let's see what gets broken ;-)

Well...something like this bug, which got broken somewhere between 4.11 and 4.13...

**Comment by jbsarrodie** [comment] 2020-05-05 18:56
> Well...something like this bug, which got broken somewhere between 4.11 and 4.13...

Or something like setting the clipping area on connexions...

**Comment by Phillipus** [comment] 2020-05-05 18:57
> Or something like setting the clipping area on connexions...

Yes, that one too.

**Comment by Phillipus** [comment] 2020-05-06 09:43
Even though this seems to be fixed in Eclipse 4.15 I opened a bug report just in case there are underlying issues:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=562872

**Comment by Phillipus** [comment] 2020-05-06 13:16
> Even though this seems to be fixed in Eclipse 4.15 I opened a bug report just in case there are underlying issues:
> 
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=562872

It's this one https://bugs.eclipse.org/bugs/show_bug.cgi?id=550606

**Comment by Phillipus** [comment] 2020-05-11 08:03
@gtc-bigyin This should be fixed in Archi 4.7 beta 1 - https://www.archimatetool.com/beta/

**Comment by gtc-bigyin** [comment] 2020-05-11 09:48
Tested, seems to work ok ..

M

**Comment by Phillipus** [comment] 2020-05-11 09:50
> Tested, seems to work ok ..

Thanks. It was an Eclipse bug (https://bugs.eclipse.org/bugs/show_bug.cgi?id=550606) and Archi 4.7 is now built on Eclipse 4.15 which has the fix.

I'll close this one, thanks for reporting it.

**Closed by Phillipus** 2020-05-11 09:50 UTC
