### ISSUE TITLE
May be a bug when importing Open Exchange File 

### ISSUE THREAD

**Issue by wuzheng650** [archimatetool/archi#839] opened 2022-05-03 14:48 UTC
### Version of Archi
4.9.3

### Archi Plug-ins
no

### Operating System
Windows

### Expected Behaviour
The Open Exchange File could be imported.

### Actual Behaviour

![image](https://user-images.githubusercontent.com/9996235/166474811-94fbd16d-f96d-4f29-8844-f32991f5060d.png)
May be , the problem is due to Archimate requires all the nodes about 'connection' must be in the last of node of 'view'.

### Steps to Reproduce the Behaviour
1.file
2.import
3.Model from Open Exchange File...
4.select the import file
[pcf-example.zip](https://github.com/archimatetool/archi/files/8611251/pcf-example.zip)

**Comment by wuzheng650** [comment] 2022-05-03 16:14
Yes, when I move all the <connecton> tags to the last place within the <view> tag,  the file can be imported correctly.
I think child nodes under the same node in XML are parallel relationship.
The location of <connection> will lead to an error in importing. Is this a special requirement for Archimate Open Exchange File?

**Comment by Phillipus** [comment] 2022-05-03 16:40
> Is this a special requirement for Archimate Open Exchange File?

Yes. The XML must conform and validate to the Schema, see http://www.opengroup.org/xsd/archimate/

**Comment by Phillipus** [comment] 2022-05-03 19:34
I'll close this as this is not a bug in Archi.

**Closed by Phillipus** 2022-05-03 19:34 UTC

**Comment by wuzheng650** [comment] 2022-05-04 09:38
Thank you very much. I found the requirements in \<xs:sequence\>.
