### ISSUE TITLE
[Linux] 4.7 Beta - NPE on Clipboard

### ISSUE THREAD

**Issue by gtc-bigyin** [archimatetool/archi#592] opened 2020-03-11 12:00 UTC
!SESSION 2020-03-11 11:03:59.158 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -clean

!ENTRY org.eclipse.ui.workbench 4 2 2020-03-11 11:26:15.205
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
	at java.base/java.lang.String.<init>(Unknown Source)
	at com.archimatetool.editor.ui.LocalClipboard$1.nativeToJava(LocalClipboard.java:54)
	at org.eclipse.swt.dnd.Clipboard.getContents(Clipboard.java:323)
	at org.eclipse.swt.dnd.Clipboard.getContents(Clipboard.java:243)
	at com.archimatetool.editor.ui.LocalClipboard.getContents(LocalClipboard.java:99)
	at com.archimatetool.editor.ui.LocalClipboard$2.windowActivated(LocalClipboard.java:77)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:1022)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench.fireWindowActivated(Workbench.java:1019)
	at org.eclipse.ui.internal.WorkbenchWindow$8.shellActivated(WorkbenchWindow.java:2482)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:92)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5618)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1405)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1431)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1410)
	at org.eclipse.swt.widgets.Shell.gtk_focus_in_event(Shell.java:1560)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2241)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6846)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5842)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4154)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1474)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1603)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4404)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at com.archimatetool.editor.Application.start(Application.java:84)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
### Version of Archi, Operating System

Linux - ubuntu running on Oracle VM

### Expected Behaviour

Launch without error
### Actual Behaviour

error on launch 
Running V 4.6 on same machine no error

### Steps to Reproduce the Behaviour
1. Launch App
2.
3.

**Comment by Phillipus** [comment] 2020-03-11 12:06
Can you say what was on the system clipboard when you launched the app?

**Comment by gtc-bigyin** [comment] 2020-03-11 12:08
Nothing in the VM, but something (snip) in the windows host

Currently

[cid:image001.png@01D5F7A6.221AEF40]

**Comment by gtc-bigyin** [comment] 2020-03-11 12:09
Happy to whatsapp or skype if you want me to try something

**Comment by Phillipus** [comment] 2020-03-11 12:41
Might be related to #575

**Comment by Phillipus** [comment] 2020-03-11 12:50
@gtc-bigyin Can you try the same thing with this build:

https://www.archimatetool.com/downloads/temp/Archi-Linux64-4.7.0-ea2a.tgz

**Comment by gtc-bigyin** [comment] 2020-03-11 12:56
Seems to have corrected the issue

Matt

**Comment by Phillipus** [comment] 2020-03-11 13:01
@gtc-bigyin Thanks for testing.

I wonder if you could get a reproducible test case and double check that the bug occurs on Archi 4.7 ea2 but not on Archi 4.7 ea2a? (Just to double check this fix)

For testing purposes you don't need to close and restart Archi, you can put the focus on another app and then put the focus on Archi. The clipboard contents are checked when Archi gets the focus.

Are you saying that you had something on the host clipboard? An image? Text?

**Comment by gtc-bigyin** [comment] 2020-03-11 13:38
See in line

**Comment by Phillipus** [comment] 2020-03-11 13:40
This and #575 are really strange bugs.

`org.eclipse.swt.dnd.ByteArrayTransfer#nativeToJava` should not be called by `org.eclipse.swt.dnd.Clipboard.Clipboard#getContents` unless the contents of the system clipboard has been copied from Archi. If something is copied to the system clipboard then this should never be called. But somehow it is.

**Comment by Phillipus** [comment] 2020-03-11 13:41
@gtc-bigyin Thanks for double-checking. Just to confirm - the new version ea2a doesn't have this problem?

**Comment by gtc-bigyin** [comment] 2020-03-11 13:53
No running version below with a model an no issue

[cid:image001.png@01D5F7B4.DAB6E190]

**Comment by Phillipus** [comment] 2020-03-11 13:57
Thanks. The workaround will be in EA3. I wish I could reproduce it. It might be something to do with suing a VM.

**Comment by gtc-bigyin** [comment] 2020-03-11 13:58
If there is something I can do (transfer the VM etc, there is nothing sensitive in it) let me know..

**Comment by Phillipus** [comment] 2020-03-11 14:07
Thanks, I might try with Oracle VM. Which version of Ubuntu?

**Comment by gtc-bigyin** [comment] 2020-03-11 14:09
[cid:image001.png@01D5F7B7.12449CE0]

**Comment by Phillipus** [comment] 2020-03-11 14:11
Sorry, images don't show on GitHub if you reply by email.

**Comment by gtc-bigyin** [comment] 2020-03-11 14:19
Linux DockerBox 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux


rom: Phil Beauvoir [mailto:notifications@github.com]
Sent: 11 March 2020 15:12
To: archimatetool/archi <archi@noreply.github.com>
Cc: Matthew Dickie <matthew.dickie@glentech.eu>; Mention <mention@noreply.github.com>
Subject: Re: [archimatetool/archi] 4.7 Beta - java.lang.NullPointerException (#592)


Sorry, images don't show on GitHub if you reply by email.

**Comment by Phillipus** [comment] 2020-03-12 10:49
Notes to self:

For some reason the Linux SWT GTK Clipboard code is getting the system Clipboard contents and wrongly assigning it to Archi's specific TransferData type. This also happened in #575 with the GEF Clipboard code

Another case here - https://bugs.eclipse.org/bugs/show_bug.cgi?id=526468 and a similar workaround - https://github.com/eclipse/webtools.common/commit/eb8cc8a97bf77c7cfba5fb41f99794157822096b

I'd be interested to know what combination of setup causes this. Is it a specific GTK version? Using a VM? Something else? I use VMWare Fusion on Mac and tested with Linux Mint and Ubuntu 18.04, 19.04 and 19.10 and can't reproduce it. And it must be OK for several other Archi Linux users. Intriguing.

**Comment by Phillipus** [comment] 2020-03-27 17:08
Should be fixed in Archi 4.7 EA3. Please try that version.

**Comment by gtc-bigyin** [comment] 2020-03-29 11:41
Tried seems to work without issues..

Matt

**Comment by Phillipus** [comment] 2020-03-29 11:54
Thanks for testing, I'll close this now.

**Closed by Phillipus** 2020-03-29 11:54 UTC
