### ISSUE TITLE
Q: XSD for archimate file format

### ISSUE THREAD

**Issue by normenmueller** [archimatetool/archi#627] opened 2020-05-20 21:58 UTC
Hi @Phillipus 

Just a quick question. I’m thinking of manipulating Archi’s file format (.archimate) — not the open exchange format — via XSLT. 

I wonder if there exists an XSD?

I’m concerned if there is some order specified on the XML elements (xs:sequence) or if the order is completely irrelevant.

**Comment by Phillipus** [comment] 2020-05-21 05:51
Hi,

the attached XSD has been generated by the Eclipse EMF model generator. However, looking at it, it is not accurate as it declares some elements as attributes ("documentation" for example). It should, though, give an idea.

[ArchimateXML.xsd.zip](https://github.com/archimatetool/archi/files/4660781/ArchimateXML.xsd.zip)

**Comment by Phillipus** [comment] 2020-05-22 18:26
I'll close this as it's not a bug or feature request. If you have any more questions related to this, the Archi forum is the best place for discussion.

**Closed by Phillipus** 2020-05-22 18:26 UTC

**Comment by normenmueller** [comment] 2020-05-23 07:10
@Phillipus Just a final note: Thanks for your help! In future I will use the Archi forum for questions. Fyi: I was able to re-sort the top-level folder structure and Archi read the modified file without any problems.
