### ISSUE TITLE
New HTML Report

### ISSUE THREAD

**Issue by prgee** [archimatetool/archi#112] opened 2015-03-02 19:03 UTC
Hi Phil,

I've just taken a look at the new ver 3.2 HTML report from JB et. al. It looks really great and I think it will be invaluable as a means of publishing models. I did notice the following issues:
1. View links within a diagram do not seem to work
2. URLs are not rendered as links and are not "clickable", whether they are in the description text or in a user-defined property.

Thanks and Regards,
Peter

**Comment by jbsarrodie** [comment] 2015-03-02 19:59
Hi,

_It looks really great and I think it will be invaluable as a means of publishing models_
Thank you a lot ;-)

_View links within a diagram do not seem to work_
I'm not sure to understand point 1, could you elaborate a little bit.

_URLs are not rendered as links and are not "clickable", whether they are in the description text or in a user-defined property._
Re point 2 that's unfortunately "by design" at the moment. FYI in order to avoid any issue with documentation or property value containing HTML code I had to use a specific HTML tag (XMP) which doesn't allow links.

I'm still looking for some workaround but am rather pessimistic :-(

Regards

JB

**Comment by prgee** [comment] 2015-03-02 20:16
My mistake, JB. The proper Archi term is "View Reference".

Peter

**Comment by jbsarrodie** [comment] 2015-03-02 20:20
Still not clear, do you mean that if you create a view containing view references, you don't see thoses references in the element list tab ? If not, could you please provide a simple example (model or screenshot) ?

**Comment by prgee** [comment] 2015-03-02 20:22
That's correct - the view references don't show up on the element tab.

**Comment by jbsarrodie** [comment] 2015-03-02 20:24
_That's correct - the view references don't show up on the element tab._

Ok, simple (but unfair) answer: a view reference in not an ArchiMate element ;-)

But, to be honest, it should be possible to make it work, so maybe in beta 2.

**Comment by prgee** [comment] 2015-03-02 22:11
I'll be cheering you on, JB :-D

**Comment by jbsarrodie** [comment] 2015-03-03 10:08
It seems it's still christmas time. I've found some solutions to solve both issues. Will be in beta 2.

**Comment by prgee** [comment] 2015-03-03 17:00
Sounds good - I'll watch for it. I have another question  about the HTML report. I have used the HTML publishing feature in Sparx EA to solicit feedback and was able to add a "mailto:" hyperlink to the template. This allowed me to place a ""Send Feedback" link on each element and view so that the reviewer could simply click the link to send a question or comment to me. The subject line was set to the name and type of the model element. Is something like this possible for your HTML report??

Cheers,
Peter

**Comment by jbsarrodie** [comment] 2015-03-03 17:16
That's something possible, but for the moment it would be a simple convertion of the text `mailto:me@anydomainname.com` to a real mailto link without additions: [mailto:me@anydomainname.com](mailto:me@anydomainname.com)

Include contextual information (model/view name should be possible, but we have to find a good way of doing it to limit future requests.

FYI - My mid term goal is to support Markdown to enable more rendering freedom.

**Comment by prgee** [comment] 2015-03-03 17:35
Markdown support makes a lot of sense. Thanks for the speedy replies!

**Comment by jbsarrodie** [comment] 2015-03-03 20:52
I've just committed patchs for links and view reference support.

@Phillipus : let's wait some time before building a new beta (I have published my main model internally and asked for colleagues to check it).

I'm closing this issue. Please open a new one if you find other bugs.

**Comment by jbsarrodie** [comment] 2015-03-04 08:58
@prgee FYI, if you want to try asap, you can manually update those files on your current installation (no compilationi required):
* https://github.com/archimatetool/archi/blob/html-report/com.archimatetool.reports/templates/html/css/model.css
* https://github.com/archimatetool/archi/blob/html-report/com.archimatetool.reports/templates/html/js/frame.js
* https://github.com/archimatetool/archi/blob/html-report/com.archimatetool.reports/templates/st/frame.stg

;-)

**Comment by jbsarrodie** [comment] 2015-03-04 09:02
Last comment, a longer term feature would be to let (power) users customize or create their own report (which are in fact a mix of HTML/CSS/JS created through [StringTemplate](http://www.stringtemplate.org/)

**Comment by prgee** [comment] 2015-03-05 20:22
I updated those files per your suggestion. Seems to work well although it should support URL links in user-defined properties as well. I've been reading about StringTemplate - it's quite impressive !

**Comment by jbsarrodie** [comment] 2015-03-05 20:53
In fact I realize that my fix only works for documentation field, not properties.

I'm reopening the issue (not sure to find a good solution but who knows)

**Comment by guidohajanssen** [comment] 2016-08-28 07:04
I started a project based on the Exhange Format blog and the HTML report that has a lot of the features you are looking for. See https://www.github.com/guidohajanssen/archimateviewer en http://www.archimateviewer.nl

**Closed** 2019-08-09 14:22 UTC
