### ISSUE TITLE
Archi 4.8.1 - unable to bring in pallette objects into main window (worked on Archi 4.7.1)

### ISSUE THREAD

**Issue by jmiller9591** [archimatetool/archi#707] opened 2021-02-12 14:30 UTC
error log and screen print attached

### Version of Archi

4.8.1

### Archi Plug-ins

Archi Collaboration, database & specialization plug-ins from Herve'

### Operating System

Mac - 11.2.1 (Big Sur)

### Expected Behaviour

Dragging an object from the palette window should allow one to work with it in the main window.

### Actual Behaviour

When dragging an object from the palette to the main window, I get the error message as shown by the screen shot I attached.  If I acknowledge the error, I am unable to work with the object in the main window (an outline appears)

I tried this on Big Sur with 4.7.1 version (without any plug-ins installed) and was able to successfully work with objects from the palette to the main window.   I did remove and replace prior version of Archi with 4.8.1, however I have been using Archi for several years so there may be older cruft in my user directory that was referenced in past although not sure that is issue?  Many thanks for your help!

### Steps to Reproduce the Behaviour
1. Start Archi -> new model
2. Drag an object into main win
3. Receive screen shot error

[Archi02122021_log.pdf](https://github.com/archimatetool/archi/files/5972381/Archi02122021_log.pdf)
<img width="1319" alt="Archi_02122021_pix" src="https://user-images.githubusercontent.com/44744538/107780225-06707300-6d0c-11eb-8376-4b8a9d8b1560.png">

**Comment by jmiller9591** [comment] 2021-02-12 14:38
02/12/2021 - tried again with 4.7.1 and OS popped window that Archi wanted access to directory where a file was kept.  I hit radio button for "ok" and then 4.7.1 now gives me same error.  Wanted to mention this.  I am going to re-download 4.8.1 and and leave on my desktop to see if where Archi or if Archi needs access to directory folder makes a difference.

**Comment by Phillipus** [comment] 2021-02-12 14:39
Please try without the database and specialization plug-ins installed. The error log is suggesting one of these is the cause.

**Comment by jmiller9591** [comment] 2021-02-12 14:48
02/12/2021 - tried again w/4.8.1 and did not allow Archi to have access to documents folder - same issue; retried 4.7.1 and did not allow access to documents folder and now 4.7.1 has same issue as well.  (note: I do not recall 4.7.1 on first install asking for permissions to document folder, if that helps)

**Comment by Phillipus** [comment] 2021-02-12 14:49
As I said:

Please try without the database and specialization plug-ins installed. The error log is suggesting one of these is the cause.

**Comment by jmiller9591** [comment] 2021-02-12 14:49
02/12/2021 - Hi Phil, thanks.  When I last tried 4.8.1 again, I did not have any plug-ins installed and received same type of behavior.  Hope this helps and many thanks again for your help.

**Comment by Phillipus** [comment] 2021-02-12 14:53
The error log show that the problem is the specialization plugin.

```java.lang.NullPointerExceptionat org.archicontribs.specialization.propertysections.SpecializationModelSection.getSelectedClass(SpecializationModelSection.java:1177```

**Comment by jmiller9591** [comment] 2021-02-12 14:55
02/12/2021 - Hi Phil.  I did a "uninstall" from main menu for all plugins except collaboration plugin.  Now normal behavior.  Will check for any updates for this plugin from Herve's work and then see if a re-install of that gets me on my way.  Many thanks again for your help!!!

**Comment by Phillipus** [comment] 2021-02-12 14:57
I'll close this as it's almost certainly the Specialization plug-in causing the problem.

**Closed by Phillipus** 2021-02-12 14:57 UTC
