### ISSUE TITLE
feature request: view reference property

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#783] opened 2021-11-03 10:11 UTC
Archi supports view reference components but lets one do very little with them - they just sit on the diagram and can be clicked, that's all. It would be nice if view reference property could be added to component of any type and it would be possible to create e.g. an application component on a top-level diagram and link it to a view explaining the inner workings of this component. Essentially a diagram with drill-down capability.

**Comment by Phillipus** [comment] 2021-11-03 10:13
Closed as duplicate of #782

**Closed by Phillipus** 2021-11-03 10:13 UTC
