### ISSUE TITLE
[Feature Request] Zoom and panning in html report

### ISSUE THREAD

**Issue by Ujifman** [archimatetool/archi#843] opened 2022-05-19 15:19 UTC
Hello, I found two features that will increase usability of html report, when you in `views diagrams`.
1. Zoom in/out with ctrl+/- for diagram. By default ctrl+/- change zoom for all browser page. It would be more usefull if ctrl+/- will duplictate zoom slider and change zoom for diagram only.
2. Panning with click and move. Usually views are rather huge, and one needs zoom in and move view. Now one can move only with scroll bars, but it is not useful. It would be great to move view just like in program with click and move wheel button of mouse.

My idea is just to add some js code to report building tool, that will implement described behavior.

**Comment by Phillipus** [comment] 2022-05-19 15:28
> My idea is just to add some js code to report building tool, that will implement described behavior.

Are you offering to provide the JS code? If so, a draft PR would work.

**Comment by Ujifman** [comment] 2022-05-19 15:31
Yes I already have js code that implements it, and now I study your code to find the right place for it, ad i suppose it should be in `com.archimatetool.reports\templates\html` am I right?

**Comment by Phillipus** [comment] 2022-05-19 15:33
Yes, that's correct. Thanks for taking a look at it.

**Comment by Phillipus** [comment] 2022-05-19 15:43
> So now I can prepare pull request?

Yes, a draft PR in a branch of forked Archi code is the way to go.

**Comment by Ujifman** [comment] 2022-11-10 13:41
Sorry for long time for implementing, but finally I've got pull request about this feature #882

**Comment by Phillipus** [comment] 2022-11-10 13:55
Thanks for this, I merged it.

**Comment by Phillipus** [comment] 2022-12-09 19:15
@Ujifman Hi, I've found a problem with `panelBodyScroller.js`. The text field for inputting alasql queries on the "Query" tab in the report cannot receive text input. The problem occurs on line 16:

```js
  const mouseDownHandler = function (e) {
    e.preventDefault(); <-------------------- Here!
```

Would you be able to take a look at this?

BTW - I've edited the file to support IE11

**Comment by Phillipus** [comment] 2022-12-09 22:08
One thing I tried that seems to work is removing the `e.preventDefault();` line and adding this:

```
  document.getElementsByClassName('diagram')[0].addEventListener('mousedown', function (e) {
    e.preventDefault();
  });
```

**Comment by Phillipus** [comment] 2022-12-10 10:40
I've created a branch `html-fix` with my attempt at a fix. Also, I don't think it's a good idea to show a "grab" cursor by default.

https://github.com/archimatetool/archi/commit/cc594b504dffc2c49eaa1a2ea203dbd1fe0f43eb

**Comment by Ujifman** [comment] 2022-12-11 17:16
@Phillipus Hi, sorry, I've missed alert from GitHub, had some crazy days at work. As I see you already fixed the issue, do you need some help?

**Comment by Phillipus** [comment] 2022-12-11 17:31
@Ujifman Hi, I just wanted to check it with you, first. Do you see any problems with my proposed fix?

**Comment by Ujifman** [comment] 2022-12-11 17:50
> @Ujifman Hi, I just wanted to check it with you, first. Do you see any problems with my proposed fix?

Looks nice! I don't see any problems.

**Comment by Phillipus** [comment] 2022-12-11 18:01
Thanks for the feedback. I'll commit it,

**Comment by Phillipus** [comment] 2023-01-07 07:06
Hi, this is causing problems as noted by @evlibra:

https://github.com/archimatetool/archi/commit/5f81eed9a062aee3f2a1c63556265c268946b10b#commitcomment-95334110

https://github.com/archimatetool/archi/commit/b8c4163451a1e791f29d219d4b6e5e6122603306#commitcomment-95333906

We should reconsider this one for Archi 5 and find a way to only pan when the mouse is down on a diagram. If not we should remove this feature for now and come back to it.

@Ujifman Can you find a way to do this?

**Comment by Phillipus** [comment] 2023-01-08 18:16
I think I've fixed this issue now. @evlibra: please test.

**Comment by evlibra** [comment] 2023-01-08 21:55
> I think I've fixed this issue now. @evlibra: please test.

Thanks @Phillipus. Yes, the issue is fixed now - frames beyond the diagram are not impacted. The only question is whether grabbing shall be allowed only within boundaries of diagram elements (see area in green on the screenshot), or within whole diagram frame, meaning also area at the right from the diagram. At the moment is is only within diagram's elements, but intuitively one might expect also grab at right from it. See the screenshot
<img width="511" alt="image" src="https://user-images.githubusercontent.com/48681198/211221000-1107d1a6-8d1e-4d41-b4e3-719a43022cb3.png">

**Comment by Phillipus** [comment] 2023-01-08 22:01
I'm sorry but I can't spend any more time on this issue, I've tried my best to make it work based on @Ujifman 's PR. If it continues to be a problem I will remove it.

**Comment by Phillipus** [comment] 2023-01-08 22:19
This is now removed. I've left the mouse scroll wheel feature in.

Please resubmit a working PR that we might consider for Archi 5.1.

**Closed by Phillipus** 2023-01-08 22:19 UTC

**Comment by Ujifman** [comment] 2023-01-09 07:13
@Phillipus I'll try to find out a way to fix it.
