### ISSUE TITLE
label $association:source{name} not appearing on diagram

### ISSUE THREAD

**Issue by peterprib** [archimatetool/archi#874] opened 2022-10-17 23:16 UTC
### Version of Archi
4.10.0

### Archi Plug-ins
jarchi

### Operating System
windows 11

### Expected Behaviour
When relationship line has label to associated object it label appears in view regardless of whether association is in view. 
Actually it would be better to have a control which details behaviour based on being in view vs model. 

### Actual Behaviour
label $association:source{name} to appear when association not in view

### Steps to Reproduce the Behaviour
1. add app component 1
2. add app component 2
3. Add flow between 1 and 2 with label $association:source{name} 
4. add data object
5. add association to flow from data object, and name appears on flow
6. delete data object from view and label disappears
7. select data object created and add to view label appears
8. select app 1 and add to view, one flow has label and other doesn't

**Comment by Phillipus** [comment] 2022-10-18 08:41
This is expected behaviour. An expression label is applied per View instance, so when the additional instance of the flow connection is added you need to add the label expression to that instance as well. It is possible to have two different label expressions for each instance.

**Comment by Phillipus** [comment] 2022-10-21 18:57
I'll close this as working as intended.

**Closed by Phillipus** 2022-10-21 18:57 UTC

**Comment by peterprib** [comment] 2022-10-22 01:22
Sounds a severe limitation in feature if it can only reach to objects on view especially via relationships.  There should be the option of either view or model.  When it comes to projecting information in a label I'm more likely to reach to an object via relationship that is not on the view to minimise the number of object on view,  that is, declutter lines and boxes on the diagram.  One would have thought model would be easy to implement.
