### ISSUE TITLE
UI Dark Theme

### ISSUE THREAD

**Issue by kirkpabk** [archimatetool/archi#906] opened 2023-02-06 12:52 UTC
Great feature - however, default font in models tree and scripts tree boxes are "black" on the dark background.  Cannot find a way to change the font color that sticks.  Very hard to see.

**Comment by Phillipus** [comment] 2023-02-06 14:00
You don't say whether you are on Windows, Linux or Mac. Assuming you're on Windows, then yes, selected tree cells are too dark. We use the Eclipse Dark Theme and the CSS for this is located here:

```C:\Program Files\Archi\plugins\com.archimatetool.editor.themes_XXXXXXX\themes\eclipse\css```

Perhaps you could experiment with different CSS settings and find something that works better?

**Comment by Phillipus** [comment] 2023-02-07 11:59
It turns out that improved dark theme support is implemented in Eclipse 4.26 and later (dark menus and improved selected tree cell colors). Archi is built on Eclipse 4.25. When Eclipse 4.27 is released I will try to build Archi on this version of Eclipse, assuming there are no serious regressions and bugs in Eclipse 4.27 (there usually are, so don't hold your breath).

**Comment by Phillipus** [comment] 2023-02-08 08:42
I'll close this. As I said, it's an Eclipse thing on Windows 11 and if/when we build Archi on a later version of Eclipse the issues will be solved.

**Closed by Phillipus** 2023-02-08 08:42 UTC
