### ISSUE TITLE
[issue] Visualiser does not show related elements where element is associated with a relationship

### ISSUE THREAD

**Issue by cushyno** [archimatetool/archi#177] opened 2016-12-22 12:28 UTC
Using Archimate 3 relationships to relationships, supported by Archi 4.

Element A is related to element B via a data flow, the relationship is named X.  Element C is a separate element not directly related to either A or B.  I associate C to the data flow X, this association is named Y.

![archi-relationship-relationship](https://cloud.githubusercontent.com/assets/8866837/21425573/d00cd5ce-c841-11e6-9cc2-5ca9fb38db6c.PNG)

In Visualiser:

- When viewing element C, only relationship Y is shown regardless of Depth.
- When viewing relationship Y, only element C is shown regardless of Depth.

  For each of these cases I would expect Visualiser to always show X, additionally showing A and B dependent on the Depth filter.

- When viewing relationship X, only elements A,B are shown regardless of Depth.

  For this case I would expect Visualiser to always show A, B and Y (and therefore C too).

**Comment by Phillipus** [comment] 2016-12-22 12:49
The problem is that the UI library (Zest) cannot show connections to connections, only nodes and connections from nodes to nodes. So it is not possible to do this.

**Comment by cushyno** [comment] 2016-12-22 13:22
Thank you for confirming that it is not possible.
It's useful to have a record of what can and can't be done with the libraries currently in use.

**Comment by Phillipus** [comment] 2019-01-28 14:01
Closing as no longer valid. Re-open new issue if required,

**Closed by Phillipus** 2019-01-28 14:01 UTC
