### ISSUE TITLE
Group and Grouping tab size does not contain Text

### ISSUE THREAD

**Issue by smileham** [archimatetool/archi#689] opened 2020-11-11 17:09 UTC
### Version of Archi
4.7.1

### Archi Plug-ins
N/A

### Operating System
Windows

### Expected Behaviour
"Group" and "Grouping" label fits within the tab box regardless of text length and font size

### Actual Behaviour
![Grouping Title](https://user-images.githubusercontent.com/2892935/98841758-7981f900-2440-11eb-95b0-c72111f472c9.png)

### Steps to Reproduce the Behaviour
1. Drag on Group/Grouping component
2. Enter Text in Tab name
3. Set font to size 18

**Comment by Phillipus** [comment] 2020-11-11 18:36
Duplicate of #688

**Comment by Phillipus** [comment] 2020-11-20 18:18
I'm going to re-open this issue as it seems from #693 that this might not be wanted.

**Comment by Phillipus** [comment] 2020-11-20 18:24
Following on from #693 this might not be wanted behaviour. So the choices are:

1. Revert this and go back to the old way
1. Keep this new behaviour

Things that I am not prepared to do are have at is an option, or complicated rules like "If it's a label expression then do this, or do that..." It starts to get very hard to implement.

For reference, Modelio tool implements the new behaviour.

**Comment by larspijnappel** [comment] 2020-11-20 18:39
Indeed, when using a label expression the complete label is placed in the tab itself and the  tab area is enlarged accordingly (see described example in #693). 

In Archi 4.7.1 (and below) the 1st line of the expression is visually located in the tab and the remaining lines are located below that. 

I suppose there's always a workaround feasible, but if this change would be implemented then anyone who has used label expression in existing models would need to do the following: manually change all relevant Group/Groupings from a Tabbed to Rectangle border?

**Comment by Phillipus** [comment] 2020-11-20 18:45
> I suppose there's always a workaround feasible, but if this change would be implemented then anyone who has used label expression in existing models would need to do the following: manually change all relevant Group/Groupings from a Tabbed to Rectangle border?

Yes. So we are back to choosing between:

1. Revert this and go back to the old way
1. Keep this new behaviour

As I said, it is not practical to go down the road of "Have it as an option, or if if there is a label expression then so this, or if there is a new line character do that, or if the font is bigger than the tab height then do this...." thinking.

I can understand wanting to fit the text in the tab, especially if the font is bigger, but can see that users might find this surprising.

This is the problem with a seemingly "simple" feature request.

**Comment by Phillipus** [comment] 2020-11-20 18:46
> In Archi 4.7.1 (and below) the 1st line of the expression is visually located in the tab

That's only if the font is the right size to fit in the tab. Change it to a bigger font and it looks stranger as in the screenshot above.

**Comment by Phillipus** [comment] 2020-11-20 18:52
An alternate method would be to resize the tab height to the font height and the tab width to the text width:

<img width="626" alt="Screenshot 2020-11-20 at 18 51 35" src="https://user-images.githubusercontent.com/600504/99838780-8c43ae80-2b61-11eb-9f4b-13ffb029939a.png">

**Comment by Phillipus** [comment] 2020-11-20 18:55
Rather than the current behaviour:

<img width="563" alt="Screenshot 2020-11-20 at 18 54 28" src="https://user-images.githubusercontent.com/600504/99838975-e3e21a00-2b61-11eb-937b-6c67aa56a05b.png">

**Comment by Phillipus** [comment] 2020-11-20 18:57
Damn, This is the wrong bug. This is duplicate of #688

**Comment by jbsarrodie** [comment] 2020-11-20 18:59
> So we are back to choosing between:
> 
> 1. Revert this and go back to the old way
> 2. Keep this new behaviour

In fact, IMHO, when using the default "Tab" grouping notation, the only right behavior is the following:
* If text position is top, force text alignment to left (whatever is really set) and allow **only one** line of text in the label with the tab height which adjusts to the font height. This means that long names will be truncated.
* if text position is middle or bottom, use the old method

**Comment by Phillipus** [comment] 2020-11-20 19:00
> If text position is top, force text alignment to left (whatever is really set) and allow only one line of text in the label with the tab height which adjusts to the font height. This means that long names will be truncated.

That is even harder to implement. I already spent 3 days on this! :-)

**Comment by Phillipus** [comment] 2020-11-20 19:04
OK, this has got way too complicated. I'm going to revert to the old behaviour and somebody else can implement this.

**Comment by jbsarrodie** [comment] 2020-11-20 19:05
> I'm going to revert to the old behaviour and somebody else can implement this.

Don't do this: I think this new behavior is better than the old one (though not perfect).

**Comment by Phillipus** [comment] 2020-11-20 19:05
https://github.com/archimatetool/archi/issues/689#issuecomment-731348543 might be a better option, then

**Comment by jbsarrodie** [comment] 2020-11-20 19:08
> [#689 (comment)](https://github.com/archimatetool/archi/issues/689#issuecomment-731348543) might be a better option, then

This is very close to an optimum solution. Is it possible to truncate text by setting some attribute on the label ?

**Comment by Phillipus** [comment] 2020-11-20 19:11
> Is it possible to truncate text by setting some attribute on the label ?

Not that I know of.

**Comment by Phillipus** [comment] 2020-11-20 19:13
TBH, https://github.com/archimatetool/archi/issues/689#issuecomment-731348543 is the current behaviour but just fitting in the font size which is the aim of the OP.

**Comment by jbsarrodie** [comment] 2020-11-20 19:14
> Not that I know of.

Ok, so let me look at something (I want to do some test)

**Comment by Phillipus** [comment] 2020-11-20 19:18
> Ok, so let me look at something (I want to do some test)

This is going to turn into "the never-ending story"... ;-)

**Comment by jbsarrodie** [comment] 2020-11-20 19:21
> This is going to turn into "the never-ending story"... ;-)

I don't think so.

Can you share the code for https://github.com/archimatetool/archi/issues/689#issuecomment-731348543 in a branch ?

**Comment by Phillipus** [comment] 2020-11-20 19:47
> Can you share the code for [#689 (comment)](https://github.com/archimatetool/archi/issues/689#issuecomment-731348543) in a branch ?

Yes, it's in the `group-figure` branch.

But that's it from me tonight...I just opened une bouteille de vin rouge... ;-)

**Closed** 2020-12-13 16:41 UTC
