### ISSUE TITLE
Models Tree loses focus after an object is dragged into top-level folder

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#837] opened 2022-04-28 08:11 UTC
### Version of Archi
4.9.3

### Archi Plug-ins
none

### Operating System
windows 10

### Expected Behaviour
keyboard shortcurts should work all the time

### Actual Behaviour
keyboard shortcuts stop working after a view is dragged out of a folder in Models tree

### Steps to Reproduce the Behaviour
1. create a folder under Views in Models pane
2. drag a view into this folder
3. drag it back to the root of Views folder
4. press ^S to save - model is not saved. All keyboard shortcuts stop working e.g. pressing ^Z doesn't undo the move, etc.

**Comment by Phillipus** [comment] 2022-04-28 08:17
Can't reproduce this one.

Are the menu items greyed out?

Ensure that the model concerned has the focus in the Models Tree when using these commands.

**Comment by Phillipus** [comment] 2022-04-28 08:33
Seems that dragging a tree node to the top folder deselects it. Used to work OK in Archi 4.7.1, but not 4.8 and later. Will investigate.

**Comment by Phillipus** [comment] 2022-04-28 09:34
I've changed the title of this issue to reflect the true cause.

I've investigated the code and the Tree loses the current selection and focus when objects are dragged into a top-level folder. I can't see where it is happening, so this might take some time to solve (if it can be solved).

**Comment by Phillipus** [comment] 2022-04-28 11:55
This is now fixed and will be in the next version.

**Closed by Phillipus** 2022-04-28 11:55 UTC
