### ISSUE TITLE
png export of views adds a white background rather than leaving the background transparent

### ISSUE THREAD

**Issue by The-WetFish** [archimatetool/archi#1083] opened 2024-10-07 09:50 UTC
### Archi Version

5.4.2

### Operating System

MacOS 15.1 Beta (24B5055e)

### Description

When exporting to png it automatically puts in a white background (rather than leaving the background transparent). That means white text suddenly becomes impossible to read.

### Steps to reproduce

1. Create a view to test with
2. add an element
3. set the element to white text and 0 fill opacity
4. choose to export, view as image
5. choose png (therefore supporting transparency)
6. save file to wherever you want
7. open file, notice a white background forced in which means you can no longer see the text

**Comment by Phillipus** [comment] 2024-10-07 10:47
I'm going to close this one as a duplicate of https://github.com/archimatetool/archi/issues/731 because, for technical reasons mentioned there, it's currently not possible to set the background of a view to transparent. If a solution comes I'll certainly try to implement it.

**Closed by Phillipus** 2024-10-07 10:47 UTC
