### ISSUE TITLE
Import a model into another model

### ISSUE THREAD

**Issue by chdessus** [archimatetool/archi#909] opened 2023-02-09 15:11 UTC
### Version of Archi
 4.9.3
Due to client decision, I cannot move to 4.10.

### Archi Plug-ins
 
CoARch - Excel - Scripting - LightBox

### Operating System

WINDOWS10

### Expected Behaviour

I would like to import a model into another model  : FILE/IMPORT/ANOTHER MODEL INTO SELECTED MODEL
### Actual Behaviour

I get an error. See PDF file attached.

### Steps to Reproduce the Behaviour
1. FILE/IMPORT/ANOTHER MODEL INTO SELECTED MODEL
2. then select an archimate file + Enter.
3.

**Comment by chdessus** [comment] 2023-02-09 15:12
[erreur Archi Import model.pptx](https://github.com/archimatetool/archi/files/10698578/erreur.Archi.Import.model.pptx)

**Comment by chdessus** [comment] 2023-02-09 15:14
[erreur.Archi.Import.model.pdf](https://github.com/archimatetool/archi/files/10698600/erreur.Archi.Import.model.pdf)

**Comment by Phillipus** [comment] 2023-02-09 15:24
Hi Christine, I'd need to inspect the imported and target models in order to diagnose this one. Do you have models that you could email to me?

Phil

**Comment by chdessus** [comment] 2023-02-09 17:16
Hello,

Here attached the models. I have anonymized it. I want to import
DIA-ANONYMUS into the model PD-ANONYMUS.
Before that I have imported another model into PD-ANONYMUS without any
difficulty.
For this project, I do have 8-10 models to import into PD-ANONYMUS.

What I did :
- Open PD-ANONYMUS
- File/import/Another model into selected model
- Then I select DIA-ANONYMUS and I get the error.

I still have the error with the anonymised models.

Thank you and regards.

Christine Dessus
T : +33 6 31 09 73 54
www.competensis.com

**Comment by Phillipus** [comment] 2023-02-09 17:19
Hi Christine,

because you are posting from email, attachments are not included in the message.

Please email the models to info@archimatetool.com

**Comment by chdessus** [comment] 2023-02-09 17:22
Sorry, The attached files.
[IMPORT MODELES ARCHI.zip](https://github.com/archimatetool/archi/files/10699859/IMPORT.MODELES.ARCHI.zip)

**Comment by Phillipus** [comment] 2023-02-09 17:26
Thanks Christine. I have the models now and will investigate. I deleted the models from here to keep things anonymous.

**Comment by chdessus** [comment] 2023-02-09 17:29
Thank you.

Le jeu. 9 févr. 2023 à 18:26, Phil Beauvoir ***@***.***> a
écrit :

**Comment by Phillipus** [comment] 2023-02-09 18:21
Hi Christine,

I've found the cause of the bug. It can happen when there are relationships connected to other relationships and they don't yet have a parent folder. I can fix this for Archi 5.0.0 next beta tomorrow.

Regards,

Phil

**Comment by chdessus** [comment] 2023-02-09 18:42
Great.
Thank You.
I appreciate your support.
Christine.


Le jeu. 9 févr. 2023 à 19:22, Phil Beauvoir ***@***.***> a
écrit :

**Comment by Phillipus** [comment] 2023-02-13 09:35
Close this one now as it should be fixed in latest Archi 5 beta. Thanks for reporting it!

**Closed by Phillipus** 2023-02-13 09:35 UTC
