### ISSUE TITLE
Issue with palette selection tools not staying selected persists in Archi 5.4.0/5.4.1

### ISSUE THREAD

**Issue by IronSolder** [archimatetool/archi#1076] opened 2024-09-12 13:32 UTC
### Archi Version

5.4.0/5.4.1

### Operating System

Debian 12

### Archi Plug-ins

None

### Description

Still have the issue with palette selection tools not staying selected in Archi 5.4.0/5.4.1 when selecting relations.
Switched back to Archi 5.3 without this issue.

### Steps to reproduce

1. Select relation palette tool e.g. Magic Connector.
2. Select object 1 for connection -> ok
3. When mouse pointer is moved over another object, it only can be selected as object 2 for connection BEFORE object information is displayed. As soon as the object information is displayed, the selection of the relation palette tool is lost.

**Comment by Phillipus** [comment] 2024-09-12 13:37
Can you explain in more detail what this means:

> When mouse pointer is moved over another object, it only can be selected as object 2 for connection BEFORE object information is displayed. As soon as the object information is displayed, the selection of the relation palette tool is lost.

Or perhaps a screen capture to show this?

**Comment by Phillipus** [comment] 2024-09-12 14:12
It's because the tooltip is grabbing the focus. This is a regression from here - https://github.com/eclipse/gef-classic/commit/843e56c0df42aec34a487b97483a0b6c866fff95

I'll fix it. In the meantime either disable tooltips in preferences or create the connection before the tooltip shows.

**Comment by Phillipus** [comment] 2024-09-12 14:34
I have a fix for the next version. I'll wait until next week to release the fix in case something else shows up.

**Comment by IronSolder** [comment] 2024-09-12 14:58
Unfortunately I wasn't fast enough to record a screen video. But in the meantime the problem could be understood without it. :-)

Disabling the tooltip is a much more pleasant option than frantically selecting the target object before the tooltip appears... .

I also confirm the behavior that the tooltips are not displayed in the correct position, but for me this is only a small blemish and does not particularly disrupt work.

Thanks for the quick response!!

**Comment by Phillipus** [comment] 2024-09-19 09:29
Fixed in Archi 5.4.2.

**Closed by Phillipus** 2024-09-19 09:29 UTC
