### ISSUE TITLE
Note or new element thought bubble to expose content of connected element property 

### ISSUE THREAD

**Issue by peterprib** [archimatetool/archi#409] opened 2018-11-10 22:34 UTC
This would allow an important aspect of an element to be placed on diagram yet held against the real owner of the comment.  Some times one wants to expose and highlight information on certain aspects of particular elements on a diagram.

**Comment by ruben-s** [comment] 2019-01-16 13:11
Hi,

an upvote.
Note this is functionality that exists in EA Sparx, and indeed I find it usefull to show information on a diagram that really is owned by an element on the diagram.

br,
 Ruben

**Comment by ruben-s** [comment] 2019-01-16 13:14
is #418 a duplicate of this?

**Comment by willipwolf** [comment] 2019-03-07 14:13
Yes I do think that this is a duplicate with #418 but #418 perhaps states the feature request more succinctly.  That is, to optionally display the element:documentation content in a view.  I would use this a lot !

**Comment by jbsarrodie** [comment] 2019-03-07 20:55
Hi, You might have a look at [Herve's specialization plugin](https://github.com/archi-contribs/specialization-plugin) which allows you to replace label of an object (by default equals to object's name) using either free text of some macro providing access to documentation field or properties.

**Comment by willipwolf** [comment] 2019-03-07 22:58
Thank you, I'll look into it.

**Closed** 2021-12-18 18:30 UTC

**Comment by jbsarrodie** [comment] 2021-12-18 19:32
Just in case someone find this issue after some lookup: this is now supported through [label expressions](https://github.com/archimatetool/archi/wiki/Label-Expressions) (a note can reference properties of its parent object or of the object to which it is connected).

**Comment by Phillipus** [comment] 2021-12-18 19:33
> Just in case someone find this issue after some lookup: this is now supported through [label expressions](https://github.com/archimatetool/archi/wiki/Label-Expressions) (a note can reference properties of its parent object or of the object to which it is connected).

Thanks, JB. I should have added that on the closing comment.
