### ISSUE TITLE
[Feature Request] toggle on element properties to automatically display documentation 

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#418] opened 2018-12-05 10:11 UTC
I find myself having to do this manually for presentations and documentation and will save a lot of time in modeling.

What would help is a toggle on element properties to automatically display documentation  on diagram as Note in or linked to element.

**Comment by ruben-s** [comment] 2019-01-16 13:15
duplicate of #409 ?

**Comment by willipwolf** [comment] 2019-03-07 14:14
Yes I do think that this is a duplicate with #409 but perhaps this one states the feature request more succinctly.  That is, to optionally display the element:documentation content in a view.  I would use this a lot !

**Comment by mwherman2000** [comment] 2019-03-07 14:38
https://github.com/archimatetool/archi/issues/409 is specific about this capability being rendered as a "thought bubble".

I (think I) have a related requirement: the ability to place "large numbered bullets" in the *model* so that when I create viewpoints of the model, the same "large numbered bullets" appear in the newly created viewpoints.  Below is an example.  Currently I'm adding the bullets in PowerPoint on top of an image exported from Archi.  I now have a[ dozen different viewpoints](https://github.com/mwherman2000/indy-arm/blob/master/README.md#indy-arm-viewpoints-) and the task of maintaining the bullets on a dozen different PowerPoint slides have become untenable. 

I'm more than willing to be a Tester for this feature.

![image](https://user-images.githubusercontent.com/6101736/53964033-b9a9a980-40ab-11e9-879e-02e6a0815898.png)

**Comment by jbsarrodie** [comment] 2019-03-07 20:55
Hi, You might have a look at [Herve's specialization plugin](https://github.com/archi-contribs/specialization-plugin) which allows you to replace label of an object (by default equals to object's name) using either free text of some macro providing access to documentation field or properties.

**Comment by willipwolf** [comment] 2019-03-07 22:58
Thanks that sounds like what I need.

**Comment by theunsfvo** [comment] 2019-06-12 09:56
I think my request is different, was about to open another request when I saw this is still open.

What I would like is to have the text of an element Documentation box to show INSIDE the element body OR right next to it in note/bubble form...

![image](https://user-images.githubusercontent.com/5095077/59341950-1f3fae80-8d09-11e9-92c1-ebf98326099e.png)

**Comment by jbsarrodie** [comment] 2019-06-20 12:27
> What I would like is to have the text of an element Documentation box to show INSIDE the element body OR right next to it in note/bubble form...

For the INSIDE part, you can do it with Herve's specialization plugin by forcing the label to show the name, a newline and the content of the documentation field.

For the other option (next to), that's something I also would like but never had time to implement. I might work on it this summer ;-)

**Comment by theunsfvo** [comment] 2019-06-20 12:32
Where can we find the plug-in and is it easy to install/use?

Thanks,
Theuns

**Comment by jbsarrodie** [comment] 2019-06-20 12:43
You can find it here: https://github.com/archi-contribs/specialization-plugin

I'd suggest to use the version 1.x (version 2 is still experimental and I haven't tested it myself). You just have to download it and save it inside the plugin folder of you Archi setup.

Then restart Archi and you should now see a new subtab named "Replace label" inside the Properties view in which you can customize the label. The formala you need should be `${name}\n${documentation}`

**Comment by theunsfvo** [comment] 2019-06-20 12:48
Thank your, I will try it out.

Thanks,
Theuns

**Comment by jbsarrodie** [comment] 2020-03-20 08:22
Closing as this is implemented as part of #576 which will be included in Archi 4.7

**Closed by jbsarrodie** 2020-03-20 08:22 UTC
