### ISSUE TITLE
Language Pack Translation Issues

### ISSUE THREAD

**Issue by rojoweko** [archimatetool/archi#683] opened 2020-10-14 23:59 UTC
### Version of Archi
4.7.1

### Operating System
Windows 10

### Expected Behaviour
The complete GUI shoud be translatable

### Actual Behaviour
For some parts of the GUI no translation can be added

### Steps to Reproduce the Behaviour
1. Create and import an Archi language package plugin template, translate the GUI, export the language plugins and combine them with the respective babel-plugins according to https://github.com/archimatetool/archi/wiki/Translating-Archi 
2. Install the language plugins into the application directory of your Archi installation
3. Launch Archi and check the menus of the GUI

At least the following parts of the GUI appear still in English:
- Menu entry "Edit -> Rename", when an element in the View windows is selected.
- Menu actions under "View -> Position" ("Align left", etc.) and the tooltips of the respective buttons.
- Label of the Outline window.
- Some menu actions under "File -> Import" ("Model From Open Exchange File..." and "Another Model Into Selected Model..." as well as the Import Model dialogue window).
- Menu action "Model To Open Exchange File..." as well as the Export Model dialogue window.
- Menu entry "Tools -> Properties Manager".
- Dropdown menu entries "PDF Image" and "SVG Image" in the Image Export dialogue box.

Searching with Eclipse through the translation plugin templates did not bring up these properties.

According to the translation manual referenced above I used the most recent babel language plugin for Eclipse "Oxygen" (is this still correct?).

Thanks in advance for looking into this! ;-)

**Comment by Phillipus** [comment] 2020-10-15 10:15
> Menu entry "Edit -> Rename", when an element in the View windows is selected.

That was internal. I've now externalised it.

> Menu actions under "View -> Position" ("Align left", etc.) and the tooltips of the respective buttons.

These are internal Eclipse GEF messages. Hwoever, I'v found a way to externalise them.

> Label of the Outline window.

This is internal to Eclipse. I don't know where the string is for that.

> Some menu actions under "File -> Import" ("Model From Open Exchange File..." and "Another Model Into Selected Model..."

I've now externalised these ones.

> as well as the Import Model dialogue window).

These are already externalised in `com.archimatetool.modelimporter.messages.properties`

Menu action "Model To Open Exchange File..."

I've now externalised this one.

> as well as the Export Model dialogue window.

These are already externalised in `org.opengroup.archimate.xmlexchange.wizard.messages.properties`

> Menu entry "Tools -> Properties Manager".

I've now externalised this one.

> Dropdown menu entries "PDF Image" and "SVG Image" in the Image Export dialogue box.

I've now externalised these ones.

> According to the translation manual referenced above I used the most recent babel language plugin for Eclipse "Oxygen" (is this still correct?).

Oxygen is very old. We are using Eclipse 4.15 now. I don't know if there is a newer one.

**Comment by Phillipus** [comment] 2020-10-15 10:21
For reference:

https://github.com/archimatetool/archi/commit/49631ec72c38ec15e193d5f308a0b23b78c9f985

**Comment by Phillipus** [comment] 2020-10-15 10:40
BTW - the [wiki ](https://github.com/archimatetool/archi/wiki/Translating-Archi)is probably out of date and incorrect by now. Anyone is free to update it if necessary. For my part, I can only externalise the strings where possible,

**Comment by rojoweko** [comment] 2020-10-15 14:17
Thanks for the quick response! I will update my local repo and try again! ;-)

Here's another one I forgot before (sorry):

- Name of the "Label"-section in the Properties window.

**Comment by rojoweko** [comment] 2020-10-15 14:23
Regarding Babel: There are only language packages for "even" minor versions of Eclipse available (e.g. 4.12, 4.14, 4.16). I tried them up to 4.14, but did not notice any improvements regarding the coverage of translated GUI items. 4.14 even caused Archi to start much slower than usual.

**Comment by Phillipus** [comment] 2020-10-15 15:19
> Name of the "Label"-section in the Properties window.

OK, I added that one and re-pushed the commit.

**Comment by rojoweko** [comment] 2020-10-15 15:47
Do I need to check out a different branch to test the changes? I tried to pull an update via "Team -> Pull" from the master but I did not find the changes in e.g. com.archimatetool.editor.

**Comment by Phillipus** [comment] 2020-10-15 15:53
It's in a different branch - `externalise-strings`. I'll keep them in a branch in case there are more changes.

**Comment by rojoweko** [comment] 2020-10-17 17:27
OK, that seemed to work! Thank you! ;-)
The only non-translatable strings left I have noticed so far are the following:
- Tooltips of the alignment/matching buttons in the toolbar ("Align left", etc., "Match Width...", etc.)
- The names of ArchiMate viewpoints in the menu actions under "View -> Viewpoint"
- Menu entries "Edit -> Undo" and "Edit -> Redo" and the respective tooltips for buttons in the toolbar
- Menu entries "View -> Zoom In/Out"

Could these be externalised by you as well or are they part of the Exclipse framework?

Please also update the create-nls.xml Ant script in order to set up the localized plugins for the modelimporter and xmlexchange.

Is it possible to show the translated cheat sheets in the cheat sheet list instead of the English ones?

Is there a way of enabling the language pack on a non localized operating system?

Thanks in advance! ;-)

**Comment by Phillipus** [comment] 2020-10-17 18:50
The first set of changes from before have been merged into the `master` branch.

The following changes are now in the `externalise-strings` branch:

- Tooltips of the alignment/matching buttons in the toolbar ("Align left", etc., "Match Width...", etc.)
- Menu entries "View -> Zoom In/Out"
- Updated the create-nls.xml Ant script

These are not updated:

> The names of ArchiMate viewpoints in the menu actions under "View -> Viewpoint"

This is not externalisable in the usual way. The file is `com.archimatetool.model\model\viewpoints.xml`. You'd have to translate the `name` parts and distribute the new file.

> Menu entries "Edit -> Undo" and "Edit -> Redo" and the respective tooltips for buttons in the toolbar

These are internal to Eclipse's `GEF` framework.

> Is it possible to show the translated cheat sheets in the cheat sheet list instead of the English ones?

There are two xml files in `com.archimatetool.help\cheatsheets` - I don't know how to externalise these ones.

> Is there a way of enabling the language pack on a non localized operating system?

I don't know. I think you have to set the language somehow in the startup - see https://www.eclipse.org/articles/Article-Speak-The-Local-Language/article.html

**Comment by jbsarrodie** [comment] 2020-10-17 18:54
> This is not externalisable in the usual way. The file is `com.archimatetool.model\model\viewpoints.xml`. You'd have to translate the `name` parts and distribute the new file.

Do you know if it is possible to add multiple `name` tags with different value for `xml:lang` attribute ? If yes this would mean it is possible to create a single `viewpoints.xml` file containing multiple translations.

**Comment by Phillipus** [comment] 2020-10-17 19:18
> Do you know if it is possible to add multiple name tags with different value for xml:lang attribute ? If yes this would mean it is possible to create a single viewpoints.xml file containing multiple translations.

It's not possible right now. It's something I wrote and didn't figure out a way to read in an XML file and take that into account. It needs more work to do that...one day. ;-)

**Comment by Phillipus** [comment] 2020-10-18 10:48
@rojoweko I've figured out a way to support language packs for the `viewpoints.xml` file. I've changed the `create-nls.xml` Ant script to copy this file to the exported `com.archimatetool.model` project. All you need to do is edit the `name` in the xml file. Don't worry about the `xml:lang="en"` part, that is ignored.

Basically the same process as editing a hints file in the help project.

> Is there a way of enabling the language pack on a non localized operating system?

In the `Archi.ini` file add two lines after `openFile` line:

```
-nl
fr
```

(fr or ru or de language code)

**Comment by rojoweko** [comment] 2020-10-18 14:04
Great! ;-) The tooltips and the menu entries seem to work (the tooltips only when the view window has the focus, but this is probably ok).
I also tried the viewpoint.xml by modifying a copy of it in the localized plugin, but this does not seem to work yet. Since I do not really know Ant scripting I tried the following subdirectories in the localized plugin, but without success:
- model
- nl
- nl/model
- nl/de
- nl/de/model

Did I get something wrong?

Thanks for the hint with the Archi.ini file! I will check that out! ;-)

**Comment by Phillipus** [comment] 2020-10-18 14:40
The new version of the Ant script will copy `viewpoints.xml` to the target project. You need to get the latest code from the `externalise-strings` branch.

**Comment by Phillipus** [comment] 2020-10-18 15:21
There was an error in the Ant script for `org.opengroup.archimate.xmlexchange`. Fixed in latest commit to the `externalise-strings` branch.

**Comment by rojoweko** [comment] 2020-10-18 17:45
Looking good now! ;-)

Do you have any plans to offer the integration of third party language packages into the mainline distribution of Archi?

**Comment by Phillipus** [comment] 2020-10-18 17:47
> Do you have any plans to offer the integration of third party language packages into the mainline distribution of Archi?

No. I can't be responsible for their distribution and upkeep.

**Comment by rojoweko** [comment] 2020-10-18 17:53
Do you support a different way of distributing language packages?

**Comment by Phillipus** [comment] 2020-10-18 17:56
> Do you support a different way of distributing language packages?

It's the responsibility of the language pack owner to maintain and distribute them as downloads. We can advertise them on the Archi website - https://www.archimatetool.com/resources/

**Comment by rojoweko** [comment] 2020-10-18 17:58
OK - Thanks for the info! ;-)

**Comment by rojoweko** [comment] 2020-10-19 16:05
Shall we leave this open as a permanent issue for dealing with similar requests in the future?

**Comment by rojoweko** [comment] 2020-10-19 16:08
Otherwise I would close it and reopen it when necessary. ;-)

**Comment by Phillipus** [comment] 2020-10-19 16:33
Keep it open. I renamed it to suit the purpose better.

**Comment by rojoweko** [comment] 2020-10-19 16:36
OK, thanks.

Do you need any further information from me for now before merging the changes in the master branch?

**Comment by Phillipus** [comment] 2020-10-19 16:49
> Do you need any further information from me for now before merging the changes in the master branch?

No, thanks. I'll keep the `externalise-string`s branch open for a bit longer just in case. Cheers.

**Comment by rojoweko** [comment] 2020-10-24 15:26
Hi, you were right to keep the branch open a little bit longer! ;-) I found the following other non-translatable components:

- Tooltip of the Select Tool button ("Select")
- Welcome screen
- Context menu and settings dialogue of the palette cannot be translated

**Comment by Phillipus** [comment] 2020-10-24 16:13
- Tooltip of the Select Tool button ("Select")
- Context menu and settings dialogue of the palette

These are internal to GEF so must come from the GEF language pack

- "Detach" in the context menu of the windows tabs

This is internal to Eclipse so must come from their language pack.

- Welcome screen

I updated the `create-nls.xml` Ant script to copy across the Intro files to the `com.archimatetool.editor` nl sub-directory.

**Comment by rojoweko** [comment] 2020-10-24 17:02
OK. I tried the updated create-nls.xml Ant script, but somehow it did not quite do the trick yet. The Welcome screen still does not use the translated into.html (that I actually already placed manually in the same directory before trying the new script).

**Comment by Phillipus** [comment] 2020-10-24 17:13
The updated Ant file should have this in it:

```java
<copy todir="${editor.loc.tgt}/nl/${lang_code}">
    <fileset dir="${editor.loc.src}">
        <include name="intro/" />
    </fileset>
</copy>
```

The file should be exported as:

`com.archimatetool.editor.en\nl\en\intro\intro.html`

I tested it and it's working for me.

**Comment by rojoweko** [comment] 2020-10-24 17:37
Sorry, my mistake! I forgot to put the correct language and version setting in the create-nls-xml Ant script! Now it works! Thanks! ;-)

**Comment by rojoweko** [comment] 2020-10-27 12:07
Can a language package be distributed as a .archiplugin file? If yes, how do I create one? Is there a major difference between a regular ZIP file and the archiplugin file format? Putting the files in the dropins folder instead of the plugins folder manually seems to work. ;-)

**Comment by Phillipus** [comment] 2020-10-27 14:19
@rojoweko Quick answer - yes.

Longer answer:

I've pushed another change to the `externalise-strings` branch and added two new properties to the Ant script:

```
<property name="bundle_name"                value="Your Language Pack Name"/>
<property name="bundle_vendor"              value="Your Name"/>
```

Edit these values so that this information will be visible when users manage their plug-ins from within Archi's plug-in management dialog.

So, once you have imported the nls template projects and re-exported them you will end up with these plug-in folders like this:

```
com.archimatetool.canvas.en_4.0.0.202010271357
com.archimatetool.csv.en_4.0.0.202010271357
com.archimatetool.editor.en_4.0.0.202010271357
etc...
```

So you need to add one file to this list, a small file called `archi-plugin`. It can be empty, it's just a marker file.

Then zip all of the plugin folders and the `archi-plugin` file to a zip file and change the extension to ".archiplugin".

That's it.

Attached is a simple example. Rename the extension to ".archiplugin" or examine the contents to see what I mean.

[example-plugins.zip](https://github.com/archimatetool/archi/files/5445905/example-plugins.zip)

**Comment by rojoweko** [comment] 2020-10-27 15:04
Awesome! Thanks a lot! ;-) I will check that out!

**Comment by rojoweko** [comment] 2020-10-28 16:21
The installation seems to work great! ;-) (Although I do not know if it would benecessary to deploy the Babel features in the "features" folder... I deployed them together with the plugin files in the dropins folder for now - or is there a way to deploy in the features folder with an .archiplugin file?)

The uninstalling function in Archi on the other hand seems to fail on one Babel plugin and so there will be some Babel files left over which therefore have to be deleted manually out of the dropins folder after the uninstall process.

**Comment by Phillipus** [comment] 2020-10-28 16:25
> The installation seems to work great! ;-) (Although I do not know if it would benecessary to deploy the Babel features in the "features" folder... I deployed them together with the plugin files in the dropins folder for now - or is there a way to deploy in the features folder with an .archiplugin file?)
> 
> The uninstalling function in Archi on the other hand seems to fail on one Babel plugin and so there will be some Babel files left over which therefore have to be deleted manually out of the dropins folder after the uninstall process.

Sorry, I can't help with this aspect. I think Archi will ignore any "features" since they don't actually contain any code or translations, I might be wrong, though. Suggest experimenting with this.

**Comment by jbsarrodie** [comment] 2020-10-29 20:31
> I've figured out a way to support language packs for the `viewpoints.xml` file.

Does this mean that I can override `viewpoints.xml` file by creating a dummy translation plugin ? If yes, this would offer me a good way to distribute a custom set of viewpoints.

**Comment by Phillipus** [comment] 2020-10-29 20:35
@jbsarrodie It means that the `viewpoints.xml` file is externalised like any other file (for example, the help and hint files). So I think your idea should work. I created some dummy `en` language packs for testing and this does work.

**Comment by jbsarrodie** [comment] 2021-03-16 15:55
>Edit; only in the next version of Archi, though.

Was this included in 4.8 ?

**Comment by Phillipus** [comment] 2021-03-16 16:01
> Was this included in 4.8 ?

Yep.

**Comment by jbsarrodie** [comment] 2021-03-16 16:46
> Yep.

Ok, thank you. I have a strange behavior: I was able (some time ago) to "translate" `viewpoints.xml` when launching Archi from withing Eclipse, but this doesn't work with Archi 4.8.x outside of Eclipse. I'll double check my translation plugin configuration and let you know.

**Comment by Phillipus** [comment] 2021-03-16 16:52
The key to loading the translated `viewpoints.xml` lies in  the change made to `ViewPointManager.java` 

https://github.com/archimatetool/archi/blob/f2d01d795bd3eb47010736838add9d7116d5e0ae/com.archimatetool.model/src/com/archimatetool/model/viewpoints/ViewpointManager.java#L167

This means it loads the `viewpoints.xml` file in the language pack.

BTW ignore `xml:lang="en"` in the file, it doesn't do anything.

**Comment by jbsarrodie** [comment] 2021-03-17 10:27
I got it to work: I first set my language code to `custom_en` and it was working from within Eclipse but not in a standalone Archi. I changed this to a two letter code and it now works in both environments. Problem solved.

**Comment by jbsarrodie** [comment] 2021-03-17 10:27
I guess we can close this issue now

**Closed** 2021-03-17 10:29 UTC

**Comment by Phillipus** [comment] 2021-10-14 08:36
@rojoweko Thanks for reporting these. I've created a new branch in GH, `strings`, and externalised these ones. They'll be in the next maintenance release.

**Comment by jbsarrodie** [comment] 2021-10-21 15:43
> Do you happen to have an idea what could have caused the delay during the start-up?

I had a similar issue in the past that was linked to the theme used. Can you check which theme you use and if differents pick the same as the one you have when launched through eclipse?

**Comment by rojoweko** [comment] 2021-10-30 19:42
I just tried to translate the Preview HTML Report as well by manually copying the "templates" folder from the "com.archimatetool.reports" package into the "nl/de/" folder in the "com.archimatetool.reports.de" package and by editing the content of the copied "en.css" (which I renamed to "de.css") in the "nl/de/templates/html/css/i18n/" folder, but that does not seem to have any effect on the HTML report feature. Are there some other steps I need to take here in order to enable the report localization or does this require changes in the application code to work? If the latter, please let me know, if this could be done with a reasonable effort. Thanks in advance! ;-)

**Comment by jbsarrodie** [comment] 2021-10-31 19:33
For a new CSS language translation file to be used, you have to:
- Create a new CSS file based on ` en.css`  to define all translations based on a new language. Make sure to update the begining of all lines to match the new language code (by default that's `:lang(en)` for english)
- Edit `i18n.css` to import this new language file
- Add some javascript inside `model.js` and `frame.js` to dynamically change the `lang` attribute of the page `html` tag, or force it by editing the two page templates: `frame.stg` on line 138, and `modelreport.stg` on line 33)

**Comment by rojoweko** [comment] 2021-11-01 09:27
Thanks for the quick response! ;-)

As suggested I did the following:

- I created a new file "de.css" in the folder "nl/de/templates/html/css/i18n/" in the package "com.archimatetool.reports.de" based on the original "en.css" and replaced ":lang(en)" by ":lang(de)" in each respective line.
- I copied the "i18n.css" file into the folder "nl/de/templates/html/css/" in the package "com.archimatetool.reports.de" and altered its content to "@import url('i18n/de.css');".
- I chose the option to force the "de" setting of the "lang" attributes of the "html" tag within the copies of the two page templates in the folder "nl/de/templates/st/" rather than modifying the javascript code, because I am not really firm with that.

Unfortunately that did not work out yet. I also tried the same in a "templates/" folder (without leading "nl/de/") with an respective adaption of the "build.properties" file in the "com.archimatetool.reports.de" package - with the same result. Did I understand something wrong?

**Comment by jbsarrodie** [comment] 2021-11-01 19:29
My explanation was for someone who customize the template as it is in Archi (I do that myself), but I never tried in a language plugin, and to my knowledge the HTML report template is not externalize, so this should be the root cause.

**Comment by rojoweko** [comment] 2021-11-26 11:45
Hi, I found out that I could localize the "Customizable Report" entry in the drop down box in the 2. page of the Jasper Reports creation wizard by simply renaming the "Customizable Report" folder in the localization package, but I noticed that there might be a hard coded reference to a file in that folder ("Customizable Report/main.jrxml") in com.archimatetool.jasperreports.commandline.JasperReportsProvider.java line 89. Does this string need to be externalized in order to work with a localized name of the folder "Customizable Report"?

**Comment by Phillipus** [comment] 2021-11-26 12:39
Yes, it makes sense to externalise that folder. Will be in next version.

**Comment by rojoweko** [comment] 2021-11-26 12:42
Awesome! Thanks! ;-)

**Comment by rojoweko** [comment] 2021-11-26 14:58
Another quick question (somewhat off-topic, but I figured it doesn't qualify for its own issue): Is there a default way for a language pack to integrate some "About content (legal stuff, etc.)" in Archi's About dialog?

**Comment by Phillipus** [comment] 2021-11-26 15:21
> Another quick question (somewhat off-topic, but I figured it doesn't qualify for its own issue): Is there a default way for a language pack to integrate some "About content (legal stuff, etc.)" in Archi's About dialog?

Not really. The "About" dialog loads the "LICENSE.txt" file in the editor plug-in.

**Comment by rojoweko** [comment] 2021-12-03 10:33
Thanks for externalizing the "Customizable Report" string! ;-) But unfortunately it seems to be in a not yet localized package ("com.archimatetool.jasperreports.commandline"). Please consider adding this to the "create-nls.xml" Ant script.

**Comment by Phillipus** [comment] 2021-12-03 10:36
> Thanks for externalizing the "Customizable Report" string! ;-) But unfortunately it seems to be in a not yet localized package ("com.archimatetool.jasperreports.commandline"). Please consider adding this to the "create-nls.xml" Ant script.

OK. You can also edit the create-nls.xml file and add it to your copy.

**Comment by rojoweko** [comment] 2021-12-03 11:49
OK, I will do that. ;-)

**Comment by Phillipus** [comment] 2021-12-03 11:50
There are other *.commandline projects that need to be added as well. I'll push a fix later.

**Comment by Phillipus** [comment] 2021-12-03 14:20
Pushed to "strings" branch. Will merge to "master" if everything is OK.
