### ISSUE TITLE
Win10 Archi 4.7 EA3 - no gradient is shown in diagrams

### ISSUE THREAD

**Issue by martindausb** [archimatetool/archi#604] opened 2020-04-02 11:28 UTC
[Archi.log](https://github.com/archimatetool/archi/files/4420673/Archi.log)

### Version of Archi, Operating System
Windows 10, 1909

### Expected Behaviour
The diagram elements should show a gradient color, when set in Preferences | Diagram | Appearance.
It doesn't work regardless of the set Default Gradient (Top, Left, Right, Bottom).

### Actual Behaviour
The diagram elements keep the solid Color, even after restarting the app.

### Steps to Reproduce the Behaviour
1. Menu | Edit | Preferences
2. Diagram | Appearance | Default Gradient: Chosen anything except "None"
3. Apply | Apply and Close

**Comment by Phillipus** [comment] 2020-04-02 11:31
The default gradient preference determines what gradient to use for _newly created_ objects. You can change each object's gradient setting on the Properties Appearance tab.

**Comment by Phillipus** [comment] 2020-04-02 11:50
@martindausb BTW - I see in your attached Archi.log a conflict for the Ctrl++ key binding:

```
!MESSAGE A conflict occurred for CTRL++:
Binding(CTRL++,
	ParameterizedCommand(Command(org.eclipse.gef.zoom_in,Zoom In,
		Zoom In,
		Category(org.eclipse.gef.category.view,View,View,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6435fa1c,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

```

This should not normally happen. Do you have any Archi plug-ins installed or anything different that might cause this?

**Comment by martindausb** [comment] 2020-04-02 14:13
Hi  Philip,

Thanks for the quick reply and the explanation!
So, sorry for wasting your time.

And yes, I have the Archi Model Repository plug-in installed.
Version 0.5.4.202002281020.

Best regards
Martin

On April 2, 2020 1:31:48 PM GMT+02:00, Phil Beauvoir <notifications@github.com> wrote:
>The default gradient preference determines what gradient to use for
>_newly created_ objects. You can change each object's gradient setting
>on the Properties Appearance tab.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/archimatetool/archi/issues/604#issuecomment-607789611

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by Phillipus** [comment] 2020-04-02 14:16
That's OK.

I fixed the cause of the error message in your log file:

```
!MESSAGE A conflict occurred for CTRL++:
Binding(CTRL++,
	ParameterizedCommand(Command(org.eclipse.gef.zoom_in,Zoom In,
		Zoom In,
		Category(org.eclipse.gef.category.view,View,View,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3aefae67,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
```

Only German locales will cause that. Archi 4.7 will fix this.

**Comment by Phillipus** [comment] 2020-04-02 14:19
Close this one.

**Closed by Phillipus** 2020-04-02 14:19 UTC

**Comment by martindausb** [comment] 2020-04-02 15:01
Hi Phil,

of course. Thanks again!

Best regards
Martin


On April 2, 2020 4:19:18 PM GMT+02:00, Phil Beauvoir <notifications@github.com> wrote:
>Close this one.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/archimatetool/archi/issues/604#issuecomment-607874891

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
