### ISSUE TITLE
unclear errormessage importing AMEFF

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [archimatetool/archi#841] opened 2022-05-12 20:41 UTC
### bug reports 
There is no recent error log

### Version of Archi
4.9.3

### Archi Plug-ins
CoArchi

### Operating System
Windows 11

### Expected Behaviour
AMEFF - file created by Sparx Enterprise Architect  van be imported in Archi

### Actual Behaviour
![image](https://user-images.githubusercontent.com/20146034/168161893-62a4d280-edfb-4214-abf6-06bc419b7182.png)

### Steps to Reproduce the Behaviour
I have isolated the problem to a 2 kb AMEFF file. Optically it looks ok in the indicated row and column. It can also be re-imported in Sparx. 

This is the file:
[BUS-fout.txt](https://github.com/archimatetool/archi/files/8682427/BUS-fout.txt)

**Comment by Phillipus** [comment] 2022-05-12 20:50
The error message is an XML validation error message. It means that the XML file is incorrect and can't be made any clearer. If Sparx can import that then it shows that their implementation is wrong.

I'll close this one, perhaps you can report it to Sparx?

**Closed by Phillipus** 2022-05-12 20:50 UTC

**Comment by jbsarrodie** [comment] 2022-05-12 21:05
Maybe an important note: Sparx is not a certified ArchiMate tool and has never been. For a long time (and maybe even now) its implemention of ArchiMate has been know to be non compliant. So I don't expect this tool to be able to generate a valid AMEFF file.

**Comment by Phillipus** [comment] 2022-05-12 21:28
The problem is with this line:

`<node identifier="EAID_DN000000_3D16_4af7_B8F8_B3A62528228F" xsi:type="Label" x="11" y="551" w="1030" h="154">`

The type is "Label" and this type cannot contain child nodes. It should be type "Container".

**Comment by GeraldGrootRoessink** [comment] 2022-05-13 09:21
You guys are quick. Thanks a million.  This helps me to unravel our present policy om tooling.
