### ISSUE TITLE
[Linux] Relations not fully drawn if label visible

### ISSUE THREAD

**Issue by fsclavo** [archimatetool/archi#568] opened 2020-01-06 20:16 UTC
### Version of Archi, Operating System

4.6.0, running on Linux (several machines/versions: Ubuntu 18.04 and 16.04 at least)

### Expected Behaviour

Relations must be visible at every zoom level

### Actual Behaviour

Some relations between elements, disappears at certain zoom levels. Doing zoom out makes relations visible again. It's look like a rendering issue.

### Steps to Reproduce the Behaviour
1.
2.
3.
Below are two samples of the same view, elements and relations at different zoom levels:

![Screenshot from 2020-01-06 17-09-59](https://user-images.githubusercontent.com/8451402/71845892-0f722800-30a8-11ea-991e-b80b7b3de4bb.png)
![Screenshot from 2020-01-06 17-15-21](https://user-images.githubusercontent.com/8451402/71845945-2c0e6000-30a8-11ea-9d6a-b226d409ce7f.png)

**Comment by Phillipus** [comment] 2020-01-06 20:28
We need to narrow this down.

- What zoom level?
- Only when there is text on the relationship?
- Does it happen on all relationships?
- Is it only on relationships connected to nested elements?
- Can you produce a simple model that always exhibits this?
- GTK version?

**Comment by Phillipus** [comment] 2020-01-06 20:46
I can now reproduce this:

- Zoom at 150% or 200%
- Text on relationships
- Properties window open or closed helps

@jbsarrodie It's to do with the text clipping patch in `AbstractDiagramConnectionFigure`

**Comment by Phillipus** [comment] 2020-01-06 21:13
It's only happening on Linux. Zoom has to be at 100 or 150% and you need the Properties window open below the View sometimes. 

<img width="1440" alt="Screenshot 2020-01-06 at 21 11 35" src="https://user-images.githubusercontent.com/600504/71849198-5c1a2b00-30c9-11ea-87f2-7bacd950eb10.png">

**Comment by Phillipus** [comment] 2020-01-06 21:14
Simple test model

[test.archimate.zip](https://github.com/archimatetool/archi/files/4027847/test.archimate.zip)

**Comment by Phillipus** [comment] 2020-01-06 21:17
This is going to be one of those OS-specific things that needs some kind of workaround. At this stage it's:

- Only Linux
- Zoom > 100%
- To do with calculating the clipping region in `AbstractDiagramConnectionFigure#clipTextLabel`

**Comment by Phillipus** [comment] 2020-01-06 21:49
Can also occur at 75% if the view window is set to a narrow height.

<img width="1440" alt="Screenshot 2020-01-06 at 21 46 46" src="https://user-images.githubusercontent.com/600504/71851373-53782380-30ce-11ea-808b-8d471b42f739.png">

**Comment by Phillipus** [comment] 2020-01-07 11:34
This works OK up until version Archi 4.5. At version 4.5 we switched to Eclipse 4.11, and 4.13 in Archi 4.6. My guess is this is a side effect of the GTK 3 changes made in Eclipse in these later versions.

For investigation:

- Devise a workaround for Linux. Assumes we can figure out why the clipping region is wrong at different zoom levels on Linux
- Make the text clipping optional

**Comment by jbsarrodie** [comment] 2020-01-07 14:40
I'll try to reproduce on my laptop tonight (using elementary OS and not 'pure' Ubuntu)

**Comment by fsclavo** [comment] 2020-01-10 15:03
Hi Phil! Sorry about the delay.

   - Attached are 3 pictures of the same view portion, at three different
   zoom levels to show the issue.
   - Apparently yes, it looks like only relationships with text are
   affected.
   - No
   - No
   - Every model I create has the same issue, and it isn't exclusive on my
   PC, every Linux with Archi (even different Ubuntu version) here where we
   work has the same issue with Archi 4.6 (not present on previous versions).
   - GTK versions below (sorry about the list but I don't know which is
   needed):

fsclavo@neftali:~$ dpkg -l | grep libgtk
ii  libgtk-3-0:amd64                           3.22.30-1ubuntu4
                   amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                               3.22.30-1ubuntu4
                   amd64        programs for the GTK+ graphical user
interface library
ii  libgtk-3-common                            3.22.30-1ubuntu4
                   all          common files for the GTK+ graphical user
interface library
ii  libgtk2.0-0:amd64                          2.24.32-1ubuntu1
                   amd64        GTK+ graphical user interface library
ii  libgtk2.0-bin                              2.24.32-1ubuntu1
                   amd64        programs for the GTK+ graphical user
interface library
ii  libgtk2.0-common                           2.24.32-1ubuntu1
                   all          common files for the GTK+ graphical user
interface library
ii  libgtk3-perl                               0.032-1
                    all          Perl bindings for the GTK+ graphical user
interface library
ii  libgtkmm-2.4-1v5:amd64                     1:2.24.5-2
                   amd64        C++ wrappers for GTK+ (shared libraries)
ii  libgtksourceview-3.0-1:amd64               3.24.7-1
                   amd64        shared libraries for the GTK+ syntax
highlighting widget
ii  libgtksourceview-3.0-common                3.24.7-1
                   all          common files for the GTK+ syntax
highlighting widget
ii  libgtkspell0:amd64                         2.0.16-1.2
                   amd64        spell-checking addon for GTK's TextView
widget

**Comment by jbsarrodie** [comment] 2020-01-10 19:36
> I'll try to reproduce on my laptop tonight (using elementary OS and not 'pure' Ubuntu)

I can reproduce under elementary OS (5.1 Hera, based on Ubuntu Bionic 18.04 LTS) too

My version of GTK is 3.22.30

**Comment by jbsarrodie** [comment] 2020-01-10 19:37
>Devise a workaround for Linux. Assumes we can figure out why the clipping region is wrong at different zoom levels on Linux

I'm looking at it.

**Comment by jbsarrodie** [comment] 2020-01-10 20:37
In fact zoom level is not the cause because I can reproduce the issue even at 100%:
![Screenshot from 2020-01-10 21-30-21](https://user-images.githubusercontent.com/5757396/72184364-926ce880-33f0-11ea-8957-8a417938aa62.png)

(still working to narrow it down)

**Comment by Phillipus** [comment] 2020-01-10 20:39
> In fact zoom level is not the cause because I can reproduce the issue even at 100%

In some ways that is good news. This means that the clipping region is incorrect in all cases. Interesting that it occurs when the viewport is narrow, (Thanks for taking a look at this :-))

**Comment by Phillipus** [comment] 2020-01-10 20:41
BTW - I don't see any scrollbars in that screenshot. I wonder if the viewport size is being calculated differently? (Not exactly sure what I mean by this, just an intuition)

**Comment by jbsarrodie** [comment] 2020-01-10 20:52
> BTW - I don't see any scrollbars in that screenshot. I wonder if the viewport size is being calculated differently? (Not exactly sure what I mean by this, just an intuition)

Yes, that's related to the issue. In fact, the clipping area is always set as rectangle which has the same size of the viewport but set on (0,0) and not the top left corner of the visible part of the view.

It looks like a bad mix between absolute and relative coordinates of the clipping area.

**Comment by Phillipus** [comment] 2020-01-10 20:53
> Edit: my scrollbars auto-hide ;-)

I've read about problems with auto-hide scroll bars causing other issues.

**Comment by jbsarrodie** [comment] 2020-01-10 21:02
>I've read about problems with auto-hide scroll bars causing other issues.

Issue persists even if I disable auto-hide

**Comment by jbsarrodie** [comment] 2020-01-10 21:30
It seems that the issue is with Graphics.setClip(Path). For obscure reasons, it uses absolute coordinates and not coordinates relative to the viewing area.

So... @Phillipus How can I get the position of the viewing area ?

**Comment by Phillipus** [comment] 2020-01-10 21:32
> So... @Phillipus How can I get the position of the viewing area ?

I will investigate soon,,,

**Comment by Phillipus** [comment] 2020-01-10 21:36
Just noticed that one can set a "clipping strategy" for a figure.

In `AbstractDiagramConnectionFigure#getConnectionLabel() one could do:

`fConnectionLabel.setClippingStrategy(clippingStrategy);`

**Comment by Phillipus** [comment] 2020-01-10 21:40
> 
> 
> Just noticed that one can set a "clipping strategy" for a figure.
> 
> In `AbstractDiagramConnectionFigure#getConnectionLabel() one could do:
> 
> `fConnectionLabel.setClippingStrategy(clippingStrategy);`

Forget that.

**Comment by jbsarrodie** [comment] 2020-01-10 21:41
>Forget that.

Why, this might be the right way to solve the original goal (not drawing the connection behind the label). Not by setting the clipping strategy of the label but the one of the connection.

**Comment by Phillipus** [comment] 2020-01-10 21:43
> Why, this might be the right way to solve the original goal (not drawing the connection behind the label). Not by setting the clipping strategy of the label but the one of the connection.

Because it only applies to child figures. It's not even called when it's implemented on a connection label.

**Comment by Phillipus** [comment] 2020-01-10 21:51
> Not by setting the clipping strategy of the label but the one of the connection.

That is called. Maybe worth investigating.

**Comment by Phillipus** [comment] 2020-01-10 21:55
Might be worth playing with variations of this:

```
    public Label getConnectionLabel() {
        if(fConnectionLabel == null) {
            fConnectionLabel = new Label(""); //$NON-NLS-1$
            add(fConnectionLabel);
            
            setClippingStrategy(new IClippingStrategy() {
                @Override
                public Rectangle[] getClip(IFigure childFigure) {
                    Rectangle r = fConnectionLabel.getTextBounds();
                    return new Rectangle[] { r };
                }
            });
        }
        return fConnectionLabel;
    }

```

**Comment by Phillipus** [comment] 2020-01-10 22:00
There's a draw2d class that implements it - `ViewportAwareConnectionLayerClippingStrategy`

**Comment by Phillipus** [comment] 2020-01-10 22:01
> 
> 
> > So... @Phillipus How can I get the position of the viewing area ?
> 
> I will investigate soon,,,

`ViewportUtilities` perhaps?

**Comment by Phillipus** [comment] 2020-01-11 11:24
I had a play with `IClippingStrategy` but I don't think this is going to help. It only asks for the clipping regions for child figures - labels and end-point figures.

Ultimately, `IClippingStrategy#getClip(Figure)` is called by `Figure#paintChildren(Graphics)` which is kind of doing what we already do in our `clipTextLabel()` method.

**Comment by Phillipus** [comment] 2020-01-11 11:51
But...it is possible to set the clipping strategy on the parent of the connection:

```
    public Label getConnectionLabel() {
        if(fConnectionLabel == null) {
            fConnectionLabel = new Label(""); //$NON-NLS-1$
            add(fConnectionLabel);
            
            getParent().setClippingStrategy(new IClippingStrategy() {
                @Override
                public Rectangle[] getClip(IFigure childFigure) {
                    if(childFigure == AbstractDiagramConnectionFigure.this) {
                        Rectangle r = getBounds().getCopy();
                        Rectangle l = fConnectionLabel.getBounds().getCopy();
                        //translateToRelative(r);
                        return new Rectangle[] { r };
                    }
                    else {
                        Rectangle r = childFigure.getBounds().getCopy();
                        return new Rectangle[] { r };
                    }
                }
            });
        }
        return fConnectionLabel;
    }

This POC code does the reverse of what we want, it only displays the label area. I've uploaded this to a new branch "clipping".
```

**Comment by Phillipus** [comment] 2020-01-11 23:06
After some experimentation it turns out that an `IClippingStrategy` is not going to solve this problem. Setting the `IClippingStrategy` on the connection or it's parent (as in the previous comment) will not do what we are already achieving in our `clipTextLabel()` method. If we exclude the label area from the clipping strategy of the connection it will not be rendered at all.

**Comment by Phillipus** [comment] 2020-01-13 14:47
I experimented some more with `IClippingStrategy` and variations on our `clipTextLabel()` method. However, I think the underlying issue is a Linux thing where something is wrong with the reported clipping area.

**Comment by jbsarrodie** [comment] 2020-01-13 14:49
I think I can create a fix (will be Linux specific of course), but simply need a bit more time.

**Comment by Phillipus** [comment] 2020-01-13 14:50
> I think I can create a fix (will be Linux specific of course), but simply need a bit more time.

Great! Take your time :-)

**Comment by jbsarrodie** [comment] 2020-01-13 14:56
> After some experimentation it turns out that an `IClippingStrategy` is not going to solve this problem. Setting the `IClippingStrategy` on the connection or it's parent (as in the previous comment) will not do what we are already achieving in our `clipTextLabel()` method. If we exclude the label area from the clipping strategy of the connection it will not be rendered at all.

I guess this could work but this would need some refactoring so that, at the end, the connection figure would in fact be composed of two child figures: one for the connection line and one for the lablel. We could then set an IClippingStrategy on the connection figure to impact only the connection line and not the label.

**Comment by Phillipus** [comment] 2020-01-13 14:59
> I guess this could work but this would need some refactoring so that, at the end, the connection figure would in fact be composed of two child figures: one for the connection line and one for the lablel. We could then set an IClippingStrategy on the connection figure to impact only the connection line and not the label.

It's not worth it.  `Figure#paintChildren(Graphics)` queries a Figure's `IClippingStrategy#getClip()` method and effectively does what we are doing in our method.

**Comment by Phillipus** [comment] 2020-01-13 14:59
I guess the best way around this would be to have moveable labels.

**Comment by jbsarrodie** [comment] 2020-01-13 15:04
> I guess the best way around this would be to have moveable labels.

Not really. This would of course provide more freedom, but at the end, even with movable label we would end up making sure that line is not drawn under the label when it is on top of the line, so this would exibit the same issue.

**Comment by ilyacoos** [comment] 2020-01-29 14:50
Hi guys,

Do you have any update on this issue?  It really hearts :(

**Comment by Phillipus** [comment] 2020-01-30 09:56
> Do you have any update on this issue? It really hearts :(

Still under investigation.

@jbsarrodie I can follow any leads if you have any.

If we can't work around this we can add an option to disable text clipping on Linux.

**Comment by Phillipus** [comment] 2020-03-02 11:53
> Hi guys,
> 
> Do you have any update on this issue? It really hearts :(

@ilyacoos Until we come up with a proper fix for this, you could use the Archi Early Access version. 

There is a new Preference setting for connection text label background drawing strategies (Preferences -> Connections -> Drawing). Set this to either "Opaque", or "Transparent".

https://www.archimatetool.com/beta/

**Comment by ilyacoos** [comment] 2020-03-04 21:01
Thnx ;)

**Comment by jbsarrodie** [comment] 2020-04-02 13:41
FYI

I worked on this yesterday and tried several approaches, but I have absolutely no way to solve this issue. It really seems that the root cause lies in some regressions in GC related to GTK3: as soon as you set the graphics's clipping area, this clipping area is itself clipped by the viewport without taking its position into account (ie. the relationships are clipped only drawn on a zone that matches the viewpoint in the top left position).

I've been able to found references of similar bugs, like [this one] (https://bugs.eclipse.org/bugs/show_bug.cgi?id=545226), and I guess we'll have to test with recent version of eclipse (2020-03 is available now), and open a bug on bugs.eclipse.org if still not fixed (in this case I don't expect it to be fixed anytime soon).

**Comment by Phillipus** [comment] 2020-04-02 13:51
@jbsarrodie Thanks for taking a look at this, I agree that it must be something to do with GTK3 and SWT.

> we'll have to test with recent version of eclipse (2020-03 is available now)

Already tested. Not fixed. :-(

**Comment by jbsarrodie** [comment] 2020-04-02 14:05
>Already tested. Not fixed. :-(

I did test too, but wanted your feedback in case I did something wrong.

I guess we can open a bug on bugs.eclipse.org. Who knows, maybe Eclipse guys will fix it (they actually did quite quickly for bug 545226).

In the meantime, I'm sorry to say that, because the vast majority of users run Windows, and most of the other run Mac OS,fixing Linux only bugs is not a priority (and I personally  run both Windows and Linux).

**Comment by Phillipus** [comment] 2020-04-02 14:10
> I guess we can open a bug on bugs.eclipse.org

The problem with that is that unless we can provide a simple SWT snippet that demonstrates the problem they won't even look at it.

> In the meantime, I'm sorry to say that, because the vast majority of users run Windows, and most of the other run Mac OS,fixing Linux only bugs is not a priority (and I personally run both Windows and Linux).

There is a new Preference setting for connection text label background drawing strategies (Preferences -> Connections -> Drawing). Transparent, Opaque, and Clipped. As long as the relationship label is on a white background "Opaque" will do the job.

**Comment by jbsarrodie** [comment] 2020-04-02 14:16
>Transparent, Opaque, and Clipped.

I didn't notice the "opaque" option. That's a good compromise.

The issue though is that Archi Collaboration Server is based on Linux thus will be impacted too :-(

While reading this issue's comments, I noticed that we never tested with GTK 2. I'll do a test later today as this might work around the bug (don't expect too much though)

**Comment by Phillipus** [comment] 2020-04-02 14:18
I read that Eclipse devs made a lot of "improvements" under the hood for GTK, so they might have broken something.

**Comment by jbsarrodie** [comment] 2020-04-02 19:36
@Phillipus Could you please test branch `issue_568` on Linux, WIndows and Mac? It seems that it solves the bug on Linux.

**Comment by Phillipus** [comment] 2020-04-02 20:04
Fuck yeah! :-)

(please explain how this works)

**Comment by jbsarrodie** [comment] 2020-04-02 20:17
> Fuck yeah! :-)

![image](https://user-images.githubusercontent.com/5757396/78296833-b98a1080-752e-11ea-8587-bd2a0ccb6d45.png)

> (please explain how this works)

Well, it works ;-)

Seriously, I tried lots of things (hacking GC and Transform) and nothing worked. At some point I discovered that there are several methods to set clipping area. I tried `Graphics.clipPath(path)` and it was doing the opposite of what we want (it was drawing the relationship only behind label). Then I remembered that for Mac we were using another method to create the Path, so I simply tried to use `Graphics.clipPath(path)` with the "Mac" Path and it worked (TBH there should be no difference because at the end that's the same Path). So, as the "Mac" Path was just another way of expressing the same (Windows+Linux) Path, I simplified the code to use only the "Mac" Path and `Graphics.clipPath(path)`. And voilà !

**Comment by Phillipus** [comment] 2020-04-02 20:36
Good catch. I bet you spent a lot of time on it...gave up....but couldn't let go! And came back at it...again...and again....I WILL NOT BE BEATEN!!...until...finally...it works.

I would never do that. ;-)

**Comment by Phillipus** [comment] 2020-04-02 20:46
> TBH there should be no difference because at the end that's the same Path

I wonder what the difference is between the "Mac" Path and the other one?

**Comment by jbsarrodie** [comment] 2020-04-02 21:10
> I wonder what the difference is between the "Mac" Path and the other one?

The original Path is computed as an intersection of two rectangle (one minus the other), while the "Mac Path" (in fact that was my very first implementation during my tests) is a simple shape like this one:
````
_ __________________________
|\\                         |
| \\                        |
|  \\___________________    |
|  |                    |   |
|  |____________________|   |
|                           |
|                           |
|___________________________|
````

**Comment by Phillipus** [comment] 2020-04-03 07:14
@jbsarrodie Tested more and seems to be OK.  If it's OK with you, I'll merge your fix and close this?

**Comment by jbsarrodie** [comment] 2020-04-03 07:44
If it's OK for you it's OK for me.

**Comment by Phillipus** [comment] 2020-04-03 07:46
Merged and branch deleted.

Fixed and Closed! 🥇

**Closed by Phillipus** 2020-04-03 07:46 UTC
