### ISSUE TITLE
Review new icon set and some issues

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#237] opened 2017-05-25 10:49 UTC
@pds2208 has very kindly re-done the icons and created 2x versions for hi-def screens. I've manually committed his PR into a new branch "icons". We need to review these icons and a couple of issues. Also, note that screenshots for the user guide will have to be re-done.

**Comment by Phillipus** [comment] 2017-05-25 10:52
In FontFactory class the default font has been changed from Lucida Grande 12 to SF Compact Text 11. What is the impact of this change? Is this font supported on all Mac OS versions?

**Comment by Phillipus** [comment] 2017-05-25 10:55
Some text messages have also been changed. These need to be agreed, and, then the help files need to be updated in accordance.

**Comment by pds2208** [comment] 2017-05-25 11:01
Yeah the Lucia Grande is butt ugly and was replaced ion OS X in 2014. The San Francisco font was introduced in El Capitan and the latest is currently Sierra, one release later. So no, it’s not supported out of the box (unless you download it) before El Capitan. Still, Yosemite is probably not going to get security updates from Autumn anyway.

**Comment by pds2208** [comment] 2017-05-25 11:02
Okay sorry, ‘Copy to image’ under export did not make sense to me…

**Comment by Phillipus** [comment] 2017-05-25 11:05
> So no, it’s not supported out of the box (unless you download it) before El Capitan. Still, Yosemite is probably not going to get security updates from Autumn anyway.

But we need to keep supporting this version of OS X for now. I know some users on it.

**Comment by pds2208** [comment] 2017-05-25 11:21
Perhaps Helvetia then

**Comment by Phillipus** [comment] 2017-05-25 16:47
We need user feedback on these new icons, as I don't want to be the only person to have a say. I'll probably make a test build and get it out for testing.

**Comment by pds2208** [comment] 2017-05-25 16:52
Fair enough but it’s Mac users who will notice it right away as by now most will have retina screens. Looks even better, actually MUCH better, with the San Francisco font so I’ll be running my own version until it’s eventually rolled into the standard product.

On my 4k PCs it also looks really good as well but I suspect most PC users won’t have 4k screens.

**Comment by Phillipus** [comment] 2017-05-25 17:07
It's not that there are 2x icons that's in need of user feedback it's that many of the icons are different. The SF font needs more thought. I'm not sure if the one you chose is affected by this bug:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=486734

**Comment by pds2208** [comment] 2017-05-25 17:09
That (its duplicate)  is marked as fixed back in 2015….

**Comment by Phillipus** [comment] 2017-05-25 17:11
I affects italic in the models tree, actually this one https://bugs.eclipse.org/bugs/show_bug.cgi?id=510741

**Comment by pds2208** [comment] 2017-05-25 17:14
Ah, right. That was my other bug bear I was going to change. I have to look really closely to see the difference on both Mac and Pc. Was going to change it use a strikeout as it’s much easier to see….Thoughts?

**Comment by Phillipus** [comment] 2017-05-25 17:15
I don't want to use strikeout in place of italics.

**Comment by pds2208** [comment] 2017-05-25 17:16
Why?

**Comment by Phillipus** [comment] 2017-05-25 17:17
Because it's not appropriate. Italic is the font we've been using for 7 years to indicate that an element is not used anywhere in a view.

**Comment by Phillipus** [comment] 2017-05-25 17:20
While I appreciate the work you've done on this, we will not make changes to the UI and change the default fonts without consensus from the user community, and also from @jbsarrodie .

**Comment by pds2208** [comment] 2017-05-26 14:01
Well maybe but it’s next to impossible to see properly. Another option is to colour it differently and keep italics. So something like this in TreeModelViewer makes things crystal clear to anyone….:

@Override
        public Color getForeground(Object element) {
        	// colour unused item red
            if (Preferences.STORE.getBoolean(IPreferenceConstants.HIGHLIGHT_UNUSED_ELEMENTS_IN_MODEL_TREE) && element instanceof IArchimateConcept) {
                if (!DiagramModelUtils.isArchimateConceptReferencedInDiagrams((IArchimateConcept)element)) {
                	return Display.getCurrent().getSystemColor(SWT.COLOR_RED);
                }
            }
            return fViewpointFilterProvider.getTextColor(element);
        }

**Comment by Phillipus** [comment] 2017-05-26 14:04
And would this be a problem for users who are colour blind? At any rate, it's probably best to open a separate issue for this and get some user feedback.

**Comment by pds2208** [comment] 2017-05-26 14:13
It's in addition to italics

**Comment by jbsarrodie** [comment] 2017-05-26 18:49
Hi,

I've just had a look, and I do see some issues with new icons (not all of course, but enough to discuss it).

FYI I tested on a 14 inches monitor (1366x768), and here I my remarks:
* icons used on the palette have been changed and no more match the one used inside drawn figure.
* icon for note has been changed and is now wrong (dog ear top right while it is drawn bottom right)
* some icons look low contrast and blurred, this might be caused by gradient that should not be used for small icons (eg. newfile, outline_co, magic_connection...)

I recently had to create some icons and found it to be very difficult to create good looking ones that are so small (16px x 16px). I think this raises general questions:
* can we use bigger icons with eclipse RCP apps ?
* do we want to create a new icon set from scratch ?
* if yes, do we want color or monochrome icons ?

**Comment by Phillipus** [comment] 2017-05-26 18:58
Palette icons have to be 16x12 and 32x32 pixels size (large and small icon setting). The main toolbar seems only to show 16x16 size (of they are larger they get reduced to 16x16 I think). Not sure what happens on View toolbars and context menus.

**Comment by Phillipus** [comment] 2017-05-26 19:03
There's a lot going on this issue:

- 2x icons for hi-res screens
- New icons that have been redesigned
- Some text strings changed
- Font changes

The most immediate concern was the first point - to provide 2x icons for users with hi-res screens. Does it makes sense to ficus on that?

**Comment by jbsarrodie** [comment] 2017-05-26 19:12
> The most immediate concern was the first point - to provide 2x icons for users with hi-res screens. 

I think that's the most important thing for the moment. The (potential?) issues is that either it is possible to find already existing 2x icons from eclipse project (and thus these are the same as the one we've been using), or they have to be created from scratch, and if I understand well that's the approach that has been taken here.

From my understanding the issue with 2nd approach is that you can't really upscale existing icons, so @pds2208 had to create them from scratch (or find already existing alternatives), with side effects we know (some icons are differents, some are blurred...)

That's why I wonder if this is the good way to move. It might be easier (after all) to find already existing icons sets that are good looking and already created for several sizes.

BTW, here is a [blog post](http://mezzoblue.com/archives/2007/02/21/icon_design/) that summarizes common issues with such small icons...

**Comment by Phillipus** [comment] 2017-05-26 19:16
Good points. And also we need to bear in mind:

- If/when icons are changed, all help documentation screenshots will have to be redone
- This should not come as a surprise to the many Archi users

**Comment by pds2208** [comment] 2017-05-27 06:51
The blur  is for the cursor. The others look fine to me?  The cursor seems to be an eclipse thing - eclipse is still very poor on hi dpi screens. I’ve reverted back to gif for this until they fix it. Good luck finding a full icon set ;) As it says below, it’s near impossible to scale up from 16x16.

I’ve added an option in preferences to highlight unused relations in red - the italic option is still there so you can have either, or both. I find it impossible top see the italic text. I’ll change this when I get a chance to allow any colour. Not having a colour highlight option because of the small number of colour blind users seems daft to me. 

The difference between icons on the canvas re the palette is odd. How are the ones on the canvas drawn and why aren’t they using the same icons as the palette?

Also the html reports on pc are pretty much useless on the PC as the diagrams are unreadable. Again this seems to be an eclipse thing  as I tried the standard java image library with the same result so it’s not saving the image thats doing it, it’s getting the image from the canvas. Yet the method used to save to svg or pdf is fine... Will fix this when I get around to it.

The font and text changes seems obvious ones to me. The text changes is a case of plain English and the old Mac font look awful on retina displays, which is why apple changed it in the first place. I would suggest that users on very old hardware upgrade rather than have the majority of users having to be held back due to a minority of users. If that is the case then advancements are impossible, right?

I know these changes need approval etc. but I find the tool MUCH improved because of it, particularly, but not exclusively, on the Mac . I’m happy to roll my own and continue to improve it to make it more usable for me for me and my colleagues. Up to you if you accept the changes or not…. :)

Paul

**Comment by Phillipus** [comment] 2017-05-27 10:48
The option to set UI font and colours is a separate issue. See #239 and continue the discussion there.

**Comment by Phillipus** [comment] 2017-05-27 10:53
> How are the ones on the canvas drawn and why aren’t they using the same icons as the palette?

These are "drawn" in code so that they retain integrity when zooming in and when exporting to SVG. Raster graphics don't work for these cases.

> Also the html reports on pc are pretty much useless on the PC as the diagrams are unreadable.

Please create a separate issue with more detailed info rather than "pretty much useless"

> I would suggest that users on very old hardware upgrade rather than have the majority of users having to be held back due to a minority of users.

Then I'm out of luck, since I use an old Mac laptop from 2011 and don't have the spare cash to invest in a high end MacBook to support the 5% of Archi Mac users.

**Comment by pds2208** [comment] 2017-05-27 12:05
Hmm what I can do is redo the icons by extracting them from an svg export and converting them to png. 

I'll have a go at fixing the HTML reports on pc but I'll probably have to find a different way of doing it.

**Comment by jbsarrodie** [comment] 2017-05-27 16:42
> Also the html reports on pc are pretty much useless on the PC as the diagrams are unreadable.

I'd like to have an example as I use the HTML export mainly on windows with absolutly no issues. But as Phil said, preferably on another issue to not mix different subjects in this thread.

**Comment by pds2208** [comment] 2017-05-28 13:04
Attached. Missing lines, RHS cut off etc. This is on a surface book. Same on a dell xps15 and HP x360. Absolutely fine on a mac.

Perhaps it has something to do with hi-dpi (actually normal DPI nowadays) on PC / eclipse.

**Comment by jbsarrodie** [comment] 2017-05-28 13:58
Attachments dont work from email answer, you'll have to edit your message on github and add attachment here.

> Perhaps it has something to do with hi-dpi

Yes this might be due to hidpi.

> actually normal DPI nowadays

Well, in some (most) case hidpi is only a marketing thing that adds nothing. The only added value is when there is an increase in the usable resolution (at least full hd). [Here is a good post on that topic](https://medium.com/elementaryos/what-is-hidpi-and-why-does-it-matter-b024eabea20d).

**Comment by pds2208** [comment] 2017-05-28 14:11
Done.

**Comment by pds2208** [comment] 2017-05-28 14:14
I've uploaded a new version:

'Highlight unused items in red'
Palette 'use large icons' does just that - for the Archimate ones anyway. Seems that eclipse is resampling them unnecessarily though.

**Comment by Phillipus** [comment] 2017-05-28 14:16
Please continue discussion of image quality at issue #240

**Closed** 2017-05-29 19:39 UTC
