### ISSUE TITLE
Text alignment is not set after appearance box is scrolled down with mouse wheel

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#1053] opened 2024-07-02 14:22 UTC
### Version of Archi
5.3.0

### Archi Plug-ins
no

### Operating System
windows 10

### Expected Behaviour
clicking on text alignment icons should change text alignment of the selected element

### Actual Behaviour
After appearance tab of properties window is scrolled down with mouse wheel, first click on a text alignment icon doesn't change text alignment of the selected element but scrolls the appearance tab instead. This happens only if mouse wheel is used for scrolling, keyboard and scrollbar scrolling are not affected.

### Steps to Reproduce the Behaviour
prerequisites: properties window height is not sufficient to display appearance tab completely, scrolling is required to get to its bottom

1. open properties-appearance of an element, select appearance tab and and scroll to the the bottom with excessive use of mouse wheel
2. try changing text alignment by clicking on any of the alignment icons

**Comment by Phillipus** [comment] 2024-07-02 14:34
I can't reproduce this at all. I'm on Windows 11, though. Please check if the same behaviour happens on other installations in case it is a hardware or configuration issue.

**Comment by Phillipus** [comment] 2024-07-02 14:42
Actually I can reproduce it if I click on the last text position button. No idea why this happens. Might be an Eclipse bug.

**Comment by Phillipus** [comment] 2024-07-02 15:12
Nothing to do with the scroll wheel or the text alignment button:

1. Select an ArchiMate element in a View
2. Select the Appearance tab
3. Scroll to the bottom either with the mouse wheel or the scrollbars
4. Select a different ArchiMate element in the View
5. Click anywhere in the lower white space of the Appearance tab
6. The tab scrolls upwards

This is OK on Mac, didn't test on Linux.

Seems that when clicking somewhere in the tab the focus jumps upwards. This is something in the Eclipse framework so I can't fix this. Needs more investigation.

**Comment by Phillipus** [comment] 2024-07-02 17:19
This problem is a side effect of accessibility support.

The idea is that a user can select a control in the pane and then use the Tab key (or Shift-Tab key combination) to move through the controls. When a control gains the focus it is scrolled into view if it is not visible. If the `trackFocus` option is set to `false` then the control will not scroll into view and this is bad for accessibility.

The original problem is caused by scrolling to the bottom of the controls in the pane, moving the focus away by clicking elsewhere, and then clicking in the pane again. The focus is then set to the first control in the pane and this causes the pane to try to scroll up.

I'm sorry but I can't change this because of these reasons, so I'll close this.

**Closed by Phillipus** 2024-07-02 17:19 UTC

**Comment by lvmm** [comment] 2024-07-02 18:25
No, my scenario is different: no clicking elsewhere; just scrolling down and trying to select the control which, by the way, is fully visible, so there is no reason to scroll the view, is enough. BTW on linux it is even weirder - the pane is scrolled all the way to the top, so the control actually becomes invisible, and two text styles get selected at once.

before:
![Screenshot_20240702_211731](https://github.com/archimatetool/archi/assets/11752339/849ddd95-98f0-4d68-9929-c6f8efb4d2ed)
after clicking just once and scrolling back down to see results:
![Screenshot_20240702_211946](https://github.com/archimatetool/archi/assets/11752339/e4ee09a8-12ca-4fb9-bfb7-f842db862cc8)

**Comment by Phillipus** [comment] 2024-07-02 18:30
> No, my scenario is different: no clicking elsewhere; just scrolling down and trying to select the control

The cause is exactly the same. Selecting the control puts the focus on the pane. It's not handled well by the Eclipse framework but, as I said, I can't turn off the accessibility option.

**Comment by lvmm** [comment] 2024-07-02 18:49
Uh... I don't see how control jumping all over the place and disappearing from the the screen can help people with disabilities whatever they are. Maybe a global option in setup to turn accessibility framework on or off?

**Comment by Phillipus** [comment] 2024-07-02 18:55
> Uh... I don't see how control jumping all over the place and disappearing from the the screen can help people with disabilities whatever they are. Maybe a global option in setup to turn accessibility framework on or off?

Accessibility is not just about people with disabilities, it's also about providing UI access with a keyboard instead of a mouse. I've explained why this is happening, and this side effect is one of the issues with the Eclipse framework.
