### ISSUE TITLE
[Issue] 4.7 beta merge affects linked views

### ISSUE THREAD

**Issue by rich-biker** [archimatetool/archi#591] opened 2020-03-10 09:52 UTC
### Version of Archi, Operating System
4.7 Beta (Build 202003021001)
macOS Catalina 10.15.3

### Expected Behaviour
Merging one model into another should allow linked views to work without re-opening the model.

### Actual Behaviour
After merging into a model which has a view of linked views, double clicking on the linked view opens up a blank view with a red exclamation. You can save the model and re-open it and the linked views will be ok (i.e. they open and display the content).

### Steps to Reproduce the Behaviour
1. Create a 'master model' with a main view.
2. Create overview view in that master model with a linked view to the main view
3. Save the 'master model'
4. Save-as the master model to an 'offline model'
5. So some edits in the 'offline model' (I added a process step to the main view).
6. Save the 'offline model'
7. Reopen the 'master model', import the 'offline model' into the 'master model'.
8. In the overview view, click on the linked view to the main view. Enjoy the red exclamation.

![Screenshot 2020-03-10 at 09 34 46](https://user-images.githubusercontent.com/18450552/76300525-c19abb80-62b4-11ea-96c7-d4cc42737854.png)

#### Workaround
9. Save and Close and Reopen the 'master model'

**Comment by Phillipus** [comment] 2020-03-10 10:02
Stage 7a - "Update Existing objects and folders" is checked

**Comment by Phillipus** [comment] 2020-03-10 13:42
I've fixed this now and it's in Archi 4.7 EA 2 - https://www.archimatetool.com/beta/

@rich-biker Thanks for the clear bug report, could you test EA2?

**Comment by rich-biker** [comment] 2020-03-10 14:32
Just tested it. All good now on the use case I described.

The only other odd thing is on my working large model, I do a similar thing (save-as; edit; import into original) and I see a LOT of changed elements I wouldn't have expected. Why is that?

The changes I made in this 'offline model' were to two views that don't even reference some of the 'elements updated'. I now realise that I actually had the 'Update existing objects and folders' ticked; without it nothing gets updated. Why would it need to update all the other elements in the model that are not changing / merging?

**Comment by Phillipus** [comment] 2020-03-10 14:45
When "Update existing objects and folders" is ticked every existing concept, folder and Views is checked to be updated to ensure consistency of the model. The log message is recorded even if nothing has actually changed. It would be too complicated otherwise,

**Comment by rich-biker** [comment] 2020-03-10 14:46
Thanks - that makes sense.

**Comment by Phillipus** [comment] 2020-03-10 14:49
But I can see that the log message is not helpful if something wasn't actually updated. The problem is the import checking is a bit complicate what with Undo/Redo commands and cross-references that it wouldn't be easy to actually check all updates at this level of granularity. I'll double-check it though in case...

**Comment by rich-biker** [comment] 2020-03-10 14:52
Also maybe just state it like it is in the release notes and online help to set expectations; but yes, it would be nice to only have _actually_ updated elements listed.

**Comment by Phillipus** [comment] 2020-03-10 15:07
The problem is with updating Views. When a View is updated we take a brute force approach and remove all child objects in the target View and replace them with the child objects of the imported View. Otherwise an update could get extremely complicated if we compared every object and connection with the original. So we don't actually know if anything changed.

Perhaps the log should say something like "checked for update".

**Comment by rich-biker** [comment] 2020-03-10 15:17
Is there some sort of mad reliable checksum algorithm that can be done on both views to know if they have changed?

**Comment by Phillipus** [comment] 2020-03-10 15:50
> 
> 
> Is there some sort of mad reliable checksum algorithm that can be done on both views to know if they have changed? (like I know what I'm talking about, ha).

Nice idea but wouldn't work.

I've checked the importer code and to do a comparison of changes between imported and target model objects at a fine level of granularity would require a re-write of the importer code, and be a total pain.

**Comment by Phillipus** [comment] 2020-03-15 20:11
> Perhaps the log should say something like "checked for update".

It will say "synchronized".

**Comment by Phillipus** [comment] 2020-03-16 08:59
Closing this as fixed. Please re-open if it happens again.

**Closed by Phillipus** 2020-03-16 08:59 UTC
