### ISSUE TITLE
no nesting relationship prompt when pasting

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#1055] opened 2024-07-09 14:06 UTC
### Version of Archi
5.3.0

### Archi Plug-ins
no

### Operating System
windows 10, linux

### Expected Behaviour
When an element is pasted inside another element Archi should prompt for nesting relationship the way it does when one element is dragged inside another.

### Actual Behaviour
no prompt

### Steps to Reproduce the Behaviour
1. create an application component A (type doesn't really matter) and make it large enough to fit another element inside
2. create another application component outside of A
3. copy it to clipboard
4. rightclick inside A and select paste - a nested element is created but there is no relationship prompt

**Comment by Phillipus** [comment] 2024-07-09 14:10
Duplicate of https://github.com/archimatetool/archi/issues/745

**Closed by Phillipus** 2024-07-09 14:10 UTC
