### ISSUE TITLE
Adding existing element to view by drag&drop does not work on 4.6 on Linux Wayland

### ISSUE THREAD

**Issue by joelvim** [archimatetool/archi#560] opened 2019-11-21 11:22 UTC
### Version of Archi, Operating System
4.6 Linux Ubuntu 19.04
Tested with Java 8 and Java 11 openjdk
Only installed plugin: collaboration 0.5.3.201910181308

### Expected Behaviour
I expect the element to be added in the view.

### Actual Behaviour
The element is not added in the view without any error or message appearing, like if it was an impossible action.

### Steps to Reproduce the Behaviour
1. Open a view
2. Open the left model tree
3. Open an element category (Application for instance)
4. Chose an element and drag&drop it somewhere in the view (either in an empty space or above another element)
5. A nice animation showing the element coming back in the tree runs, and the element does not appear in the view.

**Comment by Phillipus** [comment] 2019-11-21 11:28
This is unlikely to be a fault with Archi as this hasn't been reported before and I can't reproduce this,

Can you try some different factors such as different installations, different Ubuntu version. Also, test whether your Ubuntu theme has anything to do with this.

**Comment by Phillipus** [comment] 2019-11-21 11:29
Also: are you dragging and dropping elements from the same model? You can't DnD from one model to a View in another model.

**Comment by joelvim** [comment] 2019-11-21 13:57
I only have one model. I tried to delete my .archi4 directory to check whether this could by linked to data from Archi 4.4 (my previous install) which could interfere with 4.6.
I tested with 2 JDKs (8 and 11), I changed the Ubuntu theme to return to default, I changed the Archi theme (tested with all 3), I tested on 3 versions of Archi (4.4 ok, 4.5.1 and 4.6 ko).
A colleague tried on ubuntu 19.10 and 4.6, and it's ok.
I tried with Eclipse 2019-9 which is based on the same Eclipse RCP (4.13.0.20190916-1045) than Archi 4.6, using Papyrus for UML modeling, and drag & drop between model explorer and the diagram view works fine.
Archi seems not to play well with something installed on my machine, and seems to be the only one I never had any problem with any eclipse version nor Intellij Idea (just to compare to java based tools).

**Comment by Phillipus** [comment] 2019-11-21 14:01
I'm afraid I don't know how to diagnose this issue. Do you think it's specific to Ubuntu 19.04? Perhaps something to do with the version of GTK?

**Comment by joelvim** [comment] 2019-11-21 14:16
I previously opened a bug with Archi 4.4 (#462 ) and we already suspected a GTK. However, the previous bug was solved by setting an env var but it doesn't solve anything in this case.

I am using the following versions of GTK : 
3.24.8-1ubuntu1 
2.24.32-3ubuntu1

Is there something specific about Archi in its usage of RCP, GMF, EMF, SWT or whatever that could explain there is no problem with Eclipse while there is one with Archi?

**Comment by jbsarrodie** [comment] 2019-11-21 14:28
> Is there something specific about Archi in its usage of RCP, GMF, EMF, SWT or whatever that could explain there is no problem with Eclipse while there is one with Archi?

The point is that Archi doesn't use GMF, so it is difficult to compare.

FWIW, I've just tested (again) on my own linux version and it works like a charm.

I'm afraid we won't be able to fix anything if it can't be reproduced outside of your own system :-(

**Comment by jbsarrodie** [comment] 2019-11-21 14:29
Just an idea...: do you use a trackpad? If yes, can you test with a mouse or disable any specific behavior related to trackpad (like support for gesture) ?

**Comment by jbsarrodie** [comment] 2019-11-21 14:36
BTW: is it a fresh install of Ubuntu or has your machine gone through several updates (which sometime leads to issues) ?

**Comment by joelvim** [comment] 2019-11-21 14:59
I use a trackpad. I cannot test with a mouse right now, but I'll give it a try tomorrow. However, this does not look like a trackpad/mouse problem, as the element is correctly dragged, it on drop that it reacts like if it was dropped on an area where it is not possible to drop.
It's gone through several updates (I think I use this machine since more or less 4 years), but a few months ago, I've cleaned it drastically deleting all the packages coming from other repositories than main. But there can be some config files remaining. Just an idea, can it be a wayland issue (I use it instead of X11)?

**Comment by Phillipus** [comment] 2019-11-21 15:00
> can it be a wayland issue 

Very likely.

I installed a fresh 19.04 with GTK 3.24.8-1ubuntu1 and it worked OK.

**Comment by Phillipus** [comment] 2019-11-21 15:13
Just checked. It's Wayland.

**Comment by joelvim** [comment] 2019-11-21 15:16
You were able to reproduce it on wayland?

**Comment by Phillipus** [comment] 2019-11-21 15:28
Yes.

Also, see https://github.com/archimatetool/archi/issues/488

It might not be an issues on 19.10 or upcoming releases. But there are several other issues around it.

However, as Archi is open source someone could contribute any workarounds or fixes to better support Wayland (not suggesting you do it).

**Comment by joelvim** [comment] 2019-11-22 07:37
That would explain my problems with Archi 4.4 needing SWT_GTK3 env var. I am gonna update to 19.10 to see if the issue is still here or not.
I don't think I could help to fix these issues, as I suppose a strong knowledge of SWT/Eclipse RCP is needed, and it is not my domain at all. However, I am open to help to test potential fixes, as my machine seem a great environment to reproduce bugs :smile:

**Comment by Phillipus** [comment] 2019-11-22 09:42
I think Wayland support should improve over time with each Ubuntu release and each Eclipse release.

The DnD issue might be fixable, but this DnD code is pretty standard and has worked in Eclipse for several years on all platforms. I don't want to spend time on trying to find a workaround if it can be fixed in Ubuntu or Eclipse. Here's another case of DnD not working:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=547735

And here are Wayland + Eclipse issues:

https://bugs.eclipse.org/bugs/buglist.cgi?classification=Eclipse&list_id=19075391&longdesc=wayland&longdesc_type=allwordssubstr&op_sys=Linux&op_sys=Linux-GTK&query_format=advanced

**Comment by Phillipus** [comment] 2019-11-22 11:18
> I am gonna update to 19.10 to see if the issue is still here or not.

The DnD problem is still there.

Also, I notice a few UI problems, lots of minor things that add up to a less-than-satisfactory experience. At this point I would not recommend using Wayland with Archi until improvements are made in Eclipse and/or Wayland. Certainly Archi code follows all the standard code patterns for Eclipse SWT and GEF and works on all other platforms for 10 years. Having said that, if there are known workarounds we can take a look at them.

**Comment by joelvim** [comment] 2019-11-25 10:45
The trick you gave on #488 does the job: `export GDK_BACKEND=x11` and there is no more problem.
This doesn't help in finding where the problems comes from, but it helps people like me stuck on wayland.
Maybe this could be added in the Archi-ubuntu.sh by default?

**Comment by Phillipus** [comment] 2019-11-25 10:52
I was reading [this article](https://www.swalladge.net/archives/2019/10/14/are-we-wayland-yet/) and he says "It appears that GTK and QT, the two most popular window toolkits, are still under heavy development to support Wayland fully."

So the dependencies for Archi are GTK, Eclipse and Wayland itself. I guess it's an ongoing thing.

> Maybe this could be added in the Archi-ubuntu.sh by default?

Yes, I'll add it for the next release,

**Comment by Phillipus** [comment] 2019-11-26 19:36
Can we close this? I think we have more general issues with Wayland so let's see what later versions bring,

**Closed by Phillipus** 2019-11-26 19:36 UTC
