### ISSUE TITLE
Preferences-groups dissapear in dialog box

### ISSUE THREAD

**Issue by pdussart** [archimatetool/archi#548] opened 2019-10-29 11:14 UTC
### Version of Archi, Operating System
Archi 4.5.1 (build)
MacOS 10.15

### Expected Behaviour
Every time I select the menu-item Archi > Preferences,  I see a a dialog box with a clickable list of preferences-groups on the left-hand side : "Canvas Toolkit", "Colours and Fonts"... up until "Validator".

### Actual Behaviour
Each time I return to the Preferences dialog box, all preferences-groups that are above the previously selected preferences-group are gone. This can only be fixed by restarting Archi, altough it seams that by opening the Preferences dialog box the lost options sometimes re-appear automatically.

Error log doesn't show anything relevant.

### Steps to Reproduce the Behaviour
1. select the menu-item Archi > Preferences
2. click on preferences group Diagram
3. click Apply & Close
4. select the menu-item Archi > Preferences
5. The three first preferences groups (Canvas Toolkit et al) are gone.
6. Restart Archi to fix the issue.

[log.txt](https://github.com/archimatetool/archi/files/3783226/log.txt)

**Comment by Phillipus** [comment] 2019-10-29 11:24
I've just tested Archi 4.5.1 on MacOS 10.15 and I can reproduce this. If you type something in the dialog's search text box and then clear the search text that will clear it.

I'll investigate to see if this is an Eclipse problem but, because 10.15 has so many issues, we are currently saying that it is "unsupported".

**Comment by Phillipus** [comment] 2019-10-29 11:35
It's an Eclipse bug, which I've just reported:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=552514

I'll add this as a know issue to the upcoming README file for Archi 4.6.

**Comment by Phillipus** [comment] 2019-10-29 13:45
I've figured out a workaround which effectively resizes the contents of the Preferences dialog window on MacOS 10.15. So no need for the README note. The workaround will be in Archi 4.6.

**Comment by Phillipus** [comment] 2019-10-31 13:41
Sadly, the Eclipse folks seem to have moved the reported issue (and my proposed workaround) to the "not my problem" category.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=552514

**Comment by Phillipus** [comment] 2019-11-11 14:17
Close this one now that 4.6 is released.

**Closed by Phillipus** 2019-11-11 14:17 UTC
