### ISSUE TITLE
jArchi renderViewAsBase64 throws OutOfMemoryError (Java 11.0.5 doesn't allocate heap)

### ISSUE THREAD

**Issue by markbacker** [archimatetool/archi#622] opened 2020-05-13 17:01 UTC
### Version of Archi
Archi-Win64-4.7.0-beta1

### Archi Plug-ins
jArchi plugin version 0.7.2.20200228

### Operating System
Windows 10

### Steps to Reproduce the Behaviour
Rendering a .png image with a scale of 2 or larger throws a 

> java.lang.OutOfMemoryError: Java heap space. 

This happens with the new Archi 4.7.0 beta1 version, no problem with the 4.6 version

1. Select a view with quite a lot of visual elements (a small view with 10 or less elements just worked)
2. Run this script
```
view = selection.filter("archimate-diagram-model").first();
try {

	if (!view) {
		window.alert("Please select a view");
	} else {
		console.log("View is: " + view.name);
		let filename = view.name
		let file = window.promptSaveFile({
			title: "Save to file",
			fileName: filename
		});
		let fileExtension = "PNG"

		for (let scale = 1; scale < 5; scale++) {

			var bytes = $.model.renderViewAsBase64(view, fileExtension, {
				scale: scale,
				margin: scale * 10
			});
			fileWithScale = file + "_" + scale + "." + fileExtension
			console.log("Saved to: " + fileWithScale);
			$.fs.writeFile(fileWithScale, bytes, "BASE64");
		}

	}
}
catch (error) {
	console.log(`${typeof error.stack == 'undefined' ? error : error.stack}`);
}
```
3. The error occurs in the call $.model.renderViewAsBase64.

**Comment by Phillipus** [comment] 2020-05-13 17:20
Thanks for the detailed report and steps to reproduce this. I'm seeing the same thing. Works OK on 4.6 but OOM error on 4.7.

Interestingly if you add the following line to the Archi.ini file (just below `-vmargs`) it is OK:

`-Xmx1024m`

This is strange because without that line Java allocates 25% of memory for the heap which on my machine is 2048mb. So 1024 is actually less.

**Comment by Phillipus** [comment] 2020-05-13 17:27
Another way I can reproduce this is to export to image at 500% size a large-ish view.

The only thing that's really changed is Archi 4.7 is built on Eclipse 4.15.

**Comment by Phillipus** [comment] 2020-05-13 17:46
Actually I found the difference. Archi 4.6 uses Java AdoptOpenJDK 11.0.3 and Archi 4.7 uses AdoptOpenJDK 11.0.5.

I tested Archi 4.7 with 11.03 and it didn't throw the OOM error.

I'll investigate and see what changed in Java.

**Comment by Phillipus** [comment] 2020-05-13 17:50
https://github.com/AdoptOpenJDK/openjdk-support/issues/35

**Comment by Phillipus** [comment] 2020-05-13 17:57
If there is no fix in AdoptOpenJDK I will roll back to 11.03. I don't like specifying a heap size in Archi.ini because when we used to do that, users would run out of memory. By not specifying a heap size Java will attempt to use 25% of memory for the heap.

**Comment by Phillipus** [comment] 2020-05-13 18:02
AdoptOpenJDK 11.0.7 doesn't fix it. I will roll back to 11.0.3

**Comment by jbsarrodie** [comment] 2020-05-13 18:03
You should try with the openJ9 build of AdoptOpenJDK....

**Comment by jbsarrodie** [comment] 2020-05-13 18:03
FWIW, I use openJ9 with my teams without any issues (but didn't test this very specific issue)

**Comment by Phillipus** [comment] 2020-05-13 18:09
> You should try with the openJ9 build of AdoptOpenJDK....

I tried it with 11.0.7 and that does not give the OOM exception.

The only thing I don't like about the openJ9 version is that when it allocates memory on the heap it seems reluctant to shrink (free) it. Using our little heap monitor widget shows that the hotspot JVM will release the allocated memory as soon as it can.

**Comment by Phillipus** [comment] 2020-05-13 18:10
@markbacker For now add `-Xmx2048m` on the line below `-vmargs` in Archi.ini.

**Comment by jbsarrodie** [comment] 2020-05-13 18:15
> The only thing I don't like about the openJ9 version is that when it allocates memory on the heap it seems reluctant to shrink (free) it. Using our little heap monitor widget shows that the hotspot JVM will release the allocated memory as soon as it can.

This makes me think that I recently worked on a script which uses a lot of memory and in some occasions makes Archi hung (and then I have to kill it). I have to check which JVM is used (as said, I usually use openJ9, but I also worked a lot with 4.7 EA using its default JVM. Maybe my issues were also related to hotspot JVM.

Some months ago, I wanted to create a jArchi script to test several uses cases and compare performances and memory consumption between hotspot and openJ9... Maybe time to work on such script.

**Comment by Phillipus** [comment] 2020-05-13 18:36
Reading the original issue (https://github.com/AdoptOpenJDK/openjdk-support/issues/35) I don't think they are in a hurry to fix it.

Options:

- Roll back to HotSpot 11.0.3 (known and tested in Archi 4.6)
- Use OpenJ9 11.0.7 (unknown and untested)

TBH there's little difference between 11.0.3 and later apart from the OOM issue.

**Comment by jbsarrodie** [comment] 2020-05-13 18:45
So I suggest to stick with HotSpot 11.0.3 for Archi 4.7 and start testing OpenJ9 a bit more for next releases.

> unknown and untested

More than 15 people using it with Archi + coArchi + jArchi since summer 2019 ;-)

**Comment by Phillipus** [comment] 2020-05-13 18:46
> More than 15 people using it with Archi + coArchi + jArchi since summer 2019 ;-)

Yeah, but proper testing would have had 16 people using it... ;-)

**Comment by Phillipus** [comment] 2020-05-13 18:48
> So I suggest to stick with HotSpot 11.0.3 for Archi 4.7 and start testing OpenJ9 a bit more for next releases.

I'm going to do that. I could do without any more headaches when we update Eclipse/Java/Libs... ;-)

**Comment by Phillipus** [comment] 2020-05-13 18:53
This comment is interesting:

https://github.com/AdoptOpenJDK/openjdk-support/issues/35#issuecomment-561659760

I tested this and that is the issue.

Add these lines to Archi.ini and it solves the problem:

```
-vm
jre/bin/server
```

Or delete the `jre/bin/client` folder to achieve the same thing.

**Comment by Phillipus** [comment] 2020-05-13 21:34
On Windows, 11.0.3 doesn't have a bin/client folder whereas on 11.0.5 it does. Deleting the bin/client folder on 11.0.5 actually fixes this problem.

**Comment by markbacker** [comment] 2020-05-14 06:00
I have added the lines
```
-vm
jre/bin/server
```
and I can confirm that solves the problem. Thanks!

**Comment by Phillipus** [comment] 2020-05-14 07:16
It's not clear whether the issue is Eclipse's or AdoptOpenJDK. And it seems to be Windows-only.

Eclipse, and Eclipse-base apps like Archi, can run with a given JVM if the JVM is in a local "jre" folder. Eclipse/Archi discovers this folder and uses the JVM. It seems that this "magic" uses the file `jre/bin/server/jvm.dll`.

However, in AdoptOpenJDK versions since 11.0.4 there are two folders, the server one and also, `jre/bin/client/jvm.dll` It seems that Eclipse/Archi is using this last one and the Java Heap is not being set properly.

So, is the bug that Eclipse/Archi should user the `server` one and not the `client` one, or is that AdoptOpenJDK is not setting the heap?

Note that with the latest AdoptOpenJDK versions (14) this is also the case.

So it seems to me that this is not going to be addressed by AdoptOpenJDK, nor by Eclipse, so we have to make a decision of one of the following options (excluding the OpenJ9) version.

- Keep using 11.0.3
- Add a `-Xmx2048m` entry in Archi.ini
- Add a `-vm jre/bin/server` entry in Archi.ini
- Delete the `jre/bin/client` folder in the bundled JRE

**Comment by Phillipus** [comment] 2020-05-14 07:24
For Archi 4.7 I think we should use 11.0.3 and see if the issue gets resolved. If it doesn't we can think about one of the other options. Right now, we should bank on known stability.

**Comment by jbsarrodie** [comment] 2020-05-14 07:31
> So it seems to me that this is not going to be addressed by AdoptOpenJDK, nor by Eclipse, so we have to make a decision of one of the following options (excluding the OpenJ9) version.

I do think the same. I looked at AdoptOpenJDK and this is clearly not a bug in their product, but a side effect of applications assuming there is only one jre provided by the distribution. So I see absolutely no reason for AdoptOpenJDK to fix it.

So the real question are: what's the difference between 'server' and 'client' jre, and which one do we want?

I found this: https://stackoverflow.com/questions/198577/real-differences-between-java-server-and-java-client which provide a bit of context.

That being said: Archi has been shipped with HotSpot server jre for several months and we haad no complains, so if it ain't broke don't fix it... And I don't like deleting part of "standard" software, so I'd go for: Add a `-vm jre/bin/server` entry in Archi.ini

**Comment by Phillipus** [comment] 2020-05-14 07:41
See https://github.com/AdoptOpenJDK/openjdk-installer/issues/137

**Comment by Phillipus** [comment] 2020-05-14 08:05
>  so I'd go for: Add a `-vm jre/bin/server` entry in Archi.ini

The only problem with that is it is possible for an Archi user to _not_ use our bundled JRE.

The way it works now is that if the "jre" folder is present it is used and if not present, then the system JRE is used. Installation of the JRE in the Windows installer is even optional in case a user already has Java 11 installed on their machine.

Having said that, the Mac version has this:

```
-vm
../jre/lib/jli/libjli.dylib
```

So if we did add `-vm jre/bin/server` we should remove the option to not install the JRE in the Windows installer.

**Comment by Phillipus** [comment] 2020-05-14 08:08
But should a user decide not to use the Archi JRE and use their own, say, 11.0.7 version then they will also run into the OOM error.

**Comment by Phillipus** [comment] 2020-05-14 08:10
So we say, use the bundled JRE or there could be problems. This is already the case - Java 14 is available and does not work with Archi (I tried it and there was weird graphical stuff)

**Comment by jbsarrodie** [comment] 2020-05-14 08:55
> So we say, use the bundled JRE or there could be problems.

This seems the best option IMHO.

**Comment by jbsarrodie** [comment] 2020-05-14 08:57
That being said, if you think there is no potential issues with adding a `-Xmx2048m` entry in Archi.ini, we might do both, so we still use the server JVM we provide, and we make sure it should would with another JVM.

**Comment by Phillipus** [comment] 2020-05-14 09:08
I don't like setting the heap size. Ideally we need a minimum of 2gb but if the machine has more, great, use it, particularly when generating images. There are more machines with 16gb these days so all good. However, some people only have 4Gb and so 1gb heap is best.

**Comment by Phillipus** [comment] 2020-05-14 10:44
The change in AdoptOpenJDK 11.0.4 hotspot and greater is actually more fundamental than allocating heap size.

11.0.3 `java -version`:

```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```

11.0.7 `java -version`:

```
C:\Users\Phillipus>java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK Client VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

So by default it now uses the Client VM rather than the Server VM. This might be a big surprise for deployments that, for whatever reason, use the Server VM.

**Comment by Phillipus** [comment] 2020-05-14 12:53
I've release Archi 4.7 beta 2 with 11.0.3 JRE. I don't think 256Mb max heap size will lead to a nice experience. ;-)

**Comment by jbsarrodie** [comment] 2020-05-14 13:28
> This makes me think that I recently worked on a script which uses a lot of memory and in some occasions makes Archi hung (and then I have to kill it). I have to check which JVM is used (as said, I usually use openJ9, but I also worked a lot with 4.7 EA using its default JVM. Maybe my issues were also related to hotspot JVM.

My issues **were** related to this hotspot JVM running out of memory.

**Comment by Phillipus** [comment] 2020-05-14 13:30
> 
> 
> The change in AdoptOpenJDK 11.0.4 hotspot and greater is actually more fundamental than allocating heap size.
> 
> 11.0.3 `java -version`:
> 
> ```
> openjdk version "11.0.3" 2019-04-16
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
> ```
> 
> 11.0.7 `java -version`:
> 
> ```
> openjdk version "11.0.7" 2020-04-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
> OpenJDK Client VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
> ```
> 
> So by default it now uses the Client VM rather than the Server VM. This might be a big surprise for deployments that, for whatever reason, expect to use the Server VM.

I might be wrong. Somehow I got the 32-bit version where it does default to Client. I have to make some new tests now.

**Comment by Phillipus** [comment] 2020-05-14 13:59
This is more likely an Eclipse thing.

See https://github.com/AdoptOpenJDK/openjdk-support/issues/35#issuecomment-628648816

and https://bugs.eclipse.org/bugs/show_bug.cgi?id=553538

It didn't help matters that some of my test were done with a 32-bit version of AdoptOpenJDK which I downloaded by mistake... d'oh!

**Comment by jbsarrodie** [comment] 2020-05-14 14:01
FWIW, I just did a small comparison between HotSpot (server) and OpenJ9 on one of my biggest jArchi scripts, and HotSpot performs twice better than OpenJ9. So that's another argument to stick with HotSpot.

**Comment by Phillipus** [comment] 2020-05-14 14:45
When I tested OpenJ9 on Mac it created some weird folder at the top level, too.

So the issue boils down to this now:

If not specified otherwise, Eclipse and Archi will use the Client VM rather than the Server VM (even though the Server VM is the default). And the Client VM only allocates 256MB of maximum heap space if not otherwise specified in the ini file.

**Comment by markbacker** [comment] 2020-05-14 15:51
Phil, I am impressed how thoroughly you research this issue. Gives me some insight into why Archi is reliable and stable.
Kudos to you!

**Comment by Phillipus** [comment] 2020-05-14 15:53
> Phil, I am impressed how thoroughly you research this issue. Gives me some insight into why Archi is reliable and stable.
Kudos to you!

Cheers, Mark. But it's probably an OCD thing. ;-)

**Comment by markbacker** [comment] 2020-05-14 15:54
So OCD can be a good thing. And also kudos to JB of course!

**Comment by Phillipus** [comment] 2020-05-14 17:05
And the result is that there is agreement that it is an Eclipse issue not an AdoptOpenJDK issue:

https://github.com/AdoptOpenJDK/openjdk-support/issues/35 is closed

https://bugs.eclipse.org/bugs/show_bug.cgi?id=553538 is being looked into.

By shipping a client VM as well as a server VM, AdoptOpenJDK is doing nothing wrong because:

- The default is still the Server VM
- The Client VM does use a smaller max heap size if not specified

and

- Eclipse looks for the first one in the list, because "client" comes before "server" in their list of VMs to check. That is arbitrary.

1-0 to AdoptOpenJDK

**Comment by Phillipus** [comment] 2020-05-15 11:51
After even more research, this is a Windows only issue and related to the way Eclipse looks for client/server VMs.

So the fix for future versions is this line in Archi.ini:

```
-vm 
jre/bin/server
```

**Comment by Phillipus** [comment] 2020-05-18 10:23
Now that we know the deal, I'll close this. Thanks @markbacker for reporting it!

**Closed by Phillipus** 2020-05-18 10:23 UTC
