### ISSUE TITLE
[New Connection Dialog] Show all existing relationships

### ISSUE THREAD

**Issue by HansBosma** [archimatetool/archi#581] opened 2020-02-17 15:37 UTC
When a relationship between concepts already exists, a warning is given and a question asked whether to use the existing relationship. But, in case when more than one relationship of this type already occurs the same question is posed.

It would be nice when the interface signals this, and asks which of the existing relationships to reuse!

**Comment by Phillipus** [comment] 2020-02-17 15:41
Is this a duplicate of #299?

**Comment by HansBosma** [comment] 2020-02-17 15:49
Yes probably. Although in #299 it mentions two 'used by' relations. I am mostly concerned with named relations (flows e.g.) and then want to reuse one specific named relation (so with label) in a new view.

**Comment by Phillipus** [comment] 2020-02-17 15:52
The issue is the same if we generalise it. When creating a new relationship of type x between a and b, If one or more relationships of type x exist show a dialog with all of these. As long as they have been labelled the user will be able to tell which one is which.

**Comment by HansBosma** [comment] 2020-02-17 15:55
Yes, I agree. Then this is indeed a duplicate of #299.

**Comment by Phillipus** [comment] 2020-02-17 15:56
Keep this open for now. I'll look into it.

**Comment by Phillipus** [comment] 2020-02-17 17:11
This might do it.

![newrels](https://user-images.githubusercontent.com/600504/74674076-7fe08e80-51a8-11ea-9cb3-5cb5735d2068.png)

**Comment by Phillipus** [comment] 2020-02-17 17:58
Will be in next version.

**Comment by HansBosma** [comment] 2020-02-18 07:41
Yes perfect!

**Comment by Phillipus** [comment] 2020-02-22 16:45
Closing this as it is implemented for the next version. Please re-open if any issues are found when released,

**Closed by Phillipus** 2020-02-22 16:45 UTC
