### ISSUE TITLE
Palette window goes blank when switching view tabs

### ISSUE THREAD

**Issue by CzechM8** [archimatetool/archi#944] opened 2023-07-05 17:21 UTC
No error log.

### Version of Archi

5.1

### Archi Plug-ins

jArchi
CoArchi
Ecel for Archi
Lightbox for Archi

### Operating System

Mac OS version 13.4.1

### Expected Behaviour

Switching open view tabs should not cause the tools palette window to go blank.

### Actual Behaviour

Switching open view tabs causes the tools palette window to go blank. It will be restored when switching back to the original view tab being viewed OR by hovering the cursor over the Palette window. This does not always happen.

### Steps to Reproduce the Behaviour
1.  Open two view tabs
2.  Switch view tabs
3.
<img width="2560" alt="Screenshot 2023-07-05 at 1 18 12 PM" src="https://github.com/archimatetool/archi/assets/2984074/a1644a57-48cf-43b1-ac57-9478cd056922">
<img width="2560" alt="Screenshot 2023-07-05 at 1 18 22 PM" src="https://github.com/archimatetool/archi/assets/2984074/fad3a9f5-d33c-45b5-b117-7596576872f7">

**Comment by Phillipus** [comment] 2023-07-05 17:28
Hi, thanks for the report.

I can't reproduce this here so any more details would be helpful.

It's likely that this is a tab/window focus issue. I can see in the second screenshot that the Properties tab is showing details for "R&B: Capability View" while the View tab is selected for something else.

If this happens again, try clicking in the View to put the focus on it.

**Comment by Phillipus** [comment] 2023-07-05 17:33
Also, I notice you are using the "Classic" theme. Could you try with the "Light" theme.

**Comment by Phillipus** [comment] 2023-07-05 17:44
> Also, I notice you are using the "Classic" theme. Could you try with the "Light" theme.

I tried using the "Classic" theme and I managed to reproduce it. The contents are not being painted and I think this is a bug in Eclipse's code for the "Classic" theme. That theme is not really supported any more. 

See also https://github.com/archimatetool/archi/issues/767

**Comment by CzechM8** [comment] 2023-07-05 18:09
Ah ha!  The issue disappears with the Light theme!

**Comment by CzechM8** [comment] 2023-07-05 18:10
Yes, I suspected eclipse also.

**Comment by Phillipus** [comment] 2023-07-05 18:11
It's so hard to reproduce this one, and I only managed it twice. I think we'll have to accept it as an obscure Eclipse bug which is unlikely to get fixed.

**Comment by CzechM8** [comment] 2023-07-05 18:30
Phil,

I did experience this issue again using the Light theme, but it happens
MUCH less frequently.

Les

**Comment by Phillipus** [comment] 2023-07-05 18:31
> I did experience this issue again using the Light theme, but it happens
MUCH less frequently.

Interesting. I wonder if it's a Mac issue? I'm finding it hard to get a reproducible set of steps.

**Comment by Phillipus** [comment] 2023-07-05 18:35
And maybe only when using the separate Palette tab?

**Comment by CzechM8** [comment] 2023-07-05 18:51
I can pull it up on my laptop and see what WIndows does.

**Comment by CzechM8** [comment] 2023-07-05 18:53
I combined the visualizer and palette tabs and was still able to reproduce
the issue.

**Comment by Phillipus** [comment] 2023-07-05 18:54
> I combined the visualizer and palette tabs and was still able to reproduce

No, I mean closing the Palette tab so it's part of and combined with a View.

**Comment by CzechM8** [comment] 2023-07-05 19:09
Ah!  That seems to work great. I couldn't even reproduce it with the
classic theme!

**Comment by Phillipus** [comment] 2023-07-06 07:35
I've done more testing.

1. It's not related to the theme. Does it in Light theme.
2. Seems to be Mac only, can't reproduce on Windows

Steps to reproduce:

1. Open the separate Palette tab and move it to the side
2. Open several Views
3. Double-click on a View's tab so it maximises
4. Double-click on the same View's tab so it restores to normal size
5. Click on another View's tab

**Comment by Phillipus** [comment] 2023-07-07 16:48
I have a workaround for this now.

**Comment by CzechM8** [comment] 2023-07-07 18:18
Sweet! Do tell. 🙂 I've moved my palette into the view window and so far,
all is well.

**Comment by CzechM8** [comment] 2023-07-07 18:19
Ah! Just saw the link!

**Comment by Phillipus** [comment] 2023-07-17 09:34
Fixed in Archi 5.1 beta 2.

**Closed** 2023-07-25 18:31 UTC
