### ISSUE TITLE
[Bug] Problem with Line to Line connection in import of exchange file

### ISSUE THREAD

**Issue by FransFaase** [archimatetool/archi#276] opened 2017-09-20 12:14 UTC
### Version of Archi, Operating System

Archi 4.0.3

### Expected Behaviour
When performing an import of an ArchiMate Exchange file, connection of type Line to a connection of type Line should end at that connection.

### Actual Behaviour
The particular connection ends near the top corner of the diagram.

### Steps to Reproduce the Behaviour
1. Import [Graphics.txt](https://github.com/archimatetool/archi/files/1317671/Graphics.txt) (Change extentions from txt to xml)

2. Compare with [Graphics.pdf](https://github.com/archimatetool/archi/files/1317667/Graphics.pdf)

**Comment by Phillipus** [comment] 2017-09-20 12:27
This is a non-ArchiMate "Line" type connection I think. This raises an interesting problem - in Archi these "Line" connections can only connect from Notes to other Notes or to Element Nodes. Other tools might also implement their own Line connection rules that do not include connection->connection.

**Comment by Phillipus** [comment] 2017-09-20 12:40
The problem is that there is an in-built restriction in Archi that says "diagram line connections can only connect between nodes of a certain type, but not to other connections". This is not to say that this restriction cannot be changed, but other tools might have similar restrictions.

And also this might be seen as a case where the exchange format is dictating tools' behaviour for a non-ArchiMate graphical feature.

**Comment by FransFaase** [comment] 2017-09-20 12:51
Hi Phil,
I understand your point. I noticed some more issues where Archi ignores information from the Exchange File,
but I felt I had to report this, because I feared that it might crash Archi if you start manipulating those connections
that are not valid in Archi. I think it is not a big issue if you ignore these line connections to line connections
as long as they are not supported by Archi.
In the past weeks, I have been working on the AEFF 3.0 import and export functions. The export function is
not yet available, but will be available in the next release, probably BiZZdesign Enterprise Studio 3.0.1.
I also have uploaded some XML files to the SVN repository for interoperability tested (if needed).
Kind regards,
Frans
----Origineel Bericht----
Van : notifications@github.com
Datum : 20/09/2017 14:41
Aan : archi@noreply.github.com
Cc : faase009@planet.nl, author@noreply.github.com
Onderwerp : Re: [archimatetool/archi] [Bug] Problem with Line to Line connection in import of exchange file (#276)
The problem is that there is an in-built restriction in Archi that says "diagram line connections can only connect between nodes of a certain type, but not to other connections". This is not to say that this restriction cannot be changed, but other tools might have similar restrictions.
And also this might be seen as a case where the exchange format is dictating tools' behaviour for a non-ArchiMate graphical feature.

**Comment by Phillipus** [comment] 2017-09-20 13:07
Hi Frans, yes I agree. I'll take a look at handling the situation more gracefully.

**Comment by Phillipus** [comment] 2017-09-20 14:13
I've committed a fix to ignore line connection -> connection for now:

https://github.com/archimatetool/OpenGroupXMLExchange/commit/c6fb88fac766772e3b28277c32f4c2be54202b3c

It's better than the current implementation.

**Comment by Phillipus** [comment] 2017-09-20 14:15
Closing this. Thanks for reporting. Please feel free to re-open if required.

I've noted the issue as something that should be allowed if Archi allows line connection -> connection for non-ArchiMate connections

**Closed by Phillipus** 2017-09-20 14:15 UTC
