### ISSUE TITLE
[feature request] create nesting relationship when pasting

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#819] opened 2022-02-15 07:36 UTC
Archi prompts to create a nesting relationship when one element is dragged on top of another but not when it is pasted there which allows one to create a diagram which visually implies a relationship but actually doesn't have one. I'd like it to prompt for nesting when pasting too.

**Comment by Phillipus** [comment] 2022-02-15 08:22
This is a duplicate of #745

**Closed by Phillipus** 2022-02-15 08:22 UTC
