### ISSUE TITLE
Tooltip doesn't snap to only the monitor used by Archi.

### ISSUE THREAD

**Issue by Truesh00ter** [archimatetool/archi#635] opened 2020-05-30 10:52 UTC
### Version of Archi
4.6.0

### Archi Plug-ins
None that I know of.

### Operating System
Windows 10, 1909 Build 18363.836

### Expected Behaviour
Tooltip should snap on the screen that is used for Archi.

### Actual Behaviour
Tooltips from 'Palette' do not snap and can be split over multiple screens.

### Steps to Reproduce the Behaviour
1. Hover over something in the 'palette' with a long description. 
2. Have a second monitor to the right of Archi.

I'm a bit in between if this is a bug or a feature.
See below two screenshots, the minimized properties bar does snap onto the correct monitor, the palette tooltips do not. The black is my wallpaper of the second screen, due to bezels and monitor placement this is something I would like to see fixed. In practical sense the text is split on the 'g' and there is like two cm (about an inch) space until the next letter can be read. The screenshots obviously do not show the results on the used monitors.

![image](https://user-images.githubusercontent.com/17280249/83326418-293d2300-a274-11ea-8b21-854fc797fc2b.png)
![image](https://user-images.githubusercontent.com/17280249/83326422-2e01d700-a274-11ea-80d2-11b8072d2590.png)

**Comment by Phillipus** [comment] 2020-05-30 11:16
The placement of tooltips is part of the underlying Eclipse frameworks (SWT and/or Draw2d). Because of this we can't fix this, I'm afraid.

You could open an issue on Eclipse's bug tracker, but you'd have to provide a simple reproducible test snippet (I can't do this as I don't have dual monitors)

I'll close this because there's nothing we can do about it.

**Closed by Phillipus** 2020-05-30 11:16 UTC

**Comment by Phillipus** [comment] 2020-05-30 11:23
And here is the Eclipse GEF/Draw2d bug report:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=364127

Reported in 2011. It's not going to get fixed. As the reporter says, one would have to hack the a big portion of Draw2d to get at the `ToolTipHelper` class.

**Comment by Truesh00ter** [comment] 2020-05-30 11:33
Thanks for looking into it!
