### ISSUE TITLE
NPE when switching between views with "Link to View" enabled and Model Tree closed

### ISSUE THREAD

**Issue by timhale7** [archimatetool/archi#436] opened 2019-01-31 18:10 UTC
Bug report - null pointer exception

attaching configuration file and error log snippet

### Version of Archi, Operating System
help/about says Archi Version 4.3.1  Build 2019-01281101 - but the download package says 4.3.2
Windows 10

I am using the Specialization plug-in, and its drill-down feature to jump to another view when I double-click an object .  This would be the current plug-in version, as I downloaded it earlier this week.
https://github.com/archi-contribs/specialization-plugin

### Steps to Reproduce the Behaviour
1. I have one view dedicated to navigation - I happened to use "work package" objects for this, since I don't use them in the model otherwise.  I have one object per view, with the drill-down property linked to one of the views.  19 views in all.
2.  I have one "work package" object on each of the 19 views with its drill down property set to the navigation page.  trying to make it easy for the novice user to navigate around the models.
3.  When I jump to a model via a double-click on the object, and then close the eclipse page via the "x'.  I get the null pointer exception - sometimes.  I also get it - sometimes - when I jump from one eclipse tab to another.  It ONLY occurs when I've changing between views, never when I'm doing basic modeling functions on a view.  Once it starts to occur, then it seems to occur every time I switch views.

[null pointer exception - configuration.txt](https://github.com/archimatetool/archi/files/2818497/null.pointer.exception.-.configuration.txt)

[null pointer exception - error log.txt](https://github.com/archimatetool/archi/files/2818498/null.pointer.exception.-.error.log.txt)

**Comment by Phillipus** [comment] 2019-01-31 18:14
If this is caused by the Specialization plug-in, could you report it on that Issues tracker? Herve can take a look at it, as it's his code.

https://github.com/archi-contribs/specialization-plugin/issues

**Comment by herve91** [comment] 2019-01-31 18:17
yes, please open an issue on my plugin's page and I will definitely have a look.

Best regards
Hervé

**Comment by timhale7** [comment] 2019-01-31 18:19
done. thanks for the speedy reply.

**Comment by Phillipus** [comment] 2019-01-31 18:22
Actually, I can reproduce this without the plugin. It's my bug.

**Comment by Phillipus** [comment] 2019-01-31 18:34
Please delete the big report in the other repo. The problem is cause if you have "Link to View" enabled and the Model Tree is closed. As a workaround, turn "Link to View" off and/or keep the Tree open.

**Comment by timhale7** [comment] 2019-01-31 19:09
yes, that would be the condition that triggers this.  
With the drill-down navigation option, I tend to keep the Model Tree closed and just keep the object palette open to maximize monitor space dedicated to the model.

**Comment by timhale7** [comment] 2019-01-31 19:13
It doesn’t appear that I have authorization to delete. Only the repo owner can delete???

**Comment by Phillipus** [comment] 2019-01-31 19:18
You can simply close the issue. I've done it.

**Comment by Phillipus** [comment] 2019-01-31 19:43
This bug appeared in June 2014. I forgot to check tree was not null.

Working on a refactor to fix this and optimise the selection synchroniser...

**Comment by Phillipus** [comment] 2019-02-12 12:07
Fixed in Archi 4.3.3. Feel free to re-open or create another issue if there's still a problem.

**Closed by Phillipus** 2019-02-12 12:07 UTC

**Comment by timhale7** [comment] 2019-02-13 14:55
Seems to have fixed the problem.  Thanks!

**Comment by timhale7** [comment] 2019-02-13 17:18
Phil,
one different behavior I notice today is that when I have the model tree
open, and I click on an object on the canvas, it no longer brings that
object into focus in the model tree.
Prior to applying the latest version, it would highlight the selected
object in the model tree, and move the model tree view up or down so that
the selected object was visible on screen.

I'm not seeing the object being selected in the model tree now.  So there's
no model tree movement as there was in the 4.3.2 version.
This was a handy behavior for quickly finding the object in the tree.

Tim

**Comment by Phillipus** [comment] 2019-02-13 17:21
@timhale7 I can't reproduce this. Are you sure you have the "Link to View" button on?

**Comment by Phillipus** [comment] 2019-02-13 17:40
@jbsarrodie Can you confirm this is working?

**Comment by timhale7** [comment] 2019-02-13 18:08
my bad.  I did not have "link to view" turned on.
Apologies for the rabbit trail.
Tim

**Comment by Phillipus** [comment] 2019-02-13 21:01
> my bad. I did not have "link to view" turned on.
> Apologies for the rabbit trail.
> Tim

No problem. BTW - thanks for becoming a Patreon. 👍
