### ISSUE TITLE
Cannot move a model fragment from one view to another

### ISSUE THREAD

**Issue by stefjoosten** [archimatetool/archi#712] opened 2021-03-16 06:07 UTC
### Version of Archi
I am using Archi vs. 4.8.0

### Archi Plug-ins
I have jArchi installed

### Operating System
I am on MacOS Cataline vs. 10.15.7

### Expected Behaviour
I want to move a model fragment from one view to another by cut and paste (^X^V). This worked fine in Archi vs. 4.6.0.

### Actual Behaviour
In the resulting (pasted) fragment,  the names of objects are marked with " (copy)". I would expect that behavior from copy & paste (^C^V), not from cut & paste (^X^V). So in this new version of Archi, how can I move a model fragment?

### Steps to Reproduce the Behaviour
1. Open an arbitrary view in an arbitrary ArchiMate model.
2. Select a number of elements (e.g. by ^A).
3. press ^X; the code fragment vanishes to the clipboard.
4. create a new view
5. in this new view, paste the fragment. The objects are now marked with " (copy)".

**Comment by Phillipus** [comment] 2021-03-16 10:18
Nothing has changed in this aspect between 4.6 .0 and 4.8.0 (BTW the latest version is 4.8.1). When I follow your steps I don't see the " (copy)" in the pasted elements. This should only happen if the elements already exist in the target View. There is also a "Paste Special" option (explained in the User Guide.)

**Comment by Phillipus** [comment] 2021-03-23 15:34
Closing as cannot reproduce.

**Closed by Phillipus** 2021-03-23 15:34 UTC
