### ISSUE TITLE
With selected objects on the view "Copy As Image to Clipboard" command copies all the view object

### ISSUE THREAD

**Issue by startsevsa** [archimatetool/archi#676] opened 2020-10-05 13:19 UTC
![image](https://user-images.githubusercontent.com/14212283/95080761-047d1e80-0732-11eb-85ab-bfac574b5696.png)

### Version of Archi
4.7.1

### Archi Plug-ins
Archi Model Repository
Archi Scripting
Database export/import

### Operating System
Windows 10

### Expected Behaviour
Copy and paste as image only selected elements with nested objects

### Actual Behaviour
All the view is copied in the clipboard as image.
But when using with "Copy" command - only selected objects are copied. 

### Steps to Reproduce the Behaviour
1. Select a group of elements (not all) on the view
2. Chose "Copy As Image to Clipboard"
3. Open any other program (MS Office & etc.) and paste image
Result: the whole view is pasted, not only selected elements

**Comment by Phillipus** [comment] 2020-10-05 13:25
This is the intended behaviour. The image is created from the whole view.

There is a request for this - https://github.com/archimatetool/archi/issues/80

**Comment by Phillipus** [comment] 2020-10-05 13:26
I'll close this, as #80 covers the issue.

**Closed by Phillipus** 2020-10-05 13:26 UTC
