### ISSUE TITLE
Corrupted Grafico files

### ISSUE THREAD

**Issue by stefjoosten** [archimatetool/archi#152] opened 2016-10-03 07:53 UTC
Grafico is, if I'm informed correctly, meant for multi-user support with Git. In principle, this works fine. Except in some cases.... In our project, we have experienced three times that Grafico-files were corrupted. This issue documents the most recent occurence.

An Archimate-repository of Bart den Dulk (bdendulk) contains [an example](https://github.com/bdendulk/NVWA_CA_BLIK/commit/6b9b0e708c3d6bfdccee8b265b33bce210e31774) of a corrupted Archimate repository.
Loading it in Archi by means of a Grafico-import goes well.
It can then be inspected and changes as any other Archimate-repo.
However, saving the (unchanged) model as an ordinary Archimate-repo yields the following error:
 
![image](https://cloud.githubusercontent.com/assets/275768/19030027/64d0ff7c-894b-11e6-9f83-e3b14c0be475.png)

# Analysis
1. It seems that the example contains 4 violations of a system invariant of Archi. Maybe Archi does not check all of its system invariants when importing from Grafico. I would expect a corrupted file to be rejected when it is imported.
2. In commit ["Herstel actie 4 orphaned relaties"](https://github.com/bdendulk/NVWA_CA_BLIK/commit/1c79752da5a232772fdf85a388e862fe91b54556) @bdendulk has fixed the problem by hand. The difference between this commit and the original gives helpful symptoms of the problems. Bart's fix is consistent with the error message shown above.

# Diagnosis
1. It seems to me that Archi should be more particular in guarding its system invariants.
2. The question how the Grafico input got corrupted needs to be answered as well. For now, we can only guess. One (and the only) guess is that a commit in Git was performed before Archi was done saving the model to Grafico. There is no experimental validation of this guess yet.

**Comment by Phillipus** [comment] 2016-10-03 09:59
> Maybe Archi does not check all of its system invariants when importing from Grafico.

Archi code cannot check for this if the issue is in the plug-in code.

As this an issue with the Grafico plug-in could you open the issue for that project, please?

https://github.com/archi-contribs/archi-grafico-plugin/issues

**Comment by jbsarrodie** [comment] 2016-10-03 18:04
I've copied this issue into [GRAFICO repository](https://github.com/archi-contribs/archi-grafico-plugin/issues/3). Closing this one.

**Closed by jbsarrodie** 2016-10-03 18:04 UTC
