### ISSUE TITLE
[Feature Request] Changing type of element

### ISSUE THREAD

**Issue by mdvadim** [archimatetool/archi#265] opened 2017-08-24 06:09 UTC
Hi,
I think it would be useful to be able to change the type of an element on the diagram. Inserting a new type and deleting the old one is not difficult, but it is difficult to restore all links on a specific view and arrange them in the same order.
For example, I Like to change type Business Role with Stakeholder:
![default](https://user-images.githubusercontent.com/29094130/29651644-e95d0df0-88cb-11e7-94f5-f37b80069ab5.png)

**Comment by Phillipus** [comment] 2017-08-24 09:37
The problem is that a different element can have different relationship rules. Some existing relationships may become invalid with a new element type.

**Comment by jbsarrodie** [comment] 2017-08-24 11:25
We've had similar discussion in the past. Having some need for it too and having taken the time to think about it I would suggest the following behavior:
* A user asks to change the type of an element
* A dialog allows user to choose the new type and what should happen to relationships between:
  * keep allowed relationship as they are (**but warn that this could leave to different meaning**) and convert disallowed relationships to association, or
  * convert all relationships to associations
* Conversion is done and (if needed can be undone)

It should also be possible to change the type of a relationship which should be easier to manage as either the new type is allowed or not (note that relationship to/from junctions should be check slightly differently).

**Comment by mdvadim** [comment] 2017-08-24 13:37
@Phillipus Yes I see. 
@jbsarrodie I wanted to suggest same decision like your first - to change only the disallowed relationship to association.
To be able to change the type of relationship is going on my expectations.
:-)

**Comment by jbsarrodie** [comment] 2017-08-24 13:49
>I wanted to suggest same decision like your first - to change only the disallowed relationship to association.

I think most users want the same **without understanding the real impact on meaning**.

Let's take an example...

If we have this:
![image](https://user-images.githubusercontent.com/5757396/29669139-c980a6f6-88e2-11e7-85ca-7d509bce88a1.png)

...and a user wants to replace the Application Service by an Application Function, if we keep allowed relationship, this we lead to:
![image](https://user-images.githubusercontent.com/5757396/29669258-1d913f12-88e3-11e7-80f4-6dc543e49335.png)

But this is absolutly not the same meaning. Here the realization is a derived relationship that stands for something like:
![image](https://user-images.githubusercontent.com/5757396/29669326-5a417cba-88e3-11e7-8dd9-4de6b793365c.png)

While the indended "convertion" should be:
![image](https://user-images.githubusercontent.com/5757396/29669360-74ea45ba-88e3-11e7-89f1-71c1543e628d.png)

That's something that is not easy to understand by beginners (and unfortunately by lot's of people). So if  some relationships that are not on the view but exist in the model have their meaning impacted, I guess that model will soon been screwed.

**Comment by mdvadim** [comment] 2017-08-24 17:06
Well ... well ... these are already nuances that are not yet available to me. I certainly try to establish a relationship appropriate to the name of the situation, but in fact I do not do it very carefully. Sometimes I want to establish a relationship of one type, logically it seems to me right, but Archi gives me only an association and I'm surprised.

**Comment by jbsarrodie** [comment] 2017-08-24 20:24
>Sometimes I want to establish a relationship of one type, logically it seems to me right

That's the whole point that few people get (at least at the begining): relationships have no real meaning by themselves. In other modelling language they act like a verb to express behavior between two elements, but in ArchiMate the verbs are the behavioral elements themselves (function/process), no the relationships!

If this is unclear to you, this means that it is time for you to read the best book about ArchiMate: "[Mastering ArchiMate](https://masteringarchimate.com/mastering-archimate-edition-ii/)" by Gerben Wierda.

**Comment by mennolodder** [comment] 2017-10-30 12:20
I would also find this very useful. Especially because people don't understand relations and element types all that well, changing is something that happens with renewed insight about how archi models things, and with added completeness of the modelling.

I also see this as being useful for changing relations. While they are less work to replace, they still  can have several properties that can be kept. Also swapping the direction would be a useful thing.

**Comment by samperd** [comment] 2018-12-17 13:58
Hey Folks,

I would find this useful from potentially a different perspective. 

As a systems architect learning Archi, Archimate and TOGAF through real application.
I want a modeling system that is flexible enough to handle my many fals starts or model revisions by allowing me to re-cast (aka change) object types
So that I don't loose all the great content and attributes assigned to the original object.

NB:
* The one concession I would make is that for a first iteration I don't mind if all relationships are blown away.
* A second iteration could popup a dialogue to allow you to export ONLY the old object and its relationships so I can have a reference for re-building relationships.
* Alternatively I would like to make a copy of an object, re-cast it is a new object type with relationships removed. This way I maintain the content, and can then rebuild appropriate relationships of the the new object and set an attribute in the old object where "status"=depricated. This would further allow me to maintain old relationships knowing they will need to be re-mapped.

For me the key thing is to be be able to change object types, what ever else causes barriers to making that happen can be de-scoped for now.

Just another perspective.

Resource:
I believe that Sparx EA has this function. I seem to recall they employe a TYPE / SUB-Type architecture. Can this concept help.?

**Comment by jbsarrodie** [comment] 2018-12-17 19:14
This is now possible through [jArchi](https://github.com/archimatetool/archi-scripting-plugin/), the new script plugin.

A potential implementation would use [.isAllowedRelationship](https://github.com/archimatetool/archi-scripting-plugin/wiki/Model-Functions#isallowedrelationship) to check if relationships are still valid, and then [.type](https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-Object#type) to change relationships and element type.

I don't have created such script yet. If you write it by ourself, I would suggest to [share it](https://github.com/archimatetool/archi-scripting-plugin/wiki/Community-shared-scripts).

Closing this issue (but will happily update it when someone will contributed such script).

**Closed by jbsarrodie** 2018-12-17 19:14 UTC

**Comment by stefankroes** [comment] 2019-10-02 07:00
Hi,

As someone just getting to grips with the Archimate language, I really miss this feature. Trying to build a model for an existing architecture, I'm forced to revisit decision about the types of elements I use to model things all the time. Having to manually transfer name, documentation, properties and relationships in those situations becomes really tedious.

Right now *I'm just manually updating the xml file and restarting Archi* to get around this. This works well but is far from convenient. Highlighting because it may be a temporary solution to others as well.

Don't get me wrong, I fully appreciate the complexities where certain relationships may no longer apply or have a different meaning. But I feel a warning about meaning and casting to simple association where no longer applicable would be preferable over not having this functionality at all.

Just my two cents. I hope you'll consider reopening.

**Comment by jbsarrodie** [comment] 2019-10-02 14:19
Hi,

As described previously, this is supported through jArchi, and as such will not be implemented in Archi itself.

As the script might not be trivial if we want it to take several edge cases into account, I'll soon share mine.

**Comment by stefankroes** [comment] 2019-10-03 06:38
I know, but I decided to comment anyway because:

1. jArchi is not publicly available at this point.
2. Having to load and run a custom script to change an element type sounds very inconvenient, especially for beginners that need this functionality most.

Just my opinion. I'm guessing now that this won't be reopened.

**Comment by Phillipus** [comment] 2019-10-03 06:45
> jArchi is not publicly available at this point.

Yes it is. https://github.com/archimatetool/archi-scripting-plugin
The compiled version build with added examples is given to donaters as a thank-you.

> sounds very inconvenient,

Not as inconvenient as the several days work that I would personally have to devote to implement this feature. Even though Archi is apparently "open source" we can translate every feature request into concrete reality - "When will Phil devote several days of his life (for free) to implement this feature that our company needs right now?" Multiply that by all the feature requests here. ;-)

**Comment by jbsarrodie** [comment] 2019-10-03 06:46
jArchi is publicily available and opensource, but people have to complie it themselve first (really easy) or donate at least 1$ to get a precompiled version. I don't think this is a big deal for anyone.

Running a script can be done through a contextual menu. Mine have multilevels menu : Script > Change type > layer_name > concept_type

I see no need to develop this again in Archi and duplicate code. 

But, hey, Archi is opensource so you can work on it and send a pull request ;-)

**Comment by Phillipus** [comment] 2019-10-03 06:48
> I don't think this is a big deal for anyone.

It turns out that even paying $1 is way too much for some who sign up to Patreon, get the plugin and then leave Patreon the next day...

**Comment by Phillipus** [comment] 2019-10-03 06:58
Having had my moan now, and having said that... ;-)

Because of the way that the data model is written each element is backed by a Java class that has to be replaced with another one and all connections and views updated. It's a bit complicated, expecially with each action having to be put on the Undo Stack. In hindsight I would have done it differently - one element class with a "type" attribute, but maybe that would be in a completely revised version of Archi.

The jArchi implementation of this is also complicated. See https://github.com/archimatetool/archi-scripting-plugin/blob/master/com.archimatetool.script/src/com/archimatetool/script/dom/model/ArchimateElementProxy.java

Translating that into native Java for Archi would take a while. It's a case of finding several days to do it.

BTW @stefankroes thanks for signing up to Patreon!

**Comment by stefankroes** [comment] 2019-10-03 07:00
As I said; just my opinion to with as you please. If it helps any:

1. Even though I'm still evaluating the tool, I just signed up with Patreon.
2. I do know about the thankless reality of open source development: https://github.com/stefankroes/ancestry

Have a great day!

**Comment by Phillipus** [comment] 2019-10-03 07:01
@stefankroes Cheers.

Wasn't really aimed at you personally. I have to moan sometimes. ;-)
