### ISSUE TITLE
Exception during saving model

### ISSUE THREAD

**Issue by micwic** [archimatetool/archi#630] opened 2020-05-24 10:41 UTC
### Version of Archi

com.archimatetool.editor.buildid=202004150922
com.archimatetool.editor.versionid=4.7.0

### Archi Plug-ins

![Archi-exception](https://user-images.githubusercontent.com/6366517/82751822-411b2f80-9dba-11ea-825c-68b453f21d4b.png)
![Archi-exception](https://user-images.githubusercontent.com/6366517/82751831-52643c00-9dba-11ea-9a0f-eab429e30ecd.png)

### Operating System

W10 Pro Version 1903

### Expected Behaviour

Saving model

### Actual Behaviour

Exception

### Steps to Reproduce the Behaviour
1. Not known
[Archi-Exception-log.txt](https://github.com/archimatetool/archi/files/4673302/Archi-Exception-log.txt)

2.
3.

**Comment by Phillipus** [comment] 2020-05-24 10:45
The model has somehow got corrupted. This can happen under some circumstances with coArchi.

**Comment by micwic** [comment] 2020-05-24 10:47
I think I know the reason of the loop.
I created a grouping that encapsulate a link to a view and associated the grouping with a flow between to application component. In the encapsulated view, I detailed the flow (that is a complex interface between two systems). After putting elements in tat view I decided to put them inside the grouping. That reates a recursive loop I think.

**Comment by micwic** [comment] 2020-05-24 10:55
I rolled back to last commit (only one hour lost).
I will try reproducing the error in a dummy model.

**Comment by Phillipus** [comment] 2020-05-24 11:21
It could be caused by this https://github.com/archimatetool/archi-modelrepository-plugin/issues/136

**Comment by micwic** [comment] 2020-05-25 05:17
I don't think so the view is a complete new view.
I think a created a circular reference in a grouping by using it like that :
1) created two application components in a new view
2) created a flow between the two components
3) added a grouping in the model
4) putted a link to a new other view inside the grouping
5) putted a relationship between the grouping and the flow
6) in the new other view : reused the two components and added more detailded components and behavior (the flow between the two components comes automatically)
7) putted the grouping in the model
8) resized the grouping and putted the elements of the view into (BANG), including the flow associated with itself (I'm able to create a circular relationship)

**Comment by Phillipus** [comment] 2020-05-25 07:37
I tried to follow these steps but some are not clear to me. Could you simplify them?

**Comment by Phillipus** [comment] 2020-06-17 16:05
I'll close this as I think it really is a result of archimatetool/archi-modelrepository-plugin#136

**Closed by Phillipus** 2020-06-17 16:05 UTC
