### ISSUE TITLE
Importing a CSV with '&'s in the name/ID works but you can't reload the model again

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#142] opened 2016-05-04 12:48 UTC
When you import a CSV with '&'s in the name/ID, this works and you can save the model but Archi won't reload it then next time you open it.

e.g.     <element xsi:type="archimate:AssignmentRelationship" id="f9683975" source="LocationID-Global" target="ServiceID175-Identity & Access Management-Other-"/>

causes this error trace: 

![ampersand error1](https://cloud.githubusercontent.com/assets/6101736/15014547/a3d8f542-11d4-11e6-8993-9cf7afaa2bcb.png)

The workaround was to open the .archimate file in a text editor (Visual Studio) and search & replace for all " & " and change them to " and ".

Proper fix: Archi should be encoding and decoding all strings that might have this problem during Save and Open.

Michael Herman (Toronto)

**Comment by Phillipus** [comment] 2016-05-04 13:36
Hi. Are you having problems with "$" or "&" characters?

**Comment by mwherman2000** [comment] 2016-05-04 13:37
& (ampersands)

**Comment by Phillipus** [comment] 2016-05-04 13:51
I made a test file like this:

**Comment by Phillipus** [comment] 2016-05-04 13:54
I made a test CSV file:

"ID","Type","Name","Documentation"
"11f5304f","ArchimateModel","Archisurance & Stuff","An example of a fictional Insurance company."
"4&5","BusinessActor","Archisurance & More Stuff",""

I imported it into a new empty model, saved it, closed it and re-opened it. All was OK.

Do you have a simple test case where I can reproduce the problem? Please note that IDs should be well formed alphanumeric identifiers with no special characters.

**Comment by mwherman2000** [comment] 2016-05-04 14:01
Some of the text from original posting is not being displayed ...it's a relationship tag that Archi is failing on.  After the import, a relationship is created and saved.  It won't reload.

**Comment by mwherman2000** [comment] 2016-05-04 14:03
Let’s see if the email interface to GitHub will escape a tag properly:

e.g.     <element xsi:type="archimate:AssignmentRelationship" id="f9683975" source="LocationID-Global" target="ServiceID175-Identity & Access Management-Other-"/>

This is the problem ‘&’

**Comment by Phillipus** [comment] 2016-05-04 14:03
It would help me if you could supply a simple test case. As it is, I'm shooting in the dark. :-)

**Comment by mwherman2000** [comment] 2016-05-04 14:05
See above.  I don't have a simple case.  My production .archimate file is 1900 lines long and I'm totally blocked (it won't load into Archi) until I find, search and replace every issue this morning.

**Comment by Phillipus** [comment] 2016-05-04 14:08
Looking at that example I would advise you to not use IDs like that in your source CSV files. Use simple alphanumeric characters eg "id-101", "7ty6". Perhaps this should be made clearer in the documentation.

**Comment by mwherman2000** [comment] 2016-05-04 14:11
Perhaps but as a Principle: Anything Archi can save is needs to reliably open and read back.

This is a hard Principal.    Documentation is a poor workaround for this.

**Comment by Phillipus** [comment] 2016-05-04 14:16
> Documentation is a poor workaround for this.

Poor or not, this is how it works.

**Comment by mwherman2000** [comment] 2016-05-04 14:19
I think Archi escapes/encodes the &'s every else.  It's bug they they aren't being encoded in the relationship elements, n'est pas?

**Comment by Phillipus** [comment] 2016-05-04 14:30
Ideally, IDs in all cases should follow the guidance as seen here http://www.datypic.com/sc/xsd/t-xsd_ID.html

"it must start with a letter or underscore, and can only contain letters, digits, underscores, hyphens, and periods."

Although Archi IDs can start with numbers too.

I could take a look at the CSV code and add some checks to check for this on input but right now I don't have the time or the inclination to do that (getting rather old and tired of working for free and providing unpaid support for those who do make money off of Archi), so documentation will have to do for now.

:-)

**Comment by mwherman2000** [comment] 2016-05-04 14:35
I think the issue is simpler: some places in the .archimate file, Archi encodes &s and some places it doesn’t (e.g. relationship tags like this one):

e.g. <element xsi:type="archimate:AssignmentRelationship" id="f9683975" source="LocationID-Global" target="ServiceID175-Identity & Access Management-Other-"/>

**Comment by jbsarrodie** [comment] 2016-05-04 14:41
Well, in fact Archi does nothing like that: the .archimate file is generated using standard features of Eclipse framework which itself decide what to encode. As the Id should (by design) follow the guidance of http://www.datypic.com/sc/xsd/t-xsd_ID.html Eclipse framework doesn't encode it.

The issue here is that the CSV plugin work at a low level and insert whatever you want in the Id field. The idea when creating this plugin was to allow such things to allow power user to do some "magic" if needed.

I think asof now the best answer is Phil's one related to documentation and this might be addressed in another version someday.

Regards,

JB

**Comment by Phillipus** [comment] 2016-05-04 14:43
Archi encoding "&" or not encoding "&" is a side-effect / by product. The real issue is that there is no check on IDs when importing CSV. These characters should therefore not be used. Until a check is in place, "best practice" and common sense should be used.

**Comment by mwherman2000** [comment] 2016-05-04 14:48
Spaces in imported IDs are another issue.  I’ve reported it separately.

**Comment by mwherman2000** [comment] 2016-05-04 14:49
Eclipse framework or no Eclipse framework …  It’s not acceptable (to most people) for an application to create files that it later refuses the read.  It is an irrefutable Principal.

**Comment by Phillipus** [comment] 2016-05-04 14:53
> Spaces in imported IDs are another issue. I’ve reported it separately.

Please don't use spaces

> Eclipse framework or no Eclipse framework … It’s not acceptable (to most people) for an application to create files that it later refuses the read. It is an irrefutable Principal.

I don't give a fig about your "irrefutable Principals".

The issue is closed.

**Closed by Phillipus** 2016-05-04 14:53 UTC
