### ISSUE TITLE
Wrong sorting order in models tree

### ISSUE THREAD

**Issue by Sonique** [archimatetool/archi#1054] opened 2024-07-03 08:39 UTC
Follow up for https://github.com/archimatetool/archi/issues/1051

### Version of Archi
5.2.0.202311011021 silicon mac
### Archi Plug-ins
yep

### Operating System
mac silicon

### Expected Behaviour
alphanumeric sorting

### Actual Behaviour
character sorting

### Steps to Reproduce the Behaviour
1. create folders with numerals in naming like folder-15 folder-100 
2. look up in tree
3. folder 100 will be first

<img width="129" alt="image" src="https://github.com/archimatetool/archi/assets/662904/a65fa834-7868-4c15-a1d1-0ae7a7c9987c">

So how can it be changed? Because it's terrible behaviour for sorting, it's not usable at all, maybe only for Wittgenstein Tractatus table of content is good, but not for other cases. Digital sequences should be compared as numbers not as literals one by one. 

More over most editors sort in the right way.

Look for example on Intellij Idea on same system

<img width="255" alt="image" src="https://github.com/archimatetool/archi/assets/662904/77377ba4-4b85-4a71-afa3-97316b9f742b">

So I see it more as bug then expected behaviour

**Comment by Phillipus** [comment] 2024-07-03 08:45
Duplicate of #1051. Closing.

**Closed by Phillipus** 2024-07-03 08:45 UTC

**Comment by Sonique** [comment] 2024-07-03 08:56
@Phillipus even other IDE or editor engines not an argument?
