### ISSUE TITLE
Object name disappears 

### ISSUE THREAD

**Issue by Lateralist** [archimatetool/archi#564] opened 2019-11-26 17:35 UTC
Hello Archi team. 

I should point out before submitting this issue - very very pleased with Archi, this is the first issue I have had with the tool. Really appreciate the work ! 

To the issue - all was working well before 4.6. I have the specialization plug-in installed for the object drill-down function (very useful). When drilling down (and no editing taking place), I review the drilled "to" view and then return by closing the tab and the object i clicked on, the name has disappeared. Really odd.  

Archi Error Log 
[191126 Object Name Disappears.txt](https://github.com/archimatetool/archi/files/3893220/191126.Object.Name.Disappears.txt)

*.archimate - not possible to include without cleansing

### Version of Archi, Operating System
Archi 4.6.0; Windows 10

### Expected Behaviour
Object name remains unchanged unless edited by user

### Actual Behaviour
Clicking on an object using drill-down, navigates to associated view, but on return the name of the object has disappeared. (Initially I thought the issue was between keyboard and chair, but not this has started happening more frequently). 

### Steps to Reproduce the Behaviour
1. Open a stable/complete view
2. Double click to drill down 
3. Review associated component view 
4. Close associated view; object that was drilled into now has no name

I appreciate this may be due to using the plug-in for "Specialization", however this did not happen with 4.5.* versions; only seems to have started with 4.6.0.

**Comment by Phillipus** [comment] 2019-11-26 17:49
From the log this seems to be caused by a Specialization plug-in issue. I'll close this.

Please could you re-submit this at https://github.com/archi-contribs/specialization-plugin/issues

**Closed by Phillipus** 2019-11-26 17:49 UTC

**Comment by herve91** [comment] 2019-11-26 18:27
My specialization plugin does not work (yet) with Archi 4.6.

I'm currently concentrating on my database plugin that should be ready by the end of the week, and will then have time to adapt the specialization plugin to Archi 4.6

Best regards
Hervé
