### ISSUE TITLE
HTML report does not generate Views dropdown menu

### ISSUE THREAD

**Issue by wwu206** [archimatetool/archi#784] opened 2021-11-04 13:53 UTC
### Version of Archi
Archimate tool 4.9.1
Build 202110260902

### Archi Plug-ins
coArchi 0.7.202102021056
jArchi 1.2.0.202110121451

### Operating System
Windows 10

### Expected Behaviour
When I generate a HTML Report I expected to have a "Model Content" and a "Views" dropdown menus as usual in previous versions of Archi 

### Actual Behaviour
In this version, depending on the models, I have the "Views" dropdown or not.
Without the "Views" dropdown is impossible to navigate in the model. 
Maybe is the model size? The model that doesn't have the Views dropdown, is about 3500 objects.
For the smaller models I don't have problems.

![Report with Views dropdown](https://user-images.githubusercontent.com/36263372/140325403-1ad07422-a01d-48e9-8616-d8b55c1a2460.png)
![Report without Views dropdown](https://user-images.githubusercontent.com/36263372/140325409-f648012d-1290-4004-a9a9-9536024dc7d1.png)

Cheers,
Rui

**Comment by Phillipus** [comment] 2021-11-04 13:56
Are there any errors in the error log?

The Error Log can be accessed in Archi by selecting the “About Archi” menu item. In the dialog box press the “Installation Details” button, then select the “Configuration” tab and press the “View Error Log” button.

**Comment by wwu206** [comment] 2021-11-04 14:14
Hi Phil.

Thanks for your quick response.

In attach is the error log file.

Cheers,
Rui

Rui Nuno Simões
Arquiteto de SI/TI | IS/IT Architect
[Assinatura C]
Departamento de Sistemas e Tecnologias de Informação | Information Systems and Technology Department
Núcleo de Arquitetura de SI/TI | IS/IT Architecture Unit

Rua Francisco Ribeiro, 2 | 1150-165 Lisboa
T +351 213130762
F +351 213143873
***@***.******@***.***>| www.bportugal.pt<http://www.bportugal.pt/>

Siga-nos no Twitter<twitter.com/bancodeportugal>, no LinkedIn<http://www.linkedin.com/company/17080> e no Instagram<https://www.instagram.com/bancodeportugaloficial/>

P Antes de imprimir, pense no ambiente
       Before printing, think about the environment

**Comment by Phillipus** [comment] 2021-11-04 14:16
You can't add attachments from email. You have to do it in GitHub.

**Comment by wwu206** [comment] 2021-11-04 14:17
Yes, the model has about 200 views

Rui Nuno Simões
Arquiteto de SI/TI | IS/IT Architect
[Assinatura C]
Departamento de Sistemas e Tecnologias de Informação | Information Systems and Technology Department
Núcleo de Arquitetura de SI/TI | IS/IT Architecture Unit

Rua Francisco Ribeiro, 2 | 1150-165 Lisboa
T +351 213130762
F +351 213143873
***@***.******@***.***>| www.bportugal.pt<http://www.bportugal.pt/>

Siga-nos no Twitter<twitter.com/bancodeportugal>, no LinkedIn<http://www.linkedin.com/company/17080> e no Instagram<https://www.instagram.com/bancodeportugaloficial/>

P Antes de imprimir, pense no ambiente
       Before printing, think about the environment

**Comment by Phillipus** [comment] 2021-11-04 14:22
Nothing in the log of interest except:

> java.lang.Exception: org.eclipse.swt.SWTError: Not implemented [WebView2 runtime not found]

That means you have enabled the option to use the Edge Browser for the internal browser but don't have the Edge Runtime installed. Shouldn't make a difference, though.

**Comment by Phillipus** [comment] 2021-11-04 14:30
I can't reproduce it. Can you share a model privately with me that has the problem?

**Comment by wwu206** [comment] 2021-11-04 14:40
I disabled the option but the behavior is the same.

I already checked and the views are created in the file structure generated and were generated 3379 views (not 200)

Maybe the problem is on the index.html creation

**Comment by wwu206** [comment] 2021-11-04 15:40
Unfortunately, I cannot send you the model but the index file has an unexpected end.

![Index - EOF](https://user-images.githubusercontent.com/36263372/140363409-65f4a7a5-be22-4baa-ad21-8004cff1469e.png)

**Comment by Phillipus** [comment] 2021-11-04 15:51
OK, but if I can't reproduce it I can't fix it. Perhaps you can diagnose it yourself? Maybe look for factors such as the amount of elements, amount of views, whether folders are used, etc.

**Comment by wwu206** [comment] 2021-11-04 16:06
In the previous version we had installed (4.8.1), we didn't have this error, if it helps

**Comment by wwu206** [comment] 2021-11-04 16:13
As size, we have in the generation folder:
21344 elements
3379 images
20429 objects
3379 views

**Comment by Phillipus** [comment] 2021-11-04 16:49
I can't diagnose this without a model that has the problem.

But maybe you could try a process of elimination - is it the amount of elements? The amount of relations? The amount of views? Try using folders. Try on a different machine, or check there's enough memory.

Sorry, but I can only guess at this point.

**Comment by wwu206** [comment] 2021-11-05 09:57
Hi.
Where cian I found the version 4.9.0?
I'd like to try to install this version but I cannot find it.
Cheers

**Comment by Phillipus** [comment] 2021-11-05 11:04
Version 4.9.0 has no differences in the reporting. You should compare with 4.8.1.

**Comment by wwu206** [comment] 2021-11-05 11:06
Ok, 4.8.1 works perfectly

**Comment by Phillipus** [comment] 2021-11-05 11:15
You say you are using images. Perhaps this is a factor.

But as I said, I can only guess unless I have a model to reproduce the problem. Did you try all the things I mentioned in https://github.com/archimatetool/archi/issues/784#issuecomment-961228596

**Comment by Phillipus** [comment] 2021-11-05 14:29
@wwu206 Something you could try:

1. Install a new zip version of Archi 4.9.1
2. Copy the folder `Archi\plugins\com.archimatetool.reports_4.8.1.202101181039\templates`
3. Replace in folder `Archi\plugins\com.archimatetool.reports_4.9.1.202110260902\templates`

This will mean that Archi 4.9.1 will then use the old code for generating HTML reports. Then we can see if the problem is there.

**Comment by wwu206** [comment] 2021-11-05 14:35
@Phillipus I think I've found the problem:
In some of the serve relations appears a blank property with information. I removed two of them (in two different phases) and the index.html file grew in both times.
Now I'm checking for more.
I'll let you know as soon as I have more news.
Thanks

**Comment by Phillipus** [comment] 2021-11-05 15:32
I added a blank property to an element (same for relationship). I see this in my error output:

```
context [/modelreport /expandFolder /_sub1 /expandFolder /_sub2 /classesFromProperties /_sub3] 1:25 internal error: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at org.stringtemplate.v4.STGroup.getEmbeddedInstanceOf(STGroup.java:177)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:235)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeIterator(Interpreter.java:772)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:747)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeIterator(Interpreter.java:772)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:747)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeIterator(Interpreter.java:772)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:747)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.ST.write(ST.java:427)
	at org.stringtemplate.v4.ST.render(ST.java:497)
	at org.stringtemplate.v4.ST.render(ST.java:491)
	at org.stringtemplate.v4.ST.render(ST.java:487)
	at com.archimatetool.reports.html.HTMLReportExporter.createReport(HTMLReportExporter.java:257)
```

**Comment by Phillipus** [comment] 2021-11-05 15:48
@jbsarrodie I think the cause might be in `modelreport.st`, can you take a look?:

```
classesFromProperties(object) ::= <<
^object.Properties:{p | ^(p.Key)(p.Value)^ }^
>>
```

Also, the order of folders is different:

![report](https://user-images.githubusercontent.com/600504/140538978-045892bc-cba0-4b2f-931e-0922274d4daf.png)

**Comment by wwu206** [comment] 2021-11-05 16:10
Hi.

I already can see some views, but only about 10% of them.

Now the index file end like the file attach

![image](https://user-images.githubusercontent.com/36263372/140542317-935514ed-9f53-4811-94e9-6811459d46ff.png)

**Comment by Phillipus** [comment] 2021-11-05 16:11
You could remove all the empty properties in the model with a jArchi script.

**Comment by wwu206** [comment] 2021-11-05 16:15
I'll try that during the weekend

We talk again on Monday

**Comment by wwu206** [comment] 2021-11-08 11:07
Hi Phil.

The problem is solved.

To have the HTML generated properly, I had to delete all the properties from the Serving relationship type filled or not.

Hope it helps to solve the problem in future versions.

Cheers,
Rui

**Comment by Phillipus** [comment] 2021-11-08 11:09
Hi Rui,

thanks for the feedback. I think it's not really a problem with Serving relationship but rather empty properties.

@jbsarrodie What do you think?

**Comment by wwu206** [comment] 2021-11-08 11:26
For me only cleaning the properties from the serving relation solved the problem.

Is strange that in my case with a so big model there no more empty properties in other objects.

We have lots of properties in all objects, except in relations. In relations we use only the "Documentation" to fill all information (these cases, I my case, should not exist) . Maybe the problem is only in the properties tab in relations. For us, all other relationship types have no properties specified neither filled. 

Hope it help,
Rui

**Comment by Phillipus** [comment] 2021-11-08 11:39
A test model consisting of two elements, and a serving relationship with a Property with name and value outputs this to the console:

`context [/modelreport /expandFolder /_sub2 /classesFromProperties /_sub3] 1:25 no such template: /Any`

If the property consists of just a name, "test" this is output:

`context [/modelreport /expandFolder /_sub98 /classesFromProperties /_sub99] 1:25 no such template: /test`

If the property is empty (no name, no value) this exception occurs:

```
context [/modelreport /expandFolder /_sub34 /classesFromProperties /_sub35] 1:25 internal error: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at org.stringtemplate.v4.STGroup.getEmbeddedInstanceOf(STGroup.java:177)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:235)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeIterator(Interpreter.java:772)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:747)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeIterator(Interpreter.java:772)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:747)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.Interpreter.writeObject(Interpreter.java:742)
	at org.stringtemplate.v4.Interpreter.writeObjectNoOptions(Interpreter.java:674)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:285)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.ST.write(ST.java:427)
	at org.stringtemplate.v4.ST.render(ST.java:497)
	at org.stringtemplate.v4.ST.render(ST.java:491)
	at org.stringtemplate.v4.ST.render(ST.java:487)
	at com.archimatetool.reports.html.HTMLReportExporter.createReport(HTMLReportExporter.java:257)
```

**Comment by wwu206** [comment] 2021-11-08 11:40
I just checked that I have lots of properties in objects and views with the "Name" filled and with the "Value" empty.

**Comment by jbsarrodie** [comment] 2021-11-08 19:40
> @jbsarrodie What do you think?

I think this is related to the new feature which makes it possible to hide some entries from the menu. I had to use a trick which generates a classname based on property name and value. I think generation failed when name and/or value is empty. I must admit that thanks to my OCD, all my properties have name and value ;-)

This should be easy to fix I think, but will take me some days before I can look at it.

**Comment by jbsarrodie** [comment] 2022-01-04 11:31
Both bugs should be fixed in the `html_report_fix` branch.

@wwu206 I've never been able to reproduce your issue and you never shared your model with us, so could you please either share the "faulty" model with us or test this patch on your side (on Archi 4.9, manually edit `archi/com.archimatetool.reports/templates/st/modelreport.stg` to replace it with [this one](https://raw.githubusercontent.com/archimatetool/archi/e0dac1fabbbdd75d28d538db18bf04e11956db85/com.archimatetool.reports/templates/st/modelreport.stg)). This version no more raises a JAVA error on properties with "empty" name.

> A test model consisting of two elements, and a serving relationship with a Property with name and value outputs this to the console:
> 
> `context [/modelreport /expandFolder /_sub2 /classesFromProperties /_sub3] 1:25 no such template: /Any`
> 
> If the property consists of just a name, "test" this is output:
> 
> `context [/modelreport /expandFolder /_sub98 /classesFromProperties /_sub99] 1:25 no such template: /test`

These are "normal" warnings which are due to the way my trick works (it calls a template function based on the name of the property). I've made it a bit more explicite that these warnings could be igored.

**Comment by Phillipus** [comment] 2022-01-04 11:57
@jbsarrodie I'm getting:

`context [/modelreport /expandFolder /_sub18 /classesFromProperties /_sub19] 1:25 no such template: /IGNORE_ERROR_`

Test model consisting of two elements, and a serving relationship with a Property with empty name and value.

**Comment by jbsarrodie** [comment] 2022-01-04 13:10
> @jbsarrodie I'm getting:
> 
> `context [/modelreport /expandFolder /_sub18 /classesFromProperties /_sub19] 1:25 no such template: /IGNORE_ERROR_`
> 
> Test model consisting of two elements, and a serving relationship with a Property with empty name and value.

That's intended behavior: this is an internal StringTemplate message raised because we try to call a non existent function which name is forged by concatenating `IGNORE_ERROR_` and the property's name.

**Comment by Phillipus** [comment] 2022-01-04 16:22
These fixes are present in Archi 4.9.2 beta 3. Pleased test. 👍 

https://www.archimatetool.com/beta/

**Comment by wwu206** [comment] 2022-01-05 12:15
Hi Phil.

I’ll download and test as soon as we can (as we work in a shared environment). I’ll give you news as soon as possible.

Thanks.

Have a nice 2022 and best regards,
Rui

Rui Nuno Simões
Arquiteto de SI/TI | IS/IT Architect
[Assinatura C]
Departamento de Sistemas e Tecnologias de Informação | Information Systems and Technology Department
Núcleo de Arquitetura de SI/TI | IS/IT Architecture Unit

Rua Francisco Ribeiro, 2 | 1150-165 Lisboa
T +351 213130762
F +351 213143873
***@***.******@***.***>| www.bportugal.pt<http://www.bportugal.pt/>

Siga-nos no Twitter<twitter.com/bancodeportugal>, no LinkedIn<http://www.linkedin.com/company/17080> e no Instagram<https://www.instagram.com/bancodeportugaloficial/>

P Antes de imprimir, pense no ambiente
       Before printing, think about the environment

**Comment by Phillipus** [comment] 2022-01-09 12:09
@jbsarrodie I've merged (and deleted) your branch. Thanks for the fix!

**Comment by Phillipus** [comment] 2022-01-09 12:10
Re-opening because the merge commit to GitHub auto-magically closed it.

**Comment by Phillipus** [comment] 2022-01-09 12:10
Re-opening because the merge commit to GitHub auto-magically closed it.

**Comment by Phillipus** [comment] 2022-01-16 14:51
Let's close this one. Please add a comment if the issue happens again.

**Closed by Phillipus** 2022-01-16 14:51 UTC
